In [ ]:
!pip -q install --no-cache-dir "numpy==1.26.4" "pandas==2.2.2"
!pip -q install --no-cache-dir "opencv-python-headless==4.10.0.84"
!pip -q install --no-cache-dir decord tqdm einops
!pip -q install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cu121
!pip -q install --no-cache-dir "ultralytics==8.3.0"
!pip -q install --no-cache-dir "emotiefflib[torch]"

In [ ]:
import os
from pathlib import Path

ROOT = "/content/miga_data"
SRC_DIR = "/content/src"

Path(ROOT).mkdir(parents=True, exist_ok=True)
Path(SRC_DIR).mkdir(parents=True, exist_ok=True)

print("ROOT:", ROOT)
print("SRC_DIR:", SRC_DIR)

ROOT: /content/miga_data
SRC_DIR: /content/src

In [ ]:
from google.colab import drive
drive.mount("/content/drive")


FEAT_DIR = "/content/drive/MyDrive/miga_features_cache_agcn"

Mounted at /content/drive

In [ ]:
DATA_DIR = "/content/miga_data"
!mkdir -p $DATA_DIR

!wget -O $DATA_DIR/imigue_skeleton_phase1.zip https://miga3.a3s.fi/imigue_skeleton_phase1.zip

!wget -O $DATA_DIR/imigue_rgb_phase1.zip https://miga3.a3s.fi/imigue_rgb_phase1.zip

!wget -O $DATA_DIR/imigue_skeleton_phase2.zip https://miga3.a3s.fi/imigue_skeleton_phase2.zip

!wget -O $DATA_DIR/imigue_rgb_phase2.zip https://miga3.a3s.fi/imigue_rgb_phase2.zip

--2026-01-17 13:19:13--  https://miga3.a3s.fi/imigue_skeleton_phase1.zip
Resolving miga3.a3s.fi (miga3.a3s.fi)... 86.50.254.18, 86.50.254.19
Connecting to miga3.a3s.fi (miga3.a3s.fi)|86.50.254.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6270753807 (5.8G) [application/zip]
Saving to: ‘/content/miga_data/imigue_skeleton_phase1.zip’

/content/miga_data/ 100%[===================>]   5.84G  19.2MB/s    in 5m 17s

2026-01-17 13:24:32 (18.8 MB/s) - ‘/content/miga_data/imigue_skeleton_phase1.zip’ saved [6270753807/6270753807]

--2026-01-17 13:24:32--  https://miga3.a3s.fi/imigue_rgb_phase1.zip
Resolving miga3.a3s.fi (miga3.a3s.fi)... 86.50.254.18, 86.50.254.19
Connecting to miga3.a3s.fi (miga3.a3s.fi)|86.50.254.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6512356945 (6.1G) [application/zip]
Saving to: ‘/content/miga_data/imigue_rgb_phase1.zip’

/content/miga_data/ 100%[===================>]   6.06G  20.5MB/s    in 5m 19s

2026-01-17 13:29:53 (19.5 MB/s) - ‘/content/miga_data/imigue_rgb_phase1.zip’ saved [6512356945/6512356945]

--2026-01-17 13:29:53--  https://miga3.a3s.fi/imigue_skeleton_phase2.zip
Resolving miga3.a3s.fi (miga3.a3s.fi)... 86.50.254.18, 86.50.254.19
Connecting to miga3.a3s.fi (miga3.a3s.fi)|86.50.254.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1948103204 (1.8G) [application/zip]
Saving to: ‘/content/miga_data/imigue_skeleton_phase2.zip’

/content/miga_data/ 100%[===================>]   1.81G  18.5MB/s    in 1m 52s

2026-01-17 13:31:46 (16.7 MB/s) - ‘/content/miga_data/imigue_skeleton_phase2.zip’ saved [1948103204/1948103204]

--2026-01-17 13:31:46--  https://miga3.a3s.fi/imigue_rgb_phase2.zip
Resolving miga3.a3s.fi (miga3.a3s.fi)... 86.50.254.18, 86.50.254.19
Connecting to miga3.a3s.fi (miga3.a3s.fi)|86.50.254.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2277100195 (2.1G) [application/zip]
Saving to: ‘/content/miga_data/imigue_rgb_phase2.zip’

/content/miga_data/ 100%[===================>]   2.12G  20.3MB/s    in 1m 50s

2026-01-17 13:33:38 (19.7 MB/s) - ‘/content/miga_data/imigue_rgb_phase2.zip’ saved [2277100195/2277100195]

In [ ]:
!unzip -q $DATA_DIR/imigue_skeleton_phase1.zip -d $DATA_DIR
!unzip -q $DATA_DIR/imigue_rgb_phase1.zip -d $DATA_DIR
!unzip -q $DATA_DIR/imigue_skeleton_phase2.zip -d $DATA_DIR
!unzip -q $DATA_DIR/imigue_rgb_phase2.zip -d $DATA_DIR

In [ ]:
!rm $DATA_DIR/*.zip

In [ ]:
%%writefile /content/src/__init__.py

Overwriting /content/src/__init__.py

In [ ]:
%%writefile /content/src/paths.py
import os, glob

ROOT = "/content/miga_data"

RGB_P1_TRAIN = f"{ROOT}/imigue_rgb_phase1/train_data"
RGB_P1_VAL   = f"{ROOT}/imigue_rgb_phase1/validation_data"
RGB_P2       = f"{ROOT}/imigue_rgb_phase2"

SK_P1_TRAIN  = f"{ROOT}/imigue_data_phase1/datasets/imigue_skeleton_train"
SK_P1_VAL    = f"{ROOT}/imigue_data_phase1/datasets/imigue_skeleton_validate"
SK_P2_TEST   = f"{ROOT}/imigue_data_phase2/imigue_skeleton_test"

def vid4(x): return f"{int(x):04d}"

def resolve_video_path_phase1(video_id, split):
    v = vid4(video_id)
    if split == "train":
        p = os.path.join(RGB_P1_TRAIN, v, f"{v}.mp4")
        return p if os.path.exists(p) else None
    if split == "val":
        p = os.path.join(RGB_P1_VAL, v, f"{v}.mp4")
        return p if os.path.exists(p) else None
    for p in [
        os.path.join(RGB_P1_TRAIN, v, f"{v}.mp4"),
        os.path.join(RGB_P1_VAL, v, f"{v}.mp4"),
    ]:
        if os.path.exists(p): return p
    return None

def resolve_video_path_phase2(video_id):
    v = vid4(video_id)
    p = os.path.join(RGB_P2, v, f"{v}.mp4")
    if os.path.exists(p): return p
    hits = glob.glob(os.path.join(RGB_P2, "**", f"{v}.mp4"), recursive=True)
    return hits[0] if hits else None

def resolve_skeleton_path_phase1(video_id, split, prefer_hand=True):
    v = vid4(video_id)
    base = SK_P1_TRAIN if split=="train" else SK_P1_VAL
    p_hand  = os.path.join(base, v, f"{v}_light_hand.csv")
    p_light = os.path.join(base, v, f"{v}_light.csv")
    if prefer_hand and os.path.exists(p_hand): return p_hand
    if os.path.exists(p_light): return p_light
    if os.path.exists(p_hand):  return p_hand
    return None

def resolve_skeleton_path_phase2(video_id, prefer_hand=True):
    v = vid4(video_id)
    p_hand  = os.path.join(SK_P2_TEST, v, f"{v}_light_hand.csv")
    p_light = os.path.join(SK_P2_TEST, v, f"{v}_light.csv")
    if prefer_hand and os.path.exists(p_hand): return p_hand
    if os.path.exists(p_light): return p_light
    if os.path.exists(p_hand):  return p_hand
    return None

Overwriting /content/src/paths.py

In [ ]:
import os
import pandas as pd
import glob, os

ROOT = "/content/miga_data"

train_csv = f"{ROOT}/imigue_rgb_phase1/train_label.csv"
val_csv   = f"{ROOT}/imigue_rgb_phase1/validation_label.csv"

train_df = pd.read_csv(train_csv)
val_df   = pd.read_csv(val_csv)

train_df["split"] = "train"
val_df["split"] = "val"

phase1_all = pd.concat([train_df, val_df], ignore_index=True)

def vid4(x):
    return f"{int(x):04d}"

def video_path(row):
    v = vid4(row["video_id"])
    if row["split"] == "train":
        return f"{ROOT}/imigue_rgb_phase1/train_data/{v}/{v}.mp4"
    else:
        return f"{ROOT}/imigue_rgb_phase1/validation_data/{v}/{v}.mp4"

def skeleton_path(row):
    v = f"{int(row['video_id']):04d}"
    roots = [
        "/content/miga_data/imigue_data_phase1",
        "/content/miga_data",
    ]
    for root in roots:
        hits = glob.glob(f"{root}/**/{v}*_light*.csv", recursive=True)
        if hits:
            return hits[0]
    return None


phase1_all["skeleton_path"] = phase1_all.apply(skeleton_path, axis=1)
phase1_all.to_csv("/content/phase1_all_with_split.csv", index=False)

In [ ]:
%%writefile /content/src/agcn.py
import torch
import torch.nn as nn
import torch.nn.functional as F


class AGCNBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv_t = nn.Conv2d(in_channels, out_channels, kernel_size=(9, 1), padding=(4, 0))
        self.conv_v = nn.Conv2d(out_channels, out_channels, kernel_size=(1, 1))
        self.bn = nn.BatchNorm2d(out_channels)

    def forward(self, x):
        x = self.conv_t(x)
        x = self.conv_v(x)
        x = self.bn(x)
        return F.relu(x)


class AGCNModel(nn.Module):

    def __init__(self, in_channels=3, hidden=64, out_dim=512):
        super().__init__()

        self.data_bn = nn.BatchNorm1d(in_channels * 25)

        self.block1 = AGCNBlock(in_channels, hidden)
        self.block2 = AGCNBlock(hidden, hidden * 2)
        self.block3 = AGCNBlock(hidden * 2, hidden * 4)

        self.pool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(hidden * 4, out_dim)

    def forward(self, x):
        B, T, V, C = x.shape

        x = x.permute(0, 3, 1, 2).contiguous()

        x = x.view(B, C * V, T)
        x = self.data_bn(x)
        x = x.view(B, C, V, T).permute(0, 1, 3, 2)

        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)

        x = self.pool(x).view(B, -1)
        x = self.fc(x)
        return x

Overwriting /content/src/agcn.py

In [ ]:
%%writefile /content/src/feature_extract.py
import os
import glob
import hashlib
from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

from decord import VideoReader, cpu


MIGA_ROOT = os.environ.get("MIGA_ROOT", "/content/miga_data")

RGB_P1_TRAIN = f"{MIGA_ROOT}/imigue_rgb_phase1/train_data"
RGB_P1_VAL   = f"{MIGA_ROOT}/imigue_rgb_phase1/validation_data"
RGB_P2       = f"{MIGA_ROOT}/imigue_rgb_phase2"

SK_P1_TRAIN  = f"{MIGA_ROOT}/imigue_data_phase1/datasets/imigue_skeleton_train"
SK_P1_VAL    = f"{MIGA_ROOT}/imigue_data_phase1/datasets/imigue_skeleton_validate"
SK_P2_TEST   = f"{MIGA_ROOT}/imigue_data_phase2/imigue_skeleton_test"


def vid4(x: int) -> str:
    return f"{int(x):04d}"


def resolve_video_path_phase1(video_id: int, split: str) -> Optional[str]:
    v = vid4(video_id)
    if split == "train":
        p = os.path.join(RGB_P1_TRAIN, v, f"{v}.mp4")
        return p if os.path.exists(p) else None
    if split == "val":
        p = os.path.join(RGB_P1_VAL, v, f"{v}.mp4")
        return p if os.path.exists(p) else None
    for p in [
        os.path.join(RGB_P1_TRAIN, v, f"{v}.mp4"),
        os.path.join(RGB_P1_VAL, v, f"{v}.mp4"),
    ]:
        if os.path.exists(p):
            return p
    return None


def resolve_video_path_phase2(video_id: int) -> Optional[str]:
    v = vid4(video_id)
    p = os.path.join(RGB_P2, v, f"{v}.mp4")
    if os.path.exists(p):
        return p
    hits = glob.glob(os.path.join(RGB_P2, "**", f"{v}.mp4"), recursive=True)
    return hits[0] if hits else None


def resolve_skeleton_path_phase1(video_id: int, split: str, prefer_hand: bool = True) -> Optional[str]:
    v = vid4(video_id)
    base = SK_P1_TRAIN if split == "train" else SK_P1_VAL
    p_hand  = os.path.join(base, v, f"{v}_light_hand.csv")
    p_light = os.path.join(base, v, f"{v}_light.csv")
    if prefer_hand and os.path.exists(p_hand): return p_hand
    if os.path.exists(p_light): return p_light
    if os.path.exists(p_hand):  return p_hand
    return None


def resolve_skeleton_path_phase2(video_id: int, prefer_hand: bool = True) -> Optional[str]:
    v = vid4(video_id)
    p_hand  = os.path.join(SK_P2_TEST, v, f"{v}_light_hand.csv")
    p_light = os.path.join(SK_P2_TEST, v, f"{v}_light.csv")
    if prefer_hand and os.path.exists(p_hand): return p_hand
    if os.path.exists(p_light): return p_light
    if os.path.exists(p_hand):  return p_hand
    return None



def cache_key(video_id: int, split: str, phase: int) -> str:
    s = f"{int(video_id)}|{split}|{phase}"
    return hashlib.md5(s.encode("utf-8")).hexdigest()[:12]


def cache_paths(feat_dir: str, video_id: int, split: str, phase: int) -> Dict[str, str]:
    key = cache_key(video_id, split, phase)
    d = Path(feat_dir)
    d.mkdir(parents=True, exist_ok=True)
    return {
        "ctx":   str(d / f"{key}_ctx.pt"),
        "face":  str(d / f"{key}_face.pt"),
        "fmask": str(d / f"{key}_facemask.pt"),
        "skel":  str(d / f"{key}_skel.pt"),
        "smask": str(d / f"{key}_skelmask.pt"),
    }



def _vr(path: str) -> VideoReader:
    return VideoReader(path, ctx=cpu(0))



_CTX_MODEL = None

def build_ctx_model(device: str = "cuda"):
    global _CTX_MODEL
    if _CTX_MODEL is not None:
        _CTX_MODEL.to(device)
        _CTX_MODEL.eval()
        return _CTX_MODEL

    import torchvision
    from torchvision.models.video import r3d_18, R3D_18_Weights

    weights = R3D_18_Weights.DEFAULT
    model = r3d_18(weights=weights)
    model.fc = nn.Identity()
    model = model.to(device).eval()
    _CTX_MODEL = model
    return _CTX_MODEL


def _preprocess_clip_torch(clip_rgb: np.ndarray, device: str) -> torch.Tensor:
    x = torch.from_numpy(clip_rgb).to(torch.float32) / 255.0
    x = x.permute(3, 0, 1, 2)
    x = x.unsqueeze(0)

    x = F.interpolate(x, size=(x.shape[2], 112, 112), mode="trilinear", align_corners=False)

    mean = torch.tensor([0.43216, 0.394666, 0.37645], device=x.device).view(1,3,1,1,1)
    std  = torch.tensor([0.22803, 0.22145, 0.216989], device=x.device).view(1,3,1,1,1)
    x = (x - mean) / std
    return x.to(device)


@torch.no_grad()
def extract_ctx_stream(video_path: str, device: str = "cuda", chunk: int = 32) -> torch.Tensor:
    model = build_ctx_model(device=device)
    vr = _vr(video_path)
    T = len(vr)
    if T <= 0:
        return torch.zeros((0, 512), dtype=torch.float32)

    pad = (-T) % chunk
    total = T + pad

    feats = []
    for i in range(0, total, chunk):
        idxs = list(range(i, min(i + chunk, T)))
        if len(idxs) == 0:
            break
        frames = vr.get_batch(idxs).asnumpy()
        if frames.ndim != 4 or frames.shape[-1] != 3:
            raise RuntimeError(f"Bad frames shape from decord: {frames.shape}")

        if frames.shape[0] < chunk:
            frames = np.concatenate([frames, np.repeat(frames[-1:], chunk - frames.shape[0], axis=0)], axis=0)

        x = _preprocess_clip_torch(frames, device=device)
        f = model(x).squeeze(0).detach().cpu()
        feats.append(f)

    return torch.stack(feats, dim=0).to(torch.float32)




_FACE_MODEL = None
_EMO_REC = None

def _init_yolo():
    global _FACE_MODEL
    if _FACE_MODEL is not None:
        return _FACE_MODEL
    try:
        from ultralytics import YOLO
        for w in ["yolov8n-face.pt", "yolov8n.pt"]:
            try:
                _FACE_MODEL = YOLO(w)
                break
            except Exception:
                _FACE_MODEL = None
    except Exception:
        _FACE_MODEL = None
    return _FACE_MODEL


def _center_crop(img, size=224):
    h, w = img.shape[:2]
    s = min(h, w)
    y0 = (h - s) // 2
    x0 = (w - s) // 2
    crop = img[y0:y0+s, x0:x0+s]
    import cv2
    crop = cv2.resize(crop, (size, size))
    return crop


def _detect_face_crop(img_rgb, size=224):
    model = _init_yolo()
    if model is None:
        return _center_crop(img_rgb, size=size), False

    try:
        res = model.predict(source=img_rgb, verbose=False)
        if len(res) == 0 or res[0].boxes is None or len(res[0].boxes) == 0:
            return _center_crop(img_rgb, size=size), False
        boxes = res[0].boxes.xyxy.detach().cpu().numpy()
        areas = (boxes[:,2]-boxes[:,0])*(boxes[:,3]-boxes[:,1])
        b = boxes[int(np.argmax(areas))]
        x1, y1, x2, y2 = [int(max(0, v)) for v in b]
        x2 = min(x2, img_rgb.shape[1]-1)
        y2 = min(y2, img_rgb.shape[0]-1)
        crop = img_rgb[y1:y2, x1:x2]
        if crop.size == 0:
            return _center_crop(img_rgb, size=size), False
        import cv2
        crop = cv2.resize(crop, (size, size))
        return crop, True
    except Exception:
        return _center_crop(img_rgb, size=size), False


def _init_emotieff(device: str):
    global _EMO_REC
    if _EMO_REC is not None:
        return _EMO_REC

    from emotiefflib.facial_analysis import EmotiEffLibRecognizerTorch

    try:
        _EMO_REC = EmotiEffLibRecognizerTorch(device=device)
    except TypeError:
        _EMO_REC = EmotiEffLibRecognizerTorch()
    return _EMO_REC


def _as_rgb_uint8(face_rgb_224):
    x = face_rgb_224
    if isinstance(x, torch.Tensor):
        x = x.detach().cpu().numpy()
    x = np.asarray(x)
    if x.dtype != np.uint8:
        x = np.clip(x, 0, 255).astype(np.uint8)
    return x


@torch.no_grad()
def emotieff_embed(face_rgb_224: np.ndarray, device: str = "cuda") -> np.ndarray:

    rec = _init_emotieff(device=device)
    x = _as_rgb_uint8(face_rgb_224)

    for name in [
        "get_face_embedding",
        "get_embedding",
        "get_embeddings",
        "extract_embedding",
        "extract_embeddings",
        "get_features",
        "extract_features",
    ]:
        if hasattr(rec, name) and callable(getattr(rec, name)):
            out = getattr(rec, name)(x)
            out = np.asarray(out).reshape(-1).astype(np.float32)
            return out

    if callable(rec):
        out = rec(x)
        if isinstance(out, dict):
            for k in ["embedding", "emb", "features", "feature"]:
                if k in out:
                    return np.asarray(out[k]).reshape(-1).astype(np.float32)
        out = np.asarray(out).reshape(-1).astype(np.float32)
        return out

    for attr in ["model", "net", "backbone"]:
        if hasattr(rec, attr):
            m = getattr(rec, attr)
            if isinstance(m, nn.Module):
                m = m.to(device).eval()
                t = torch.from_numpy(x).to(torch.float32) / 255.0
                t = t.permute(2, 0, 1).unsqueeze(0).to(device)

                for nm in ["forward_features", "extract_features", "features"]:
                    if hasattr(m, nm) and callable(getattr(m, nm)):
                        feat = getattr(m, nm)(t)
                        feat = feat.reshape(feat.shape[0], -1)
                        return feat.squeeze(0).detach().cpu().numpy().astype(np.float32)

                feat = m(t)
                feat = feat.reshape(feat.shape[0], -1)
                return feat.squeeze(0).detach().cpu().numpy().astype(np.float32)

    raise RuntimeError("EmotiEffLib: не удалось получить embedding")


@torch.no_grad()
def extract_face_windows(video_path: str, device: str = "cuda", chunk: int = 32) -> Tuple[torch.Tensor, torch.Tensor]:

    vr = _vr(video_path)
    T = len(vr)
    if T <= 0:
        return torch.zeros((0, 1280), dtype=torch.float32), torch.zeros((0,), dtype=torch.bool)

    pad = (-T) % chunk
    total = T + pad

    feats = []
    mask = []
    D = None

    for i in range(0, total, chunk):
        mid = min(i + chunk // 2, T - 1)
        frame = vr[mid].asnumpy()

        crop, ok = _detect_face_crop(frame, size=224)

        if ok:
            emb = emotieff_embed(crop, device=device)
            if D is None:
                D = int(emb.shape[0])
            feats.append(torch.from_numpy(emb).to(torch.float32))
            mask.append(True)
        else:
            mask.append(False)
            if D is None:
                D = 1280
            feats.append(torch.zeros((D,), dtype=torch.float32))

    face = torch.stack(feats, dim=0)
    fmask = torch.tensor(mask, dtype=torch.bool)
    return face, fmask



_SKEL_PROJ = None

def _skel_projector(in_dim: int, out_dim: int = 512) -> nn.Module:
    global _SKEL_PROJ
    if _SKEL_PROJ is not None and getattr(_SKEL_PROJ, "_in_dim", None) == in_dim:
        return _SKEL_PROJ
    torch.manual_seed(42)
    proj = nn.Sequential(
        nn.Linear(in_dim, out_dim),
        nn.LayerNorm(out_dim),
        nn.GELU(),
    )
    proj._in_dim = in_dim
    _SKEL_PROJ = proj.eval()
    return _SKEL_PROJ


def _load_skeleton_csv(path: str) -> np.ndarray:
    df = pd.read_csv(path)
    arr = df.values.astype(np.float32)
    return arr  # (T,D)


@torch.no_grad()
def extract_skeleton_windows(skel_csv_path: str, device: str = "cpu", chunk: int = 32) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Return:
      skel:  (W,512) float32
      smask: (W,) bool
    """
    arr = _load_skeleton_csv(skel_csv_path)
    T, D = arr.shape
    if T <= 0:
        return torch.zeros((0, 512), dtype=torch.float32), torch.zeros((0,), dtype=torch.bool)

    pad = (-T) % chunk
    total = T + pad
    if pad:
        arr = np.concatenate([arr, np.repeat(arr[-1:], pad, axis=0)], axis=0)

    proj = _skel_projector(D, 512)

    feats = []
    mask = []
    for i in range(0, total, chunk):
        w = arr[i:i+chunk]
        valid = not np.allclose(w, 0)
        x = torch.from_numpy(w.mean(axis=0)).to(torch.float32)
        z = proj(x).detach().cpu()
        feats.append(z)
        mask.append(valid)

    skel = torch.stack(feats, dim=0).to(torch.float32)
    smask = torch.tensor(mask, dtype=torch.bool)
    return skel, smask




@torch.no_grad()
def build_and_cache_one(
    video_id: int,
    split: str,
    phase: int,
    feat_dir: str,
    chunk: int = 32,
    vpath: Optional[str] = None,
    spath: Optional[str] = None,
    do_ctx: bool = True,
    do_face: bool = True,
    do_skel: bool = True,
    device: str = "cuda",
):
    ps = cache_paths(feat_dir, video_id, split, phase)


    if vpath is None:
        if phase == 1:
            vpath = resolve_video_path_phase1(video_id, split)
        else:
            vpath = resolve_video_path_phase2(video_id)

    if spath is None:
        if phase == 1:
            spath = resolve_skeleton_path_phase1(video_id, split)
        else:
            spath = resolve_skeleton_path_phase2(video_id)

    if do_ctx or do_face:
        if vpath is None or (not os.path.exists(vpath)):
            raise FileNotFoundError(f"RGB video not found for id={video_id} split={split} phase={phase}")

    if do_skel:
        if spath is None or (not os.path.exists(spath)):
            raise FileNotFoundError(f"Skeleton csv not found for id={video_id} split={split} phase={phase}")

    if do_ctx and (not os.path.exists(ps["ctx"])):
        ctx = extract_ctx_stream(vpath, device=device, chunk=chunk)   # (W,512)
        torch.save(ctx, ps["ctx"])

    if do_face and (not os.path.exists(ps["face"])) and (not os.path.exists(ps["fmask"])):
        face, fmask = extract_face_windows(vpath, device=device, chunk=chunk)  # (W,D)
        torch.save(face, ps["face"])
        torch.save(fmask, ps["fmask"])

    if do_skel and (not os.path.exists(ps["skel"])) and (not os.path.exists(ps["smask"])):
        skel, smask = extract_skeleton_windows(spath, device="cpu", chunk=chunk)  # (W,512)
        torch.save(skel, ps["skel"])
        torch.save(smask, ps["smask"])

    return ps

Overwriting /content/src/feature_extract.py

In [ ]:
%%writefile /content/src/cache_features_cli.py
import argparse
import pandas as pd
from tqdm import tqdm
import torch
import traceback

from src.feature_extract import build_and_cache_one

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", required=True)
    ap.add_argument("--phase", type=int, required=True)
    ap.add_argument("--feat_dir", required=True)
    ap.add_argument("--chunk", type=int, default=32)
    ap.add_argument("--start", type=int, default=0)
    ap.add_argument("--end", type=int, default=999999)
    ap.add_argument("--split_col", type=str, default="split")
    ap.add_argument("--device", choices=["auto","cpu","cuda"], default="auto")
    ap.add_argument("--do_ctx", action="store_true")
    ap.add_argument("--do_face", action="store_true")
    ap.add_argument("--do_skel", action="store_true")
    args = ap.parse_args()

    if args.device == "auto":
        device = "cuda" if torch.cuda.is_available() else "cpu"
    else:
        device = args.device

    if not (args.do_ctx or args.do_face or args.do_skel):
        args.do_ctx = args.do_face = args.do_skel = True

    print("DEVICE:", device)
    print("FEAT_DIR:", args.feat_dir)
    print("MODES: ctx=", args.do_ctx, "face=", args.do_face, "skel=", args.do_skel)

    df = pd.read_csv(args.csv)
    df = df.iloc[args.start:args.end].reset_index(drop=True)

    ok, bad = 0, 0

    for i, r in tqdm(df.iterrows(), total=len(df)):
        try:
            vid = int(r["video_id"])
            split = r.get(args.split_col, "test")

            build_and_cache_one(
                video_id=vid,
                split=split,
                phase=args.phase,
                feat_dir=args.feat_dir,
                chunk=args.chunk,
                vpath=None,
                spath=r.get("skeleton_path", None),
                do_ctx=args.do_ctx,
                do_face=args.do_face,
                do_skel=args.do_skel,
                device=device,
            )
            ok += 1

        except Exception:
            bad += 1
            print(" ERROR")
            print("row:", i, "video_id:", r.get("video_id"), "split:", r.get(args.split_col, ""))
            if "skeleton_path" in r:
                print("skeleton_path:", r.get("skeleton_path"))
            traceback.print_exc()

    print(f"\nDONE shard [{args.start}:{args.end}) ok={ok} bad={bad}")

if __name__ == "__main__":
    main()

Overwriting /content/src/cache_features_cli.py

In [ ]:
%%bash
CHUNK=64
SHARD=10
DEVICE=cuda
CSV=/content/phase1_all_with_split.csv
FEAT_DIR=/content/drive/MyDrive/miga_features_cache_agcn

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase1_all_with_split.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD))
  if [ $END -gt $TOTAL ]; then END=$TOTAL; fi

  echo "=== CTX shard $START:$END (chunk=$CHUNK) ==="
  PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 python -u /content/src/cache_features_cli.py \
    --csv $CSV --phase 1 --feat_dir $FEAT_DIR \
    --chunk $CHUNK --start $START --end $END --device $DEVICE \
    --do_ctx

  START=$END
done

=== CTX shard 0:10 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [0:10) ok=10 bad=0
=== CTX shard 10:20 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [10:20) ok=10 bad=0
=== CTX shard 20:30 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [20:30) ok=10 bad=0
=== CTX shard 30:40 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [30:40) ok=10 bad=0
=== CTX shard 40:50 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [40:50) ok=10 bad=0
=== CTX shard 50:60 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [50:60) ok=10 bad=0
=== CTX shard 60:70 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [60:70) ok=10 bad=0
=== CTX shard 70:80 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [70:80) ok=10 bad=0
=== CTX shard 80:90 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [80:90) ok=10 bad=0
=== CTX shard 90:100 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [90:100) ok=10 bad=0
=== CTX shard 100:110 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [100:110) ok=10 bad=0
=== CTX shard 110:120 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [110:120) ok=10 bad=0
=== CTX shard 120:130 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [120:130) ok=10 bad=0
=== CTX shard 130:140 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [130:140) ok=10 bad=0
=== CTX shard 140:150 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [140:150) ok=10 bad=0
=== CTX shard 150:160 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [150:160) ok=10 bad=0
=== CTX shard 160:170 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [160:170) ok=10 bad=0
=== CTX shard 170:180 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [170:180) ok=10 bad=0
=== CTX shard 180:190 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [180:190) ok=10 bad=0
=== CTX shard 190:200 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [190:200) ok=10 bad=0
=== CTX shard 200:210 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [200:210) ok=10 bad=0
=== CTX shard 210:220 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [210:220) ok=10 bad=0
=== CTX shard 220:230 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [220:230) ok=10 bad=0
=== CTX shard 230:240 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [230:240) ok=10 bad=0
=== CTX shard 240:250 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [240:250) ok=10 bad=0
=== CTX shard 250:255 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= True face= False skel= False

DONE shard [250:255) ok=5 bad=0

100%|██████████| 10/10 [00:00<00:00, 1759.06it/s]
100%|██████████| 10/10 [00:00<00:00, 2025.74it/s]
100%|██████████| 10/10 [00:00<00:00, 1952.75it/s]
100%|██████████| 10/10 [00:00<00:00, 1881.44it/s]
100%|██████████| 10/10 [00:00<00:00, 2027.51it/s]
100%|██████████| 10/10 [00:00<00:00, 2024.57it/s]
100%|██████████| 10/10 [00:00<00:00, 2076.49it/s]
100%|██████████| 10/10 [00:00<00:00, 2107.80it/s]
100%|██████████| 10/10 [00:00<00:00, 2152.36it/s]
100%|██████████| 10/10 [00:00<00:00, 2086.61it/s]
100%|██████████| 10/10 [00:00<00:00, 2022.62it/s]
100%|██████████| 10/10 [00:00<00:00, 2067.38it/s]
100%|██████████| 10/10 [00:00<00:00, 2069.63it/s]
100%|██████████| 10/10 [00:00<00:00, 1962.16it/s]
100%|██████████| 10/10 [00:00<00:00, 2038.54it/s]
100%|██████████| 10/10 [00:00<00:00, 1965.83it/s]
100%|██████████| 10/10 [00:00<00:00, 2073.82it/s]
100%|██████████| 10/10 [00:00<00:00, 2069.01it/s]
100%|██████████| 10/10 [00:00<00:00, 2078.65it/s]
100%|██████████| 10/10 [00:00<00:00, 1996.24it/s]
100%|██████████| 10/10 [00:00<00:00, 2120.80it/s]
100%|██████████| 10/10 [00:00<00:00, 2070.75it/s]
100%|██████████| 10/10 [00:00<00:00, 2065.65it/s]
100%|██████████| 10/10 [09:35<00:00, 57.57s/it]
100%|██████████| 10/10 [13:51<00:00, 83.15s/it]
100%|██████████| 5/5 [04:49<00:00, 57.96s/it]

In [ ]:
%%bash
CHUNK=32
SHARD=5
DEVICE=cuda
CSV=/content/phase1_all_with_split.csv
FEAT_DIR=/content/drive/MyDrive/miga_features_cache_agcn

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase1_all_with_split.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD))
  if [ $END -gt $TOTAL ]; then END=$TOTAL; fi

  echo "=== FACE shard $START:$END (device=$DEVICE) ==="
  PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 python -u /content/src/cache_features_cli.py \
    --csv $CSV --phase 1 --feat_dir $FEAT_DIR \
    --chunk $CHUNK --start $START --end $END --device $DEVICE \
    --do_face

  START=$END
done

=== FACE shard 0:5 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n.pt to 'yolov8n.pt'...
Downloading enet_b0_8_best_vgaf.pt from https://github.com/sb-ai-lab/EmotiEffLib/blob/main/models/affectnet_emotions/enet_b0_8_best_vgaf.pt?raw=true

DONE shard [0:5) ok=5 bad=0
=== FACE shard 5:10 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [5:10) ok=5 bad=0
=== FACE shard 10:15 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [10:15) ok=5 bad=0
=== FACE shard 15:20 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [15:20) ok=5 bad=0
=== FACE shard 20:25 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [20:25) ok=5 bad=0
=== FACE shard 25:30 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [25:30) ok=5 bad=0
=== FACE shard 30:35 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [30:35) ok=5 bad=0
=== FACE shard 35:40 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [35:40) ok=5 bad=0
=== FACE shard 40:45 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [40:45) ok=5 bad=0
=== FACE shard 45:50 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [45:50) ok=5 bad=0
=== FACE shard 50:55 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [50:55) ok=5 bad=0
=== FACE shard 55:60 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [55:60) ok=5 bad=0
=== FACE shard 60:65 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [60:65) ok=5 bad=0
=== FACE shard 65:70 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [65:70) ok=5 bad=0
=== FACE shard 70:75 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [70:75) ok=5 bad=0
=== FACE shard 75:80 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [75:80) ok=5 bad=0
=== FACE shard 80:85 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [80:85) ok=5 bad=0
=== FACE shard 85:90 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [85:90) ok=5 bad=0
=== FACE shard 90:95 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [90:95) ok=5 bad=0
=== FACE shard 95:100 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [95:100) ok=5 bad=0
=== FACE shard 100:105 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [100:105) ok=5 bad=0
=== FACE shard 105:110 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [105:110) ok=5 bad=0
=== FACE shard 110:115 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [110:115) ok=5 bad=0
=== FACE shard 115:120 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [115:120) ok=5 bad=0
=== FACE shard 120:125 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [120:125) ok=5 bad=0
=== FACE shard 125:130 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [125:130) ok=5 bad=0
=== FACE shard 130:135 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [130:135) ok=5 bad=0
=== FACE shard 135:140 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [135:140) ok=5 bad=0
=== FACE shard 140:145 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [140:145) ok=5 bad=0
=== FACE shard 145:150 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [145:150) ok=5 bad=0
=== FACE shard 150:155 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [150:155) ok=5 bad=0
=== FACE shard 155:160 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [155:160) ok=5 bad=0
=== FACE shard 160:165 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [160:165) ok=5 bad=0
=== FACE shard 165:170 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [165:170) ok=5 bad=0
=== FACE shard 170:175 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [170:175) ok=5 bad=0
=== FACE shard 175:180 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [175:180) ok=5 bad=0
=== FACE shard 180:185 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [180:185) ok=5 bad=0
=== FACE shard 185:190 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [185:190) ok=5 bad=0
=== FACE shard 190:195 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [190:195) ok=5 bad=0
=== FACE shard 195:200 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [195:200) ok=5 bad=0
=== FACE shard 200:205 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [200:205) ok=5 bad=0
=== FACE shard 205:210 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [205:210) ok=5 bad=0
=== FACE shard 210:215 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [210:215) ok=5 bad=0
=== FACE shard 215:220 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [215:220) ok=5 bad=0
=== FACE shard 220:225 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [220:225) ok=5 bad=0
=== FACE shard 225:230 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [225:230) ok=5 bad=0
=== FACE shard 230:235 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [230:235) ok=5 bad=0
=== FACE shard 235:240 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [235:240) ok=5 bad=0
=== FACE shard 240:245 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [240:245) ok=5 bad=0
=== FACE shard 245:250 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [245:250) ok=5 bad=0
=== FACE shard 250:255 (device=cuda) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= True skel= False

DONE shard [250:255) ok=5 bad=0

  0%|          | 0/5 [00:00<?, ?it/s]
  0%|          | 0.00/6.25M [00:00<?, ?B/s]
100%|██████████| 6.25M/6.25M [00:00<00:00, 53.4MB/s]
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768473915.285799   39579 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768473915.292454   39579 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768473915.312160   39579 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768473915.312196   39579 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768473915.312198   39579 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768473915.312200   39579 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:07<00:00, 13.54s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768473985.350419   40541 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768473985.357151   40541 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768473985.375657   40541 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768473985.375695   40541 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768473985.375698   40541 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768473985.375700   40541 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 20%|██        | 1/5 [00:26<01:45, 26.33s/it][h264 @ 0x2a5b3fc0] mmco: unref short failure
[h264 @ 0x2a5b3fc0] mmco: unref short failure
100%|██████████| 5/5 [00:58<00:00, 11.70s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474048.359705   41422 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474048.366370   41422 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474048.384475   41422 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474048.384514   41422 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474048.384516   41422 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474048.384518   41422 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:05<00:00, 13.10s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474118.763695   42407 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474118.770457   42407 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474118.790956   42407 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474118.790997   42407 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474118.790999   42407 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474118.791002   42407 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 20%|██        | 1/5 [00:21<01:26, 21.73s/it][h264 @ 0x475d88c0] mmco: unref short failure
 80%|████████  | 4/5 [00:56<00:11, 11.67s/it][h264 @ 0x476089c0] mmco: unref short failure
100%|██████████| 5/5 [01:06<00:00, 13.20s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474188.545485   43432 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474188.552023   43432 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474188.570774   43432 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474188.570808   43432 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474188.570810   43432 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474188.570812   43432 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[h264 @ 0xba5c940] mmco: unref short failure
[h264 @ 0xba5c940] mmco: unref short failure
 80%|████████  | 4/5 [00:57<00:10, 10.99s/it][h264 @ 0xbb9be40] mmco: unref short failure
100%|██████████| 5/5 [01:04<00:00, 12.81s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474257.610882   44443 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474257.617639   44443 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474257.637021   44443 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474257.637054   44443 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474257.637056   44443 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474257.637058   44443 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 80%|████████  | 4/5 [01:04<00:14, 14.52s/it][h264 @ 0x11991340] mmco: unref short failure
100%|██████████| 5/5 [01:14<00:00, 14.92s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474336.685232   45577 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474336.693091   45577 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474336.713462   45577 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474336.713499   45577 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474336.713502   45577 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474336.713504   45577 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [00:59<00:00, 11.92s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474400.802569   46506 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474400.809216   46506 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474400.826923   46506 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474400.826947   46506 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474400.826949   46506 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474400.826951   46506 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 40%|████      | 2/5 [00:32<00:47, 15.90s/it][h264 @ 0x3aaf5c40] mmco: unref short failure
100%|██████████| 5/5 [00:50<00:00, 10.10s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474455.274013   47285 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474455.280629   47285 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474455.298685   47285 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474455.298721   47285 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474455.298724   47285 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474455.298726   47285 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 20%|██        | 1/5 [00:18<01:12, 18.01s/it][h264 @ 0x14c1b9c0] mmco: unref short failure
100%|██████████| 5/5 [01:06<00:00, 13.33s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474526.692947   48331 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474526.699467   48331 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474526.717131   48331 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474526.717163   48331 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474526.717165   48331 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474526.717167   48331 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:52<00:00, 22.59s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474643.526777   50302 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474643.533475   50302 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474643.551202   50302 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474643.551229   50302 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474643.551231   50302 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474643.551233   50302 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[h264 @ 0x9e3d1c0] mmco: unref short failure
[h264 @ 0x9e3d1c0] mmco: unref short failure
100%|██████████| 5/5 [01:28<00:00, 17.70s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474736.833179   51710 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474736.839827   51710 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474736.859132   51710 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474736.859164   51710 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474736.859167   51710 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474736.859169   51710 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:29<00:00, 17.88s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474830.783680   53123 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474830.790343   53123 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474830.808485   53123 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474830.808525   53123 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474830.808528   53123 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474830.808530   53123 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 20%|██        | 1/5 [00:22<01:31, 22.83s/it][h264 @ 0x3dd10580] mmco: unref short failure
100%|██████████| 5/5 [00:52<00:00, 10.50s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474887.182891   53914 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474887.189505   53914 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474887.209186   53914 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474887.209217   53914 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474887.209220   53914 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474887.209222   53914 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:22<00:00, 16.58s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768474974.360622   55222 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768474974.367192   55222 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768474974.384963   55222 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474974.384997   55222 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474974.385000   55222 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768474974.385002   55222 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:56<00:00, 23.30s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1768475095.759081   57069 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768475095.765608   57069 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [ ]:
%%bash
CHUNK=32
SHARD=10
DEVICE=cpu
CSV=/content/phase1_all_with_split.csv
FEAT_DIR=/content/drive/MyDrive/miga_features_cache_agcn

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase1_all_with_split.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD))
  if [ $END -gt $TOTAL ]; then END=$TOTAL; fi

  echo "=== SKEL shard $START:$END ==="
  PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 python -u /content/src/cache_features_cli.py \
    --csv $CSV --phase 1 --feat_dir $FEAT_DIR \
    --chunk $CHUNK --start $START --end $END --device $DEVICE \
    --do_skel

  START=$END
done

=== SKEL shard 0:10 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [0:10) ok=10 bad=0
=== SKEL shard 10:20 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [10:20) ok=10 bad=0
=== SKEL shard 20:30 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [20:30) ok=10 bad=0
=== SKEL shard 30:40 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [30:40) ok=10 bad=0
=== SKEL shard 40:50 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [40:50) ok=10 bad=0
=== SKEL shard 50:60 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [50:60) ok=10 bad=0
=== SKEL shard 60:70 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [60:70) ok=10 bad=0
=== SKEL shard 70:80 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [70:80) ok=10 bad=0
=== SKEL shard 80:90 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [80:90) ok=10 bad=0
=== SKEL shard 90:100 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True
 ERROR
row: 6 video_id: 319 split: train
skeleton_path: nan

DONE shard [90:100) ok=9 bad=1
=== SKEL shard 100:110 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True
 ERROR
row: 2 video_id: 348 split: train
skeleton_path: nan

DONE shard [100:110) ok=9 bad=1
=== SKEL shard 110:120 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [110:120) ok=10 bad=0
=== SKEL shard 120:130 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [120:130) ok=10 bad=0
=== SKEL shard 130:140 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [130:140) ok=10 bad=0
=== SKEL shard 140:150 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [140:150) ok=10 bad=0
=== SKEL shard 150:160 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True
 ERROR
row: 2 video_id: 347 split: train
skeleton_path: nan

DONE shard [150:160) ok=9 bad=1
=== SKEL shard 160:170 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True
 ERROR
row: 7 video_id: 218 split: train
skeleton_path: nan

DONE shard [160:170) ok=9 bad=1
=== SKEL shard 170:180 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [170:180) ok=10 bad=0
=== SKEL shard 180:190 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [180:190) ok=10 bad=0
=== SKEL shard 190:200 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [190:200) ok=10 bad=0
=== SKEL shard 200:210 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [200:210) ok=10 bad=0
=== SKEL shard 210:220 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [210:220) ok=10 bad=0
=== SKEL shard 220:230 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [220:230) ok=10 bad=0
=== SKEL shard 230:240 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [230:240) ok=10 bad=0
=== SKEL shard 240:250 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [240:250) ok=10 bad=0
=== SKEL shard 250:255 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn
MODES: ctx= False face= False skel= True

DONE shard [250:255) ok=5 bad=0

100%|██████████| 10/10 [00:01<00:00,  6.28it/s]
100%|██████████| 10/10 [00:01<00:00,  6.17it/s]
100%|██████████| 10/10 [00:01<00:00,  5.46it/s]
100%|██████████| 10/10 [00:01<00:00,  7.83it/s]
100%|██████████| 10/10 [00:02<00:00,  4.56it/s]
100%|██████████| 10/10 [00:02<00:00,  4.18it/s]
100%|██████████| 10/10 [00:01<00:00,  5.47it/s]
100%|██████████| 10/10 [00:02<00:00,  4.01it/s]
100%|██████████| 10/10 [00:01<00:00,  5.81it/s]
 60%|██████    | 6/10 [00:00<00:00,  7.22it/s]Traceback (most recent call last):
  File "/content/src/cache_features_cli.py", line 46, in main
    build_and_cache_one(
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/content/src/feature_extract.py", line 442, in build_and_cache_one
    if spath is None or (not os.path.exists(spath)):
                             ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not float
100%|██████████| 10/10 [00:01<00:00,  9.69it/s]
 20%|██        | 2/10 [00:00<00:02,  2.89it/s]Traceback (most recent call last):
  File "/content/src/cache_features_cli.py", line 46, in main
    build_and_cache_one(
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/content/src/feature_extract.py", line 442, in build_and_cache_one
    if spath is None or (not os.path.exists(spath)):
                             ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not float
100%|██████████| 10/10 [00:01<00:00,  5.37it/s]
100%|██████████| 10/10 [00:02<00:00,  4.96it/s]
100%|██████████| 10/10 [00:01<00:00,  5.11it/s]
100%|██████████| 10/10 [00:02<00:00,  4.00it/s]
100%|██████████| 10/10 [00:01<00:00,  5.82it/s]
 20%|██        | 2/10 [00:00<00:03,  2.41it/s]Traceback (most recent call last):
  File "/content/src/cache_features_cli.py", line 46, in main
    build_and_cache_one(
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/content/src/feature_extract.py", line 442, in build_and_cache_one
    if spath is None or (not os.path.exists(spath)):
                             ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not float
100%|██████████| 10/10 [00:02<00:00,  4.93it/s]
 60%|██████    | 6/10 [00:01<00:00,  5.23it/s]Traceback (most recent call last):
  File "/content/src/cache_features_cli.py", line 46, in main
    build_and_cache_one(
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/content/src/feature_extract.py", line 442, in build_and_cache_one
    if spath is None or (not os.path.exists(spath)):
                             ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not float
100%|██████████| 10/10 [00:01<00:00,  5.94it/s]
100%|██████████| 10/10 [00:02<00:00,  4.72it/s]
100%|██████████| 10/10 [00:01<00:00,  5.64it/s]
100%|██████████| 10/10 [00:01<00:00,  5.39it/s]
100%|██████████| 10/10 [00:02<00:00,  4.15it/s]
100%|██████████| 10/10 [00:01<00:00,  5.23it/s]
100%|██████████| 10/10 [00:01<00:00,  6.51it/s]
100%|██████████| 10/10 [00:01<00:00,  5.74it/s]
100%|██████████| 10/10 [00:02<00:00,  4.62it/s]
100%|██████████| 5/5 [00:00<00:00,  5.99it/s]

In [ ]:
import torch, os
p = "/content/drive/MyDrive/miga_features_cache/be6f549156a8_face.pt"
x = torch.load(p, map_location="cpu")
print("file:", os.path.basename(p))
print("shape:", x.shape)
print("D_FACE =", x.shape[1])

file: be6f549156a8_face.pt
shape: torch.Size([201, 1280])
D_FACE = 1280

In [ ]:
%%writefile /content/src/model.py
import torch
import torch.nn as nn
import torch.nn.functional as F


class AttnPool(nn.Module):
    def __init__(self, d):
        super().__init__()
        self.scorer = nn.Sequential(
            nn.Linear(d, d // 2),
            nn.GELU(),
            nn.Linear(d // 2, 1)
        )

    def forward(self, x, mask):
        score = self.scorer(x).squeeze(-1)
        score = score.float()

        score = score.masked_fill(~mask, -1e4)

        w = torch.softmax(score, dim=1).unsqueeze(-1)
        w = w.to(dtype=x.dtype)
        return (x * w).sum(dim=1)



class TriStreamModel(nn.Module):
    def __init__(
        self,
        d_ctx_in=512,
        d_face_in=1280,
        d_skel_in=512,
        d=512,
        n_layers=4,
        n_heads=4,
        dropout=0.3,
    ):
        super().__init__()


        self.ctx_in  = nn.Sequential(nn.Linear(d_ctx_in, d), nn.Dropout(dropout))
        self.face_in = nn.Sequential(nn.Linear(d_face_in, d), nn.Dropout(dropout))
        self.skel_in = nn.Sequential(nn.Linear(d_skel_in, d), nn.Dropout(dropout))

        enc = nn.TransformerEncoderLayer(
            d_model=d,
            nhead=n_heads,
            dim_feedforward=4 * d,
            dropout=dropout,
            batch_first=True,
            activation="gelu"
        )

        self.ctx_enc  = nn.TransformerEncoder(enc, num_layers=n_layers)
        self.face_enc = nn.TransformerEncoder(enc, num_layers=n_layers)
        self.skel_enc = nn.TransformerEncoder(enc, num_layers=n_layers)

        self.ctx_pool  = AttnPool(d)
        self.face_pool = AttnPool(d)
        self.skel_pool = AttnPool(d)

        self.head = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(3 * d, d),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(d, 1)
        )

    def forward(self, ctx, face, skel, time_mask, face_mask, skel_mask):

        pad_ignore = ~time_mask

        x_ctx  = self.ctx_in(ctx)
        x_face = self.face_in(face)
        x_skel = self.skel_in(skel)

        x_ctx  = self.ctx_enc(x_ctx,   src_key_padding_mask=pad_ignore)
        x_face = self.face_enc(x_face, src_key_padding_mask=pad_ignore)
        x_skel = self.skel_enc(x_skel, src_key_padding_mask=pad_ignore)

        ctx_vec  = self.ctx_pool(x_ctx,  time_mask)
        face_vec = self.face_pool(x_face, time_mask & face_mask)
        skel_vec = self.skel_pool(x_skel, time_mask & skel_mask)

        z = torch.cat([ctx_vec, face_vec, skel_vec], dim=-1)
        return self.head(z).squeeze(-1)

Overwriting /content/src/model.py

In [ ]:
%%writefile /content/src/ds.py
import os
import torch
from torch.utils.data import Dataset

from .feature_extract import cache_paths


_CTX_PROJ = None

def _ctx_to_512(x: torch.Tensor) -> torch.Tensor:
    """
    x: (T, D) on CPU
    returns (T, 512) on CPU
    """
    global _CTX_PROJ
    if x.ndim != 2:
        raise ValueError(f"ctx must be (T,D), got {tuple(x.shape)}")

    T, D = x.shape
    if D == 512:
        return x
    if D == 768:

        if _CTX_PROJ is None:
            _CTX_PROJ = torch.nn.Linear(768, 512, bias=False)
            torch.nn.init.orthogonal_(_CTX_PROJ.weight)
            _CTX_PROJ.eval()
        with torch.no_grad():
            return _CTX_PROJ(x.float()).to(dtype=torch.float32)
    raise ValueError(f"Unexpected ctx dim: {D} (expected 512 or 768)")

def _ensure_float32(x: torch.Tensor) -> torch.Tensor:
    return x.float() if x.dtype != torch.float32 else x


class Track3CachedDataset(Dataset):
    def __init__(self, df, feat_dir: str, phase: int = 1, has_label: bool = True):
        self.df = df.reset_index(drop=True)
        self.feat_dir = feat_dir
        self.phase = phase
        self.has_label = has_label

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        vid = int(row["video_id"])
        split = row.get("split", "test")

        ps = cache_paths(self.feat_dir, vid, split, self.phase)

        ctx  = torch.load(ps["ctx"],  map_location="cpu")
        face = torch.load(ps["face"], map_location="cpu")
        skel = torch.load(ps["skel"], map_location="cpu")

        fmask = torch.load(ps["fmask"], map_location="cpu")
        smask = torch.load(ps["smask"], map_location="cpu")

        ctx  = _ensure_float32(ctx)
        face = _ensure_float32(face)
        skel = _ensure_float32(skel)

        ctx = _ctx_to_512(ctx)

        T = min(ctx.shape[0], face.shape[0], skel.shape[0])
        ctx, face, skel = ctx[:T], face[:T], skel[:T]
        fmask, smask = fmask[:T].bool(), smask[:T].bool()

        out = {
            "id": vid,
            "ctx": ctx,
            "face": face,
            "skel": skel,
            "time_mask": torch.ones((T,), dtype=torch.bool),
            "face_mask": fmask,
            "skel_mask": smask,
        }
        if self.has_label:
            out["y"] = torch.tensor(float(row["label"]), dtype=torch.float32)
        return out



def pad_seq(list_TD, pad_value=0.0):
    T = max(x.shape[0] for x in list_TD)
    D = list_TD[0].shape[1]
    out = torch.full((len(list_TD), T, D), pad_value, dtype=torch.float32)
    tm  = torch.zeros((len(list_TD), T), dtype=torch.bool)
    for i, x in enumerate(list_TD):
        out[i, :x.shape[0]] = x.float()
        tm[i, :x.shape[0]] = True
    return out, tm


def collate_fn(batch):
    ctx, time_mask = pad_seq([b["ctx"] for b in batch])
    face, _        = pad_seq([b["face"] for b in batch])
    skel, _        = pad_seq([b["skel"] for b in batch])

    face_mask = torch.zeros_like(time_mask)
    skel_mask = torch.zeros_like(time_mask)

    for i, b in enumerate(batch):
        face_mask[i, :len(b["face_mask"])] = b["face_mask"]
        skel_mask[i, :len(b["skel_mask"])] = b["skel_mask"]

    out = {
        "id": [b["id"] for b in batch],
        "ctx": ctx,
        "face": face,
        "skel": skel,
        "time_mask": time_mask,
        "face_mask": face_mask,
        "skel_mask": skel_mask,
    }
    if "y" in batch[0]:
        out["y"] = torch.stack([b["y"] for b in batch])
    return out

Overwriting /content/src/ds.py

In [ ]:
import os, pandas as pd
from src.feature_extract import cache_paths

ROOT = "/content/miga_data"
FEAT_DIR = "/content/drive/MyDrive/miga_features_cache_agcn"

train_csv = f"{ROOT}/imigue_rgb_phase1/train_label.csv"
val_csv   = f"{ROOT}/imigue_rgb_phase1/validation_label.csv"

train_df = pd.read_csv(train_csv); train_df["split"]="train"
val_df   = pd.read_csv(val_csv);   val_df["split"]="val"

need = ["ctx","face","fmask","skel","smask"]

def has_cache(r):
    ps = cache_paths(FEAT_DIR, int(r["video_id"]), r["split"], 1)
    return all(os.path.exists(ps[k]) for k in need)

train_ok = train_df[train_df.apply(has_cache, axis=1)].reset_index(drop=True)
val_ok   = val_df[val_df.apply(has_cache, axis=1)].reset_index(drop=True)

print("train_ok:", len(train_ok), "/", len(train_df))
print("val_ok:", len(val_ok), "/", len(val_df))
print("val counts:", val_ok["label"].value_counts().to_dict())

train_ok: 241 / 245
val_ok: 10 / 10
val counts: {1: 10}

In [ ]:
import numpy as np, torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import DataLoader
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold

from src.ds import Track3CachedDataset, collate_fn
from src.model import TriStreamModel

device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

D_FACE = 1280

sample_ds = Track3CachedDataset(train_ok.iloc[:1], feat_dir=FEAT_DIR, phase=1, has_label=True)
sample = sample_ds[0]
d_skel_in = sample["skel"].shape[1]
print("d_skel_in:", d_skel_in)

class FocalLoss(nn.Module):
    def __init__(self, gamma=1.0, pos_weight=None):
        super().__init__()
        self.gamma = gamma
        self.pos_weight = pos_weight
    def forward(self, logits, targets):
        bce = F.binary_cross_entropy_with_logits(logits, targets, reduction="none", pos_weight=self.pos_weight)
        p = torch.sigmoid(logits)
        pt = torch.where(targets == 1, p, 1 - p).clamp(1e-6, 1-1e-6)
        return (((1 - pt) ** self.gamma) * bce).mean()

def eval_auc(model, loader):
    model.eval()
    ys, ps = [], []
    with torch.no_grad():
        for b in loader:
            logit = model(
                b["ctx"].to(device, non_blocking=True),
                b["face"].to(device, non_blocking=True),
                b["skel"].to(device, non_blocking=True),
                b["time_mask"].to(device, non_blocking=True),
                b["face_mask"].to(device, non_blocking=True),
                b["skel_mask"].to(device, non_blocking=True),
            )
            prob = torch.sigmoid(logit).detach().cpu().numpy()
            ys.append(b["y"].numpy())
            ps.append(prob)
    ys = np.concatenate(ys); ps = np.concatenate(ps)
    if len(np.unique(ys)) < 2:
        return float("nan")
    return roc_auc_score(ys, ps)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
y = train_ok["label"].values

best_auc = -1
best_state = None

for fold, (tr_idx, va_idx) in enumerate(skf.split(train_ok, y), 1):
    tr_df = train_ok.iloc[tr_idx].reset_index(drop=True)
    va_df = train_ok.iloc[va_idx].reset_index(drop=True)

    tr_ds = Track3CachedDataset(tr_df, feat_dir=FEAT_DIR, phase=1, has_label=True)
    va_ds = Track3CachedDataset(va_df, feat_dir=FEAT_DIR, phase=1, has_label=True)

    tr_loader = DataLoader(tr_ds, batch_size=4, shuffle=True, num_workers=0, collate_fn=collate_fn, pin_memory=True)
    va_loader = DataLoader(va_ds, batch_size=4, shuffle=False, num_workers=0, collate_fn=collate_fn, pin_memory=True)

    pos = (tr_df["label"] == 1).sum()
    neg = (tr_df["label"] == 0).sum()
    pos_weight = torch.tensor([neg / max(pos, 1)], dtype=torch.float32).to(device)

    model = TriStreamModel(d_ctx_in=512, d_face_in=D_FACE, d_skel_in=d_skel_in,
                          d=512, n_layers=4, n_heads=4, dropout=0.3).to(device)

    crit = FocalLoss(gamma=1.0, pos_weight=pos_weight)
    opt = torch.optim.AdamW(model.parameters(), lr=2e-4, weight_decay=1e-4)

    scaler = torch.cuda.amp.GradScaler(enabled=(device=="cuda"))
    GRAD_ACCUM = 2
    patience = 4
    bad = 0
    fold_best = -1

    for epoch in range(1, 21):
        model.train()
        opt.zero_grad(set_to_none=True)
        losses = []

        for step, b in enumerate(tr_loader, 1):
            with torch.cuda.amp.autocast(enabled=(device=="cuda")):
                logit = model(
                    b["ctx"].to(device, non_blocking=True),
                    b["face"].to(device, non_blocking=True),
                    b["skel"].to(device, non_blocking=True),
                    b["time_mask"].to(device, non_blocking=True),
                    b["face_mask"].to(device, non_blocking=True),
                    b["skel_mask"].to(device, non_blocking=True),
                )
                loss = crit(logit, b["y"].to(device, non_blocking=True)) / GRAD_ACCUM

            scaler.scale(loss).backward()

            if step % GRAD_ACCUM == 0:
                scaler.unscale_(opt)
                nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(opt); scaler.update()
                opt.zero_grad(set_to_none=True)

            losses.append(loss.item() * GRAD_ACCUM)

        auc = eval_auc(model, va_loader)
        print(f"fold {fold} epoch {epoch}: loss={np.mean(losses):.4f} val_auc={auc:.4f}")

        if np.isfinite(auc) and auc > fold_best + 1e-4:
            fold_best = auc
            bad = 0
            if auc > best_auc:
                best_auc = auc
                best_state = {k: v.detach().cpu() for k, v in model.state_dict().items()}
        else:
            bad += 1
            if bad >= patience:
                break

print("Best CV AUC:", best_auc)

if best_state is not None:
    out = "/content/drive/MyDrive/best_tristream_cv_agcn.pt"
    torch.save(best_state, out)
    print("Saved:", out)

device: cuda
d_skel_in: 512

/tmp/ipython-input-3531534122.py:77: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=(device=="cuda"))
/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 1 epoch 1: loss=0.2065 val_auc=0.5789

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 1 epoch 2: loss=0.2100 val_auc=0.3014

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 1 epoch 3: loss=0.2161 val_auc=0.6675

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 1 epoch 4: loss=0.1627 val_auc=0.3660

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 1 epoch 5: loss=0.1677 val_auc=0.6148

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 1 epoch 6: loss=0.1736 val_auc=0.6364

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 1 epoch 7: loss=0.1554 val_auc=0.6411

/tmp/ipython-input-3531534122.py:77: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=(device=="cuda"))
/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 2 epoch 1: loss=0.2011 val_auc=0.5263

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 2 epoch 2: loss=0.1640 val_auc=0.5474

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 2 epoch 3: loss=0.2170 val_auc=0.5447

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 2 epoch 4: loss=0.1720 val_auc=0.5395

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 2 epoch 5: loss=0.1616 val_auc=0.5211

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 2 epoch 6: loss=0.2068 val_auc=0.4842

/tmp/ipython-input-3531534122.py:77: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=(device=="cuda"))
/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 3 epoch 1: loss=0.2318 val_auc=0.5921

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 3 epoch 2: loss=0.1720 val_auc=0.3737

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 3 epoch 3: loss=0.1695 val_auc=0.3711

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 3 epoch 4: loss=0.1720 val_auc=0.6947

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 3 epoch 5: loss=0.1853 val_auc=0.6763

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 3 epoch 6: loss=0.1675 val_auc=0.6737

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 3 epoch 7: loss=0.1593 val_auc=0.6816

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 3 epoch 8: loss=0.1580 val_auc=0.6711

/tmp/ipython-input-3531534122.py:77: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=(device=="cuda"))
/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 4 epoch 1: loss=0.1952 val_auc=0.4289

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 4 epoch 2: loss=0.1753 val_auc=0.4711

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 4 epoch 3: loss=0.1990 val_auc=0.6184

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 4 epoch 4: loss=0.1800 val_auc=0.3289

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 4 epoch 5: loss=0.1653 val_auc=0.4658

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 4 epoch 6: loss=0.1943 val_auc=0.3632

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 4 epoch 7: loss=0.1580 val_auc=0.4000

/tmp/ipython-input-3531534122.py:77: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=(device=="cuda"))
/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 5 epoch 1: loss=0.1953 val_auc=0.6536

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 5 epoch 2: loss=0.1831 val_auc=0.5725

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 5 epoch 3: loss=0.1978 val_auc=0.6462

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 5 epoch 4: loss=0.1713 val_auc=0.6708

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 5 epoch 5: loss=0.1576 val_auc=0.6364

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 5 epoch 6: loss=0.1523 val_auc=0.6462

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 5 epoch 7: loss=0.1556 val_auc=0.6486

/tmp/ipython-input-3531534122.py:89: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=(device=="cuda")):

fold 5 epoch 8: loss=0.1609 val_auc=0.6609
Best CV AUC: 0.6947368421052631
Saved: /content/drive/MyDrive/best_tristream_cv_agcn.pt

In [ ]:
ROOT = "/content/miga_data"
FEAT_DIR_P1 = "/content/drive/MyDrive/miga_features_cache_agcn"
FEAT_DIR_P2 = "/content/drive/MyDrive/miga_features_cache_agcn_p2"
CKPT_PATH = "/content/drive/MyDrive/best_tristream_cv.pt"

In [ ]:
import os, glob
import pandas as pd

ROOT = "/content/miga_data"

RGB_PHASE2 = f"{ROOT}/imigue_rgb_phase2"
SK_P2_TEST = f"{ROOT}/imigue_data_phase2/imigue_skeleton_test"
def vid4(x): return f"{int(x):04d}"

def resolve_video_path_phase2(video_id):
    v = vid4(video_id)
    p = os.path.join(RGB_PHASE2, v, f"{v}.mp4")
    if os.path.exists(p):
        return p
    hits = glob.glob(os.path.join(RGB_PHASE2, "**", f"{v}.mp4"), recursive=True)
    return hits[0] if hits else None

def resolve_skeleton_path_phase2(video_id, prefer_hand=True):
    v = vid4(video_id)
    p_hand  = os.path.join(SK_P2_TEST, v, f"{v}_light_hand.csv")
    p_light = os.path.join(SK_P2_TEST, v, f"{v}_light.csv")
    if prefer_hand and os.path.exists(p_hand): return p_hand
    if os.path.exists(p_light): return p_light
    if os.path.exists(p_hand):  return p_hand
    return None

ids = sorted([int(os.path.basename(p)) for p in glob.glob(os.path.join(SK_P2_TEST, "[0-9][0-9][0-9][0-9]"))])

rows = []
miss_v, miss_s = 0, 0
for vid in ids:
    vpath = resolve_video_path_phase2(vid)
    spath = resolve_skeleton_path_phase2(vid)
    if vpath is None: miss_v += 1
    if spath is None: miss_s += 1
    rows.append({
        "video_id": vid,
        "split": "test",
        "video_path": vpath,
        "skeleton_path": spath
    })

phase2_df = pd.DataFrame(rows).sort_values("video_id").reset_index(drop=True)
print("Phase2 rows:", len(phase2_df), "missing video:", miss_v, "missing skeleton:", miss_s)

PHASE2_ALL = "/content/phase2_all_with_paths.csv"
phase2_df.to_csv(PHASE2_ALL, index=False)
print("Saved:", PHASE2_ALL)
phase2_df.head()

Phase2 rows: 104 missing video: 0 missing skeleton: 0
Saved: /content/phase2_all_with_paths.csv

,video_id,split,video_path,skeleton_path
0,54,test,/content/miga_data/imigue_rgb_phase2/0054/0054...,/content/miga_data/imigue_data_phase2/imigue_s...
1,67,test,/content/miga_data/imigue_rgb_phase2/0067/0067...,/content/miga_data/imigue_data_phase2/imigue_s...
2,69,test,/content/miga_data/imigue_rgb_phase2/0069/0069...,/content/miga_data/imigue_data_phase2/imigue_s...
3,70,test,/content/miga_data/imigue_rgb_phase2/0070/0070...,/content/miga_data/imigue_data_phase2/imigue_s...
4,71,test,/content/miga_data/imigue_rgb_phase2/0071/0071...,/content/miga_data/imigue_data_phase2/imigue_s...

In [ ]:
%%bash
CHUNK=32
SHARD=10
DEVICE=cuda

TOTAL=$(python - << 'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase2_all_with_paths.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD))
  if [ $END -gt $TOTAL ]; then END=$TOTAL; fi

  echo "=== CTX shard $START:$END ==="
  PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 python -u /content/src/cache_features_cli.py \
    --csv /content/phase2_all_with_paths.csv \
    --phase 2 \
    --feat_dir /content/drive/MyDrive/miga_features_cache_agcn_p2 \
    --chunk $CHUNK \
    --start $START --end $END \
    --device $DEVICE \
    --do_ctx

  START=$END
done

=== CTX shard 0:10 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= True face= False skel= False

DONE shard [0:10) ok=10 bad=0
=== CTX shard 10:20 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= True face= False skel= False

DONE shard [10:20) ok=10 bad=0
=== CTX shard 20:30 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= True face= False skel= False

DONE shard [20:30) ok=10 bad=0
=== CTX shard 30:40 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= True face= False skel= False

DONE shard [30:40) ok=10 bad=0
=== CTX shard 40:50 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= True face= False skel= False

DONE shard [40:50) ok=10 bad=0
=== CTX shard 50:60 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= True face= False skel= False

DONE shard [50:60) ok=10 bad=0
=== CTX shard 60:70 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= True face= False skel= False

DONE shard [60:70) ok=10 bad=0
=== CTX shard 70:80 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= True face= False skel= False

DONE shard [70:80) ok=10 bad=0
=== CTX shard 80:90 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= True face= False skel= False

DONE shard [80:90) ok=10 bad=0
=== CTX shard 90:100 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= True face= False skel= False

DONE shard [90:100) ok=10 bad=0
=== CTX shard 100:104 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= True face= False skel= False

DONE shard [100:104) ok=4 bad=0

100%|██████████| 10/10 [00:00<00:00, 2030.55it/s]
100%|██████████| 10/10 [00:00<00:00, 2040.63it/s]
100%|██████████| 10/10 [00:00<00:00, 1340.33it/s]
100%|██████████| 10/10 [00:00<00:00, 2176.71it/s]
100%|██████████| 10/10 [00:00<00:00, 1390.73it/s]
100%|██████████| 10/10 [00:00<00:00, 1950.93it/s]
100%|██████████| 10/10 [00:00<00:00, 2093.70it/s]
100%|██████████| 10/10 [00:00<00:00, 2157.01it/s]
100%|██████████| 10/10 [00:00<00:00, 2160.23it/s]
100%|██████████| 10/10 [00:00<00:00, 2090.98it/s]
100%|██████████| 4/4 [00:00<00:00, 1696.04it/s]

In [ ]:
%%bash
CHUNK=32
SHARD=25
DEVICE=cuda

TOTAL=$(python - << 'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase2_all_with_paths.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD))
  if [ $END -gt $TOTAL ]; then END=$TOTAL; fi

  echo "=== FACE shard $START:$END ==="
  PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 python -u /content/src/cache_features_cli.py \
    --csv /content/phase2_all_with_paths.csv \
    --phase 2 \
    --feat_dir /content/drive/MyDrive/miga_features_cache_agcn_p2 \
    --chunk $CHUNK \
    --start $START --end $END \
    --device $DEVICE \
    --do_face

  START=$END
done

=== FACE shard 0:25 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= False face= True skel= False

DONE shard [0:25) ok=25 bad=0
=== FACE shard 25:50 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= False face= True skel= False

DONE shard [25:50) ok=25 bad=0
=== FACE shard 50:75 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= False face= True skel= False

DONE shard [50:75) ok=25 bad=0
=== FACE shard 75:100 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= False face= True skel= False

DONE shard [75:100) ok=25 bad=0
=== FACE shard 100:104 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= False face= True skel= False

DONE shard [100:104) ok=4 bad=0

100%|██████████| 25/25 [00:00<00:00, 2165.36it/s]
100%|██████████| 25/25 [00:00<00:00, 2429.90it/s]
100%|██████████| 25/25 [00:00<00:00, 2491.45it/s]
100%|██████████| 25/25 [00:00<00:00, 2348.12it/s]
100%|██████████| 4/4 [00:00<00:00, 1633.14it/s]

In [ ]:
%%bash
CHUNK=32
SHARD=25
DEVICE=cuda

TOTAL=$(python - << 'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase2_all_with_paths.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD))
  if [ $END -gt $TOTAL ]; then END=$TOTAL; fi

  echo "=== SKEL shard $START:$END ==="
  PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 python -u /content/src/cache_features_cli.py \
    --csv /content/phase2_all_with_paths.csv \
    --phase 2 \
    --feat_dir /content/drive/MyDrive/miga_features_cache_agcn_p2 \
    --chunk $CHUNK \
    --start $START --end $END \
    --device $DEVICE \
    --do_skel

  START=$END
done

=== SKEL shard 0:25 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= False face= False skel= True

DONE shard [0:25) ok=25 bad=0
=== SKEL shard 25:50 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= False face= False skel= True

DONE shard [25:50) ok=25 bad=0
=== SKEL shard 50:75 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= False face= False skel= True

DONE shard [50:75) ok=25 bad=0
=== SKEL shard 75:100 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= False face= False skel= True

DONE shard [75:100) ok=25 bad=0
=== SKEL shard 100:104 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2
MODES: ctx= False face= False skel= True

DONE shard [100:104) ok=4 bad=0

100%|██████████| 25/25 [00:00<00:00, 2356.62it/s]
100%|██████████| 25/25 [00:00<00:00, 2420.26it/s]
100%|██████████| 25/25 [00:00<00:00, 2472.18it/s]
100%|██████████| 25/25 [00:00<00:00, 1411.81it/s]
100%|██████████| 4/4 [00:00<00:00, 1599.81it/s]

In [ ]:
import torch
from torch.utils.data import DataLoader
import pandas as pd

from src.ds import Track3CachedDataset, collate_fn

DEVICE = "cuda"

FEAT_DIR_P2 = "/content/drive/MyDrive/miga_features_cache_agcn_p2"
PHASE2_ALL = "/content/phase2_all_with_paths.csv"

phase2_df = pd.read_csv(PHASE2_ALL)

print("Columns:", phase2_df.columns.tolist())

test_ds = Track3CachedDataset(
    df=phase2_df,
    feat_dir=FEAT_DIR_P2,
    phase=2
)

test_loader = DataLoader(
    test_ds,
    batch_size=8,
    shuffle=False,
    num_workers=4,
    pin_memory=True,
    collate_fn=collate_fn
)

print("Phase2 samples:", len(test_ds))

Columns: ['video_id', 'split', 'video_path', 'skeleton_path']
Phase2 samples: 104

In [ ]:
from src.model import TriStreamModel

MODEL_PATH = "/content/drive/MyDrive/best_tristream_cv_agcn.pt"

model = TriStreamModel(
    d_ctx_in=512,
    d_face_in=1280,
    d_skel_in=512,
    d=512,
    n_layers=4,
    n_heads=4,
    dropout=0.3
).to(device)

model.load_state_dict(torch.load(MODEL_PATH, map_location=device))

model.eval()

print("Model loaded successfully.")

Model loaded successfully.

In [ ]:
from src.ds import Track3CachedDataset, collate_fn
from torch.utils.data import DataLoader

FEAT_DIR_P2 = "/content/drive/MyDrive/miga_features_cache_agcn_p2"

test_ds = Track3CachedDataset(
    df=phase2_df,
    feat_dir=FEAT_DIR_P2,
    phase=2,
    has_label=False
)

test_loader = DataLoader(
    test_ds,
    batch_size=4,
    shuffle=False,
    num_workers=0,
    collate_fn=collate_fn,
    pin_memory=True
)

print("Test samples:", len(test_ds))

Test samples: 104

In [ ]:
import numpy as np
from tqdm import tqdm

all_ids = []
all_probs = []

with torch.no_grad():
    for b in tqdm(test_loader):
        logit = model(
            b["ctx"].to(device, non_blocking=True),
            b["face"].to(device, non_blocking=True),
            b["skel"].to(device, non_blocking=True),
            b["time_mask"].to(device, non_blocking=True),
            b["face_mask"].to(device, non_blocking=True),
            b["skel_mask"].to(device, non_blocking=True),
        )

        print(f"logit shape: {logit.shape}")

        prob = torch.sigmoid(logit).cpu().numpy().flatten()

        video_ids = np.array(b["id"])

        all_probs.append(prob)
        all_ids.append(video_ids)

all_probs = np.concatenate(all_probs)
all_ids   = np.concatenate(all_ids)

print("Predictions:", all_probs.shape)
print("IDs:", all_ids.shape)

 15%|█▌        | 4/26 [00:00<00:01, 14.77it/s]

logit shape: torch.Size([4])
logit shape: torch.Size([4])
logit shape: torch.Size([4])
logit shape: torch.Size([4])

 23%|██▎       | 6/26 [00:00<00:01, 14.28it/s]

logit shape: torch.Size([4])
logit shape: torch.Size([4])
logit shape: torch.Size([4])

 38%|███▊      | 10/26 [00:00<00:01, 14.48it/s]

logit shape: torch.Size([4])
logit shape: torch.Size([4])
logit shape: torch.Size([4])

 46%|████▌     | 12/26 [00:00<00:00, 14.78it/s]

logit shape: torch.Size([4])
logit shape: torch.Size([4])
logit shape: torch.Size([4])

 62%|██████▏   | 16/26 [00:01<00:00, 14.22it/s]

logit shape: torch.Size([4])
logit shape: torch.Size([4])
logit shape: torch.Size([4])

 69%|██████▉   | 18/26 [00:01<00:00, 13.70it/s]

logit shape: torch.Size([4])
logit shape: torch.Size([4])
logit shape: torch.Size([4])

 85%|████████▍ | 22/26 [00:01<00:00, 13.38it/s]

logit shape: torch.Size([4])
logit shape: torch.Size([4])
logit shape: torch.Size([4])

 92%|█████████▏| 24/26 [00:01<00:00, 13.05it/s]

logit shape: torch.Size([4])
logit shape: torch.Size([4])
logit shape: torch.Size([4])

100%|██████████| 26/26 [00:01<00:00, 13.80it/s]

logit shape: torch.Size([4])
Predictions: (104,)
IDs: (104,)

In [ ]:
submission = pd.DataFrame({
    "video_id": all_ids.astype(int),
    "label": all_probs.astype(float)
}).sort_values("video_id")

submission_path = "/content/drive/MyDrive/submission_phase2.csv"
submission.to_csv(submission_path, index=False)

print(f"Submission saved to: {submission_path}")
submission.head()

Submission saved to: /content/drive/MyDrive/submission_phase2.csv

   video_id     label
0        54  0.669441
1        67  0.670642
2        69  0.668160
3        70  0.669676
4        71  0.669501