In [1]:
!pip -q install --no-cache-dir "numpy==1.26.4" "pandas==2.2.2"
!pip -q install --no-cache-dir "opencv-python-headless==4.10.0.84"
!pip -q install --no-cache-dir decord tqdm einops
!pip -q install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cu121
!pip -q install --no-cache-dir "ultralytics==8.3.0"
!pip -q install --no-cache-dir "emotiefflib[torch]"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.5/17.5 MB 159.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 53.1 MB/s eta 0:00:00

In [2]:
import os
from pathlib import Path

ROOT = "/content/miga_data"
SRC_DIR = "/content/src"

Path(ROOT).mkdir(parents=True, exist_ok=True)
Path(SRC_DIR).mkdir(parents=True, exist_ok=True)

print("ROOT:", ROOT)
print("SRC_DIR:", SRC_DIR)

ROOT: /content/miga_data
SRC_DIR: /content/src

In [3]:
from google.colab import drive
drive.mount("/content/drive")


FEAT_DIR = "/content/drive/MyDrive/miga_features_cache_agcn"

Mounted at /content/drive

In [4]:
DATA_DIR = "/content/miga_data"
!mkdir -p $DATA_DIR

!wget -O $DATA_DIR/imigue_skeleton_phase1.zip https://miga3.a3s.fi/imigue_skeleton_phase1.zip

!wget -O $DATA_DIR/imigue_rgb_phase1.zip https://miga3.a3s.fi/imigue_rgb_phase1.zip

!wget -O $DATA_DIR/imigue_skeleton_phase2.zip https://miga3.a3s.fi/imigue_skeleton_phase2.zip

!wget -O $DATA_DIR/imigue_rgb_phase2.zip https://miga3.a3s.fi/imigue_rgb_phase2.zip

--2026-02-17 06:37:38--  https://miga3.a3s.fi/imigue_skeleton_phase1.zip
Resolving miga3.a3s.fi (miga3.a3s.fi)... 86.50.254.18, 86.50.254.19
Connecting to miga3.a3s.fi (miga3.a3s.fi)|86.50.254.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6270753807 (5.8G) [application/zip]
Saving to: ‘/content/miga_data/imigue_skeleton_phase1.zip’

/content/miga_data/ 100%[===================>]   5.84G  15.2MB/s    in 5m 22s

2026-02-17 06:43:02 (18.6 MB/s) - ‘/content/miga_data/imigue_skeleton_phase1.zip’ saved [6270753807/6270753807]

--2026-02-17 06:43:02--  https://miga3.a3s.fi/imigue_rgb_phase1.zip
Resolving miga3.a3s.fi (miga3.a3s.fi)... 86.50.254.18, 86.50.254.19
Connecting to miga3.a3s.fi (miga3.a3s.fi)|86.50.254.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6512356945 (6.1G) [application/zip]
Saving to: ‘/content/miga_data/imigue_rgb_phase1.zip’

/content/miga_data/ 100%[===================>]   6.06G  20.4MB/s    in 5m 52s

2026-02-17 06:48:56 (17.6 MB/s) - ‘/content/miga_data/imigue_rgb_phase1.zip’ saved [6512356945/6512356945]

--2026-02-17 06:48:56--  https://miga3.a3s.fi/imigue_skeleton_phase2.zip
Resolving miga3.a3s.fi (miga3.a3s.fi)... 86.50.254.18, 86.50.254.19
Connecting to miga3.a3s.fi (miga3.a3s.fi)|86.50.254.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1948103204 (1.8G) [application/zip]
Saving to: ‘/content/miga_data/imigue_skeleton_phase2.zip’

/content/miga_data/ 100%[===================>]   1.81G  17.7MB/s    in 1m 50s

2026-02-17 06:50:47 (16.9 MB/s) - ‘/content/miga_data/imigue_skeleton_phase2.zip’ saved [1948103204/1948103204]

--2026-02-17 06:50:47--  https://miga3.a3s.fi/imigue_rgb_phase2.zip
Resolving miga3.a3s.fi (miga3.a3s.fi)... 86.50.254.18, 86.50.254.19
Connecting to miga3.a3s.fi (miga3.a3s.fi)|86.50.254.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2277100195 (2.1G) [application/zip]
Saving to: ‘/content/miga_data/imigue_rgb_phase2.zip’

/content/miga_data/ 100%[===================>]   2.12G  20.5MB/s    in 2m 3s

2026-02-17 06:52:51 (17.7 MB/s) - ‘/content/miga_data/imigue_rgb_phase2.zip’ saved [2277100195/2277100195]

In [5]:
!unzip -q $DATA_DIR/imigue_skeleton_phase1.zip -d $DATA_DIR
!unzip -q $DATA_DIR/imigue_rgb_phase1.zip -d $DATA_DIR
!unzip -q $DATA_DIR/imigue_skeleton_phase2.zip -d $DATA_DIR
!unzip -q $DATA_DIR/imigue_rgb_phase2.zip -d $DATA_DIR

In [7]:
!rm $DATA_DIR/*.zip

In [6]:
%%writefile /content/src/__init__.py

Writing /content/src/__init__.py

In [8]:
%%writefile /content/src/paths.py
import os, glob

ROOT = "/content/miga_data"

RGB_P1_TRAIN = f"{ROOT}/imigue_rgb_phase1/train_data"
RGB_P1_VAL   = f"{ROOT}/imigue_rgb_phase1/validation_data"
RGB_P2       = f"{ROOT}/imigue_rgb_phase2"

SK_P1_TRAIN  = f"{ROOT}/imigue_data_phase1/datasets/imigue_skeleton_train"
SK_P1_VAL    = f"{ROOT}/imigue_data_phase1/datasets/imigue_skeleton_validate"
SK_P2_TEST   = f"{ROOT}/imigue_data_phase2/imigue_skeleton_test"

def vid4(x): return f"{int(x):04d}"

def resolve_video_path_phase1(video_id, split):
    v = vid4(video_id)
    if split == "train":
        p = os.path.join(RGB_P1_TRAIN, v, f"{v}.mp4")
        return p if os.path.exists(p) else None
    if split == "val":
        p = os.path.join(RGB_P1_VAL, v, f"{v}.mp4")
        return p if os.path.exists(p) else None
    for p in [
        os.path.join(RGB_P1_TRAIN, v, f"{v}.mp4"),
        os.path.join(RGB_P1_VAL, v, f"{v}.mp4"),
    ]:
        if os.path.exists(p): return p
    return None

def resolve_video_path_phase2(video_id):
    v = vid4(video_id)
    p = os.path.join(RGB_P2, v, f"{v}.mp4")
    if os.path.exists(p):
        return p
    hits = glob.glob(os.path.join(RGB_P2, "**", f"{v}.mp4"), recursive=True)
    return hits[0] if hits else None

def resolve_skeleton_path_phase1(video_id, split, prefer_hand=True):
    v = vid4(video_id)
    base = SK_P1_TRAIN if split=="train" else SK_P1_VAL
    p_hand  = os.path.join(base, v, f"{v}_light_hand.csv")
    p_light = os.path.join(base, v, f"{v}_light.csv")
    if prefer_hand and os.path.exists(p_hand): return p_hand
    if os.path.exists(p_light): return p_light
    if os.path.exists(p_hand):  return p_hand
    return None

def resolve_skeleton_path_phase2(video_id, prefer_hand=True):
    v = vid4(video_id)
    p_hand  = os.path.join(SK_P2_TEST, v, f"{v}_light_hand.csv")
    p_light = os.path.join(SK_P2_TEST, v, f"{v}_light.csv")
    if prefer_hand and os.path.exists(p_hand): return p_hand
    if os.path.exists(p_light): return p_light
    if os.path.exists(p_hand):  return p_hand
    return None

Writing /content/src/paths.py

In [9]:
import os
import pandas as pd
import glob, os

ROOT = "/content/miga_data"

train_csv = f"{ROOT}/imigue_rgb_phase1/train_label.csv"
val_csv   = f"{ROOT}/imigue_rgb_phase1/validation_label.csv"

train_df = pd.read_csv(train_csv)
val_df   = pd.read_csv(val_csv)

train_df["split"] = "train"
val_df["split"] = "val"

phase1_all = pd.concat([train_df, val_df], ignore_index=True)

def vid4(x):
    return f"{int(x):04d}"

def video_path(row):
    v = vid4(row["video_id"])
    if row["split"] == "train":
        return f"{ROOT}/imigue_rgb_phase1/train_data/{v}/{v}.mp4"
    else:
        return f"{ROOT}/imigue_rgb_phase1/validation_data/{v}/{v}.mp4"

def skeleton_path(row):
    v = f"{int(row['video_id']):04d}"
    roots = [
        "/content/miga_data/imigue_data_phase1",
        "/content/miga_data",
    ]
    for root in roots:
        hits = glob.glob(f"{root}/**/{v}*_light*.csv", recursive=True)
        if hits:
            return hits[0]
    return None


phase1_all["skeleton_path"] = phase1_all.apply(skeleton_path, axis=1)
phase1_all.to_csv("/content/phase1_all_with_split.csv", index=False)

In [10]:
%%writefile /content/src/agcn.py
import torch
import torch.nn as nn
import torch.nn.functional as F


class AGCNBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv_t = nn.Conv2d(in_channels, out_channels, kernel_size=(9, 1), padding=(4, 0))
        self.conv_v = nn.Conv2d(out_channels, out_channels, kernel_size=(1, 1))
        self.bn = nn.BatchNorm2d(out_channels)

    def forward(self, x):
        x = self.conv_t(x)
        x = self.conv_v(x)
        x = self.bn(x)
        return F.relu(x)


class AGCNModel(nn.Module):

    def __init__(self, in_channels=3, hidden=64, out_dim=512):
        super().__init__()

        self.data_bn = nn.BatchNorm1d(in_channels * 25)

        self.block1 = AGCNBlock(in_channels, hidden)
        self.block2 = AGCNBlock(hidden, hidden * 2)
        self.block3 = AGCNBlock(hidden * 2, hidden * 4)

        self.pool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(hidden * 4, out_dim)

    def forward(self, x):
        B, T, V, C = x.shape

        x = x.permute(0, 3, 1, 2).contiguous()

        x = x.view(B, C * V, T)
        x = self.data_bn(x)
        x = x.view(B, C, V, T).permute(0, 1, 3, 2)

        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)

        x = self.pool(x).view(B, -1)
        x = self.fc(x)
        return x

Writing /content/src/agcn.py

In [11]:
FEAT_DRIVE = "/content/drive/MyDrive/miga_features_cache_agcn"
CSV = "/content/phase1_all_with_split.csv"
PHASE = 1

print("BASE FEAT_DRIVE:", FEAT_DRIVE)

BASE FEAT_DRIVE: /content/drive/MyDrive/miga_features_cache_agcn

In [12]:
%%writefile /content/src/feature_extract.py
import os
import glob
import hashlib
from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

from decord import VideoReader, cpu


MIGA_ROOT = os.environ.get("MIGA_ROOT", "/content/miga_data")

RGB_P1_TRAIN = f"{MIGA_ROOT}/imigue_rgb_phase1/train_data"
RGB_P1_VAL   = f"{MIGA_ROOT}/imigue_rgb_phase1/validation_data"
RGB_P2       = f"{MIGA_ROOT}/imigue_rgb_phase2"

SK_P1_TRAIN  = f"{MIGA_ROOT}/imigue_data_phase1/datasets/imigue_skeleton_train"
SK_P1_VAL    = f"{MIGA_ROOT}/imigue_data_phase1/datasets/imigue_skeleton_validate"
SK_P2_TEST   = f"{MIGA_ROOT}/imigue_data_phase2/imigue_skeleton_test"

# ---------------------------
# EXP SWITCHES (defaults = baseline)
# ---------------------------
CTX_BACKBONE  = os.environ.get("CTX_BACKBONE", "r3d_18")     # r3d_18 | mc3_18 | r2plus1d_18
FACE_SAMPLING = os.environ.get("FACE_SAMPLING", "mid")      # mid | 3frames_avg
FACE_DETECT   = os.environ.get("FACE_DETECT", "yolo")       # yolo | center
SKEL_AGG      = os.environ.get("SKEL_AGG", "mean")          # mean | mean_std | max


def vid4(x: int) -> str:
    return f"{int(x):04d}"


def resolve_video_path_phase1(video_id: int, split: str) -> Optional[str]:
    v = vid4(video_id)
    if split == "train":
        p = os.path.join(RGB_P1_TRAIN, v, f"{v}.mp4")
        return p if os.path.exists(p) else None
    if split == "val":
        p = os.path.join(RGB_P1_VAL, v, f"{v}.mp4")
        return p if os.path.exists(p) else None
    for p in [
        os.path.join(RGB_P1_TRAIN, v, f"{v}.mp4"),
        os.path.join(RGB_P1_VAL, v, f"{v}.mp4"),
    ]:
        if os.path.exists(p):
            return p
    return None


def resolve_video_path_phase2(video_id: int) -> Optional[str]:
    v = vid4(video_id)
    p = os.path.join(RGB_P2, v, f"{v}.mp4")
    if os.path.exists(p):
        return p
    hits = glob.glob(os.path.join(RGB_P2, "**", f"{v}.mp4"), recursive=True)
    return hits[0] if hits else None


def resolve_skeleton_path_phase1(video_id: int, split: str, prefer_hand: bool = True) -> Optional[str]:
    v = vid4(video_id)
    base = SK_P1_TRAIN if split == "train" else SK_P1_VAL
    p_hand  = os.path.join(base, v, f"{v}_light_hand.csv")
    p_light = os.path.join(base, v, f"{v}_light.csv")
    if prefer_hand and os.path.exists(p_hand): return p_hand
    if os.path.exists(p_light): return p_light
    if os.path.exists(p_hand):  return p_hand
    return None


def resolve_skeleton_path_phase2(video_id: int, prefer_hand: bool = True) -> Optional[str]:
    v = vid4(video_id)
    p_hand  = os.path.join(SK_P2_TEST, v, f"{v}_light_hand.csv")
    p_light = os.path.join(SK_P2_TEST, v, f"{v}_light.csv")
    if prefer_hand and os.path.exists(p_hand): return p_hand
    if os.path.exists(p_light): return p_light
    if os.path.exists(p_hand):  return p_hand
    return None


def cache_key(video_id: int, split: str, phase: int) -> str:
    s = f"{int(video_id)}|{split}|{phase}"
    return hashlib.md5(s.encode("utf-8")).hexdigest()[:12]


def cache_paths(feat_dir: str, video_id: int, split: str, phase: int) -> Dict[str, str]:
    key = cache_key(video_id, split, phase)
    d = Path(feat_dir)
    d.mkdir(parents=True, exist_ok=True)
    return {
        "ctx":   str(d / f"{key}_ctx.pt"),
        "face":  str(d / f"{key}_face.pt"),
        "fmask": str(d / f"{key}_facemask.pt"),
        "skel":  str(d / f"{key}_skel.pt"),
        "smask": str(d / f"{key}_skelmask.pt"),
    }


def _vr(path: str) -> VideoReader:
    return VideoReader(path, ctx=cpu(0))


# ---------------------------
# CTX
# ---------------------------
_CTX_MODEL = None

def build_ctx_model(device: str = "cuda"):
    global _CTX_MODEL
    if _CTX_MODEL is not None:
        _CTX_MODEL.to(device).eval()
        return _CTX_MODEL

    if CTX_BACKBONE == "mc3_18":
        from torchvision.models.video import mc3_18, MC3_18_Weights
        weights = MC3_18_Weights.DEFAULT
        model = mc3_18(weights=weights)
        model.fc = nn.Identity()
    elif CTX_BACKBONE == "r2plus1d_18":
        from torchvision.models.video import r2plus1d_18, R2Plus1D_18_Weights
        weights = R2Plus1D_18_Weights.DEFAULT
        model = r2plus1d_18(weights=weights)
        model.fc = nn.Identity()
    else:
        from torchvision.models.video import r3d_18, R3D_18_Weights
        weights = R3D_18_Weights.DEFAULT
        model = r3d_18(weights=weights)
        model.fc = nn.Identity()

    model = model.to(device).eval()
    _CTX_MODEL = model
    return _CTX_MODEL


def _preprocess_clip_torch(clip_rgb: np.ndarray, device: str) -> torch.Tensor:
    x = torch.from_numpy(clip_rgb).to(torch.float32) / 255.0
    x = x.permute(3, 0, 1, 2)  # (C,T,H,W)
    x = x.unsqueeze(0)         # (1,C,T,H,W)
    x = F.interpolate(x, size=(x.shape[2], 112, 112), mode="trilinear", align_corners=False)

    mean = torch.tensor([0.43216, 0.394666, 0.37645], device=x.device).view(1,3,1,1,1)
    std  = torch.tensor([0.22803, 0.22145, 0.216989], device=x.device).view(1,3,1,1,1)
    x = (x - mean) / std
    return x.to(device)


@torch.no_grad()
def extract_ctx_stream(video_path: str, device: str = "cuda", chunk: int = 32) -> torch.Tensor:
    model = build_ctx_model(device=device)
    vr = _vr(video_path)
    T = len(vr)
    if T <= 0:
        return torch.zeros((0, 512), dtype=torch.float32)

    pad = (-T) % chunk
    total = T + pad

    feats = []
    for i in range(0, total, chunk):
        idxs = list(range(i, min(i + chunk, T)))
        if len(idxs) == 0:
            break
        frames = vr.get_batch(idxs).asnumpy()
        if frames.shape[0] < chunk:
            frames = np.concatenate([frames, np.repeat(frames[-1:], chunk - frames.shape[0], axis=0)], axis=0)

        x = _preprocess_clip_torch(frames, device=device)
        f = model(x).squeeze(0).detach().cpu()
        feats.append(f)

    return torch.stack(feats, dim=0).to(torch.float32)


# ---------------------------
# FACE
# ---------------------------
_FACE_MODEL = None
_EMO_REC = None

def _init_yolo():
    global _FACE_MODEL
    if _FACE_MODEL is not None:
        return _FACE_MODEL
    try:
        from ultralytics import YOLO
        for w in ["yolov8n-face.pt", "yolov8n.pt"]:
            try:
                _FACE_MODEL = YOLO(w)
                break
            except Exception:
                _FACE_MODEL = None
    except Exception:
        _FACE_MODEL = None
    return _FACE_MODEL


def _center_crop(img, size=224):
    h, w = img.shape[:2]
    s = min(h, w)
    y0 = (h - s) // 2
    x0 = (w - s) // 2
    crop = img[y0:y0+s, x0:x0+s]
    import cv2
    crop = cv2.resize(crop, (size, size))
    return crop


def _detect_face_crop(img_rgb, size=224):
    if FACE_DETECT == "center":
        return _center_crop(img_rgb, size=size), True

    model = _init_yolo()
    if model is None:
        return _center_crop(img_rgb, size=size), False

    try:
        res = model.predict(source=img_rgb, verbose=False)
        if len(res) == 0 or res[0].boxes is None or len(res[0].boxes) == 0:
            return _center_crop(img_rgb, size=size), False
        boxes = res[0].boxes.xyxy.detach().cpu().numpy()
        areas = (boxes[:,2]-boxes[:,0])*(boxes[:,3]-boxes[:,1])
        b = boxes[int(np.argmax(areas))]
        x1, y1, x2, y2 = [int(max(0, v)) for v in b]
        x2 = min(x2, img_rgb.shape[1]-1)
        y2 = min(y2, img_rgb.shape[0]-1)
        crop = img_rgb[y1:y2, x1:x2]
        if crop.size == 0:
            return _center_crop(img_rgb, size=size), False
        import cv2
        crop = cv2.resize(crop, (size, size))
        return crop, True
    except Exception:
        return _center_crop(img_rgb, size=size), False


def _init_emotieff(device: str):
    global _EMO_REC
    if _EMO_REC is not None:
        return _EMO_REC
    from emotiefflib.facial_analysis import EmotiEffLibRecognizerTorch
    try:
        _EMO_REC = EmotiEffLibRecognizerTorch(device=device)
    except TypeError:
        _EMO_REC = EmotiEffLibRecognizerTorch()
    return _EMO_REC


def _as_rgb_uint8(face_rgb_224):
    x = np.asarray(face_rgb_224)
    if x.dtype != np.uint8:
        x = np.clip(x, 0, 255).astype(np.uint8)
    return x


@torch.no_grad()
def emotieff_embed(face_rgb_224: np.ndarray, device: str = "cuda") -> np.ndarray:
    rec = _init_emotieff(device=device)
    x = _as_rgb_uint8(face_rgb_224)

    for name in ["get_face_embedding","get_embedding","get_embeddings","extract_embedding","extract_embeddings","get_features","extract_features"]:
        if hasattr(rec, name) and callable(getattr(rec, name)):
            out = getattr(rec, name)(x)
            return np.asarray(out).reshape(-1).astype(np.float32)

    if callable(rec):
        out = rec(x)
        if isinstance(out, dict):
            for k in ["embedding","emb","features","feature"]:
                if k in out:
                    return np.asarray(out[k]).reshape(-1).astype(np.float32)
        return np.asarray(out).reshape(-1).astype(np.float32)

    raise RuntimeError("EmotiEffLib: не удалось получить embedding")


@torch.no_grad()
def extract_face_windows(video_path: str, device: str = "cuda", chunk: int = 32) -> Tuple[torch.Tensor, torch.Tensor]:
    vr = _vr(video_path)
    T = len(vr)
    if T <= 0:
        return torch.zeros((0, 1280), dtype=torch.float32), torch.zeros((0,), dtype=torch.bool)

    pad = (-T) % chunk
    total = T + pad

    feats = []
    mask = []
    D = None

    for i in range(0, total, chunk):
        if FACE_SAMPLING == "3frames_avg":
            idxs = [
                min(i + max(0, chunk // 4), T - 1),
                min(i + max(0, chunk // 2), T - 1),
                min(i + max(0, (3 * chunk) // 4), T - 1),
            ]
        else:
            idxs = [min(i + chunk // 2, T - 1)]

        embs = []
        oks = []
        for idx in idxs:
            frame = vr[idx].asnumpy()
            crop, ok = _detect_face_crop(frame, size=224)
            if ok:
                embs.append(emotieff_embed(crop, device=device))
                oks.append(True)
            else:
                oks.append(False)

        if any(oks):
            emb = np.mean(embs, axis=0).astype(np.float32)
            if D is None:
                D = int(emb.shape[0])
            feats.append(torch.from_numpy(emb).to(torch.float32))
            mask.append(True)
        else:
            if D is None:
                D = 1280
            feats.append(torch.zeros((D,), dtype=torch.float32))
            mask.append(False)

    face = torch.stack(feats, dim=0)
    fmask = torch.tensor(mask, dtype=torch.bool)
    return face, fmask


# ---------------------------
# SKEL
# ---------------------------
_SKEL_PROJ = None

def _skel_projector(in_dim: int, out_dim: int = 512) -> nn.Module:
    global _SKEL_PROJ
    if _SKEL_PROJ is not None and getattr(_SKEL_PROJ, "_in_dim", None) == in_dim:
        return _SKEL_PROJ
    torch.manual_seed(42)
    proj = nn.Sequential(
        nn.Linear(in_dim, out_dim),
        nn.LayerNorm(out_dim),
        nn.GELU(),
    )
    proj._in_dim = in_dim
    _SKEL_PROJ = proj.eval()
    return _SKEL_PROJ


def _load_skeleton_csv(path: str) -> np.ndarray:
    df = pd.read_csv(path)
    return df.values.astype(np.float32)  # (T,D)


@torch.no_grad()
def extract_skeleton_windows(skel_csv_path: str, device: str = "cpu", chunk: int = 32) -> Tuple[torch.Tensor, torch.Tensor]:
    arr = _load_skeleton_csv(skel_csv_path)
    T, D = arr.shape
    if T <= 0:
        return torch.zeros((0, 512), dtype=torch.float32), torch.zeros((0,), dtype=torch.bool)

    pad = (-T) % chunk
    total = T + pad
    if pad:
        arr = np.concatenate([arr, np.repeat(arr[-1:], pad, axis=0)], axis=0)

    # aggregator output dim
    if SKEL_AGG == "mean_std":
        in_dim = 2 * D
    else:
        in_dim = D

    proj = _skel_projector(in_dim, 512)

    feats = []
    mask = []
    for i in range(0, total, chunk):
        w = arr[i:i+chunk]  # (chunk,D)
        valid = not np.allclose(w, 0)

        if SKEL_AGG == "max":
            v = w.max(axis=0)
        elif SKEL_AGG == "mean_std":
            mu = w.mean(axis=0)
            sd = w.std(axis=0)
            v = np.concatenate([mu, sd], axis=0)
        else:
            v = w.mean(axis=0)

        x = torch.from_numpy(v).to(torch.float32)
        z = proj(x).detach().cpu()
        feats.append(z)
        mask.append(valid)

    skel = torch.stack(feats, dim=0).to(torch.float32)
    smask = torch.tensor(mask, dtype=torch.bool)
    return skel, smask


@torch.no_grad()
def build_and_cache_one(
    video_id: int,
    split: str,
    phase: int,
    feat_dir: str,
    chunk: int = 32,
    vpath: Optional[str] = None,
    spath: Optional[str] = None,
    do_ctx: bool = True,
    do_face: bool = True,
    do_skel: bool = True,
    device: str = "cuda",
):
    ps = cache_paths(feat_dir, video_id, split, phase)

    if vpath is None:
        vpath = resolve_video_path_phase1(video_id, split) if phase == 1 else resolve_video_path_phase2(video_id)

    if spath is None:
        spath = resolve_skeleton_path_phase1(video_id, split) if phase == 1 else resolve_skeleton_path_phase2(video_id)

    if do_ctx or do_face:
        if vpath is None or (not os.path.exists(vpath)):
            raise FileNotFoundError(f"RGB video not found for id={video_id} split={split} phase={phase}")

    if do_skel:
        if spath is None or (not os.path.exists(spath)):
            raise FileNotFoundError(f"Skeleton csv not found for id={video_id} split={split} phase={phase}")

    if do_ctx and (not os.path.exists(ps["ctx"])):
        ctx = extract_ctx_stream(vpath, device=device, chunk=chunk)
        torch.save(ctx, ps["ctx"])

    if do_face and (not os.path.exists(ps["face"])) and (not os.path.exists(ps["fmask"])):
        face, fmask = extract_face_windows(vpath, device=device, chunk=chunk)
        torch.save(face, ps["face"])
        torch.save(fmask, ps["fmask"])

    if do_skel and (not os.path.exists(ps["skel"])) and (not os.path.exists(ps["smask"])):
        skel, smask = extract_skeleton_windows(spath, device="cpu", chunk=chunk)
        torch.save(skel, ps["skel"])
        torch.save(smask, ps["smask"])

    return ps

Writing /content/src/feature_extract.py

In [13]:
%%writefile /content/src/cache_features_cli.py
import argparse
import pandas as pd
from tqdm import tqdm
import torch
import traceback

from src.feature_extract import build_and_cache_one

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", required=True)
    ap.add_argument("--phase", type=int, required=True)
    ap.add_argument("--feat_dir", required=True)
    ap.add_argument("--chunk", type=int, default=32)
    ap.add_argument("--start", type=int, default=0)
    ap.add_argument("--end", type=int, default=999999)
    ap.add_argument("--split_col", type=str, default="split")
    ap.add_argument("--device", choices=["auto","cpu","cuda"], default="auto")
    ap.add_argument("--do_ctx", action="store_true")
    ap.add_argument("--do_face", action="store_true")
    ap.add_argument("--do_skel", action="store_true")
    args = ap.parse_args()

    if args.device == "auto":
        device = "cuda" if torch.cuda.is_available() else "cpu"
    else:
        device = args.device

    if not (args.do_ctx or args.do_face or args.do_skel):
        args.do_ctx = args.do_face = args.do_skel = True

    print("DEVICE:", device)
    print("FEAT_DIR:", args.feat_dir)
    print("MODES: ctx=", args.do_ctx, "face=", args.do_face, "skel=", args.do_skel)

    df = pd.read_csv(args.csv)
    df = df.iloc[args.start:args.end].reset_index(drop=True)

    ok, bad = 0, 0

    for i, r in tqdm(df.iterrows(), total=len(df)):
        try:
            vid = int(r["video_id"])
            split = r.get(args.split_col, "test")

            build_and_cache_one(
                video_id=vid,
                split=split,
                phase=args.phase,
                feat_dir=args.feat_dir,
                chunk=args.chunk,
                vpath=None,
                spath=r.get("skeleton_path", None),
                do_ctx=args.do_ctx,
                do_face=args.do_face,
                do_skel=args.do_skel,
                device=device,
            )
            ok += 1

        except Exception:
            bad += 1
            print(" ERROR")
            print("row:", i, "video_id:", r.get("video_id"), "split:", r.get(args.split_col, ""))
            if "skeleton_path" in r:
                print("skeleton_path:", r.get("skeleton_path"))
            traceback.print_exc()

    print(f"\nDONE shard [{args.start}:{args.end}) ok={ok} bad={bad}")

if __name__ == "__main__":
    main()

Writing /content/src/cache_features_cli.py

**Исследование вариантов создания эмбеддингов**

**CTX Variant 0: r3d_18**

In [ ]:
%%bash
export CTX_BACKBONE=r3d_18

CHUNK=64
SHARD=10
DEVICE=cuda
CSV=/content/phase1_all_with_split.csv
BASE_FEAT_DIR=/content/drive/MyDrive/miga_features_cache_agcn
EXP_NAME=baseline_ctx
FEAT_DIR=${BASE_FEAT_DIR}/${EXP_NAME}

mkdir -p "$FEAT_DIR"

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase1_all_with_split.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD))
  if [ $END -gt $TOTAL ]; then END=$TOTAL; fi

  echo "=== CTX baseline (r3d_18) shard $START:$END (chunk=$CHUNK) ==="
  PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 python -u /content/src/cache_features_cli.py \
    --csv $CSV --phase 1 --feat_dir "$FEAT_DIR" \
    --chunk $CHUNK --start $START --end $END --device $DEVICE \
    --do_ctx

  START=$END
done

=== CTX baseline (r3d_18) shard 0:10 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False
Downloading: "https://download.pytorch.org/models/r3d_18-b3b3357e.pth" to /root/.cache/torch/hub/checkpoints/r3d_18-b3b3357e.pth

DONE shard [0:10) ok=10 bad=0
=== CTX baseline (r3d_18) shard 10:20 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [10:20) ok=10 bad=0
=== CTX baseline (r3d_18) shard 20:30 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [20:30) ok=10 bad=0
=== CTX baseline (r3d_18) shard 30:40 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [30:40) ok=10 bad=0
=== CTX baseline (r3d_18) shard 40:50 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [40:50) ok=10 bad=0
=== CTX baseline (r3d_18) shard 50:60 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [50:60) ok=10 bad=0
=== CTX baseline (r3d_18) shard 60:70 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [60:70) ok=10 bad=0
=== CTX baseline (r3d_18) shard 70:80 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [70:80) ok=10 bad=0
=== CTX baseline (r3d_18) shard 80:90 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [80:90) ok=10 bad=0
=== CTX baseline (r3d_18) shard 90:100 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [90:100) ok=10 bad=0
=== CTX baseline (r3d_18) shard 100:110 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [100:110) ok=10 bad=0
=== CTX baseline (r3d_18) shard 110:120 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [110:120) ok=10 bad=0
=== CTX baseline (r3d_18) shard 120:130 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [120:130) ok=10 bad=0
=== CTX baseline (r3d_18) shard 130:140 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [130:140) ok=10 bad=0
=== CTX baseline (r3d_18) shard 140:150 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [140:150) ok=10 bad=0
=== CTX baseline (r3d_18) shard 150:160 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [150:160) ok=10 bad=0
=== CTX baseline (r3d_18) shard 160:170 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [160:170) ok=10 bad=0
=== CTX baseline (r3d_18) shard 170:180 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [170:180) ok=10 bad=0
=== CTX baseline (r3d_18) shard 180:190 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [180:190) ok=10 bad=0
=== CTX baseline (r3d_18) shard 190:200 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [190:200) ok=10 bad=0
=== CTX baseline (r3d_18) shard 200:210 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [200:210) ok=10 bad=0
=== CTX baseline (r3d_18) shard 210:220 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [210:220) ok=10 bad=0
=== CTX baseline (r3d_18) shard 220:230 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [220:230) ok=10 bad=0
=== CTX baseline (r3d_18) shard 230:240 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [230:240) ok=10 bad=0
=== CTX baseline (r3d_18) shard 240:250 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [240:250) ok=10 bad=0
=== CTX baseline (r3d_18) shard 250:255 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
MODES: ctx= True face= False skel= False

DONE shard [250:255) ok=5 bad=0

  0%|          | 0/10 [00:00<?, ?it/s]
  0%|          | 0.00/127M [00:00<?, ?B/s]
  2%|▏         | 2.25M/127M [00:00<00:05, 23.2MB/s]
  4%|▎         | 4.50M/127M [00:00<00:05, 22.7MB/s]
 16%|█▋        | 20.9M/127M [00:00<00:01, 89.1MB/s]
 30%|███       | 38.2M/127M [00:00<00:00, 125MB/s]
 47%|████▋     | 60.4M/127M [00:00<00:00, 163MB/s]
 60%|█████▉    | 76.1M/127M [00:00<00:00, 156MB/s]
 72%|███████▏  | 91.1M/127M [00:00<00:00, 149MB/s]
100%|██████████| 127M/127M [00:00<00:00, 147MB/s]
100%|██████████| 10/10 [08:48<00:00, 52.86s/it]
100%|██████████| 10/10 [08:53<00:00, 53.37s/it]
100%|██████████| 10/10 [09:49<00:00, 58.93s/it]
100%|██████████| 10/10 [07:23<00:00, 44.34s/it]
100%|██████████| 10/10 [12:54<00:00, 77.43s/it]
100%|██████████| 10/10 [13:29<00:00, 80.90s/it]
100%|██████████| 10/10 [09:40<00:00, 58.06s/it]
100%|██████████| 10/10 [14:51<00:00, 89.15s/it]
100%|██████████| 10/10 [09:45<00:00, 58.54s/it]
100%|██████████| 10/10 [07:14<00:00, 43.50s/it]
100%|██████████| 10/10 [10:24<00:00, 62.48s/it]
100%|██████████| 10/10 [12:30<00:00, 75.05s/it]
100%|██████████| 10/10 [12:26<00:00, 74.69s/it]
100%|██████████| 10/10 [13:52<00:00, 83.21s/it]
100%|██████████| 10/10 [08:56<00:00, 53.66s/it]
100%|██████████| 10/10 [14:11<00:00, 85.17s/it]
100%|██████████| 10/10 [10:08<00:00, 60.89s/it]
100%|██████████| 10/10 [11:22<00:00, 68.26s/it]
100%|██████████| 10/10 [09:00<00:00, 54.05s/it]
100%|██████████| 10/10 [10:54<00:00, 65.45s/it]
100%|██████████| 10/10 [13:54<00:00, 83.40s/it]
100%|██████████| 10/10 [10:10<00:00, 61.01s/it]
100%|██████████| 10/10 [08:12<00:00, 49.24s/it]
100%|██████████| 10/10 [09:28<00:00, 56.82s/it]
100%|██████████| 10/10 [13:32<00:00, 81.27s/it]
100%|██████████| 5/5 [04:47<00:00, 57.54s/it]

**CTX Variant 1: exp_ctx_m**

In [ ]:
%%bash
set -euxo pipefail
CSV=/content/phase1_all_with_split.csv
BASE_DIR=/content/drive/MyDrive/miga_features_cache_agcn
EXP_DIR=/content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3

# 1) symlink all baseline into exp (fast)
mkdir -p "$EXP_DIR"
ln -sfn "$BASE_DIR"/*_face.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_facemask.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_skel.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_skelmask.pt "$EXP_DIR"/ 2>/dev/null || true

# 2) recompute ONLY ctx into exp
DEVICE=cuda
CHUNK=32
SHARD=10
export PYTHONUNBUFFERED=1

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase1_all_with_split.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD)); if [ $END -gt $TOTAL ]; then END=$TOTAL; fi
  echo "=== CTX mc3_18 shard $START:$END ==="
  time env CTX_BACKBONE=mc3_18 PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 \
    python -u /content/src/cache_features_cli.py \
      --csv "$CSV" --phase 1 --feat_dir "$EXP_DIR" \
      --chunk "$CHUNK" --start "$START" --end "$END" --device "$DEVICE" \
      --do_ctx
  START=$END
done

=== CTX mc3_18 shard 0:10 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [0:10) ok=10 bad=0
=== CTX mc3_18 shard 10:20 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [10:20) ok=10 bad=0
=== CTX mc3_18 shard 20:30 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [20:30) ok=10 bad=0
=== CTX mc3_18 shard 30:40 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [30:40) ok=10 bad=0
=== CTX mc3_18 shard 40:50 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [40:50) ok=10 bad=0
=== CTX mc3_18 shard 50:60 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [50:60) ok=10 bad=0
=== CTX mc3_18 shard 60:70 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [60:70) ok=10 bad=0
=== CTX mc3_18 shard 70:80 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [70:80) ok=10 bad=0
=== CTX mc3_18 shard 80:90 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [80:90) ok=10 bad=0
=== CTX mc3_18 shard 90:100 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [90:100) ok=10 bad=0
=== CTX mc3_18 shard 100:110 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [100:110) ok=10 bad=0
=== CTX mc3_18 shard 110:120 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [110:120) ok=10 bad=0
=== CTX mc3_18 shard 120:130 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [120:130) ok=10 bad=0
=== CTX mc3_18 shard 130:140 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [130:140) ok=10 bad=0
=== CTX mc3_18 shard 140:150 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [140:150) ok=10 bad=0
=== CTX mc3_18 shard 150:160 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [150:160) ok=10 bad=0
=== CTX mc3_18 shard 160:170 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [160:170) ok=10 bad=0
=== CTX mc3_18 shard 170:180 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [170:180) ok=10 bad=0
=== CTX mc3_18 shard 180:190 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [180:190) ok=10 bad=0
=== CTX mc3_18 shard 190:200 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [190:200) ok=10 bad=0
=== CTX mc3_18 shard 200:210 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [200:210) ok=10 bad=0
=== CTX mc3_18 shard 210:220 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [210:220) ok=10 bad=0
=== CTX mc3_18 shard 220:230 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [220:230) ok=10 bad=0
=== CTX mc3_18 shard 230:240 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [230:240) ok=10 bad=0
=== CTX mc3_18 shard 240:250 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [240:250) ok=10 bad=0
=== CTX mc3_18 shard 250:255 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
MODES: ctx= True face= False skel= False

DONE shard [250:255) ok=5 bad=0

+ CSV=/content/phase1_all_with_split.csv
+ BASE_DIR=/content/drive/MyDrive/miga_features_cache_agcn
+ EXP_DIR=/content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
+ mkdir -p /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
+ ln -sfn /content/drive/MyDrive/miga_features_cache_agcn/00a3ed33d38e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/00b40a2e4d97_face.pt /content/drive/MyDrive/miga_features_cache_agcn/01087f1b2489_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0123fc67d163_face.pt /content/drive/MyDrive/miga_features_cache_agcn/017fc7925072_face.pt /content/drive/MyDrive/miga_features_cache_agcn/01b372587e0a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/01dc5000e304_face.pt /content/drive/MyDrive/miga_features_cache_agcn/03ae04661248_face.pt /content/drive/MyDrive/miga_features_cache_agcn/049e754be9f7_face.pt /content/drive/MyDrive/miga_features_cache_agcn/04c0dc00860f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/05b600b0301d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/06a239e6b160_face.pt /content/drive/MyDrive/miga_features_cache_agcn/088f59f97642_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0908fd243ee3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/097537f5b986_face.pt /content/drive/MyDrive/miga_features_cache_agcn/09a4cc150f42_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0a096ee9e4a1_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0cae4d6d7f9c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0db8d3e98501_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0dc25751f019_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0dd6795a6dc0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0f2989c1a220_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0f9b72cc21eb_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1018772cd839_face.pt /content/drive/MyDrive/miga_features_cache_agcn/108de304743f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/11646ef853d5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1262ccdf5117_face.pt /content/drive/MyDrive/miga_features_cache_agcn/13756240ecd1_face.pt /content/drive/MyDrive/miga_features_cache_agcn/13c5f3185145_face.pt /content/drive/MyDrive/miga_features_cache_agcn/15e9668db234_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1620ff2a4e19_face.pt /content/drive/MyDrive/miga_features_cache_agcn/17e047e91727_face.pt /content/drive/MyDrive/miga_features_cache_agcn/181fb208dd25_face.pt /content/drive/MyDrive/miga_features_cache_agcn/186cb628a00e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/19843783231b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1d4ede1331de_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1eae6962a63b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1f8aad2528dc_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1fd4173fb471_face.pt /content/drive/MyDrive/miga_features_cache_agcn/201ede2caf26_face.pt /content/drive/MyDrive/miga_features_cache_agcn/209501eeb4a6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/221dfd7cebef_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2268ae4188f5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/22df7084383e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/239a3da840af_face.pt /content/drive/MyDrive/miga_features_cache_agcn/246c9b03d6f0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/252d6f4d416a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/255f7de773f8_face.pt /content/drive/MyDrive/miga_features_cache_agcn/27384aedf70d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2a7eecbafa56_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2ae8451ecf7c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2b10042d06ec_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2bacf5eaa39f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2e8718371d09_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2ea484cff01b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2ed626e5ffd3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/30ac0539b4a4_face.pt /content/drive/MyDrive/miga_features_cache_agcn/31e7c5a602ca_face.pt /content/drive/MyDrive/miga_features_cache_agcn/322324881360_face.pt /content/drive/MyDrive/miga_features_cache_agcn/338be23bfe9a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/34c172f4f548_face.pt /content/drive/MyDrive/miga_features_cache_agcn/355330b3a745_face.pt /content/drive/MyDrive/miga_features_cache_agcn/36066a55360f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/39060ead04db_face.pt /content/drive/MyDrive/miga_features_cache_agcn/39fe9da25570_face.pt /content/drive/MyDrive/miga_features_cache_agcn/3c8a19f1a77f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/3dd68fd73380_face.pt /content/drive/MyDrive/miga_features_cache_agcn/3e960c17e92e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/3f362975f317_face.pt /content/drive/MyDrive/miga_features_cache_agcn/3f8c022aaee6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/41af1a5aaffe_face.pt /content/drive/MyDrive/miga_features_cache_agcn/41f09daf4463_face.pt /content/drive/MyDrive/miga_features_cache_agcn/420233bb0153_face.pt /content/drive/MyDrive/miga_features_cache_agcn/43c5f5d4c08f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/440c24c623d1_face.pt /content/drive/MyDrive/miga_features_cache_agcn/45f2cba4384d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/47f64f106476_face.pt /content/drive/MyDrive/miga_features_cache_agcn/48b10dbd49ea_face.pt /content/drive/MyDrive/miga_features_cache_agcn/4a4778763d48_face.pt /content/drive/MyDrive/miga_features_cache_agcn/4b30c36d5a25_face.pt /content/drive/MyDrive/miga_features_cache_agcn/4bcde5a82194_face.pt /content/drive/MyDrive/miga_features_cache_agcn/4ca8e56af321_face.pt /content/drive/MyDrive/miga_features_cache_agcn/513d88fe11db_face.pt /content/drive/MyDrive/miga_features_cache_agcn/530ab6cff714_face.pt /content/drive/MyDrive/miga_features_cache_agcn/532f2f26a7b3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/53a70417fdb7_face.pt /content/drive/MyDrive/miga_features_cache_agcn/578e25e98810_face.pt /content/drive/MyDrive/miga_features_cache_agcn/59c71581045f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/59f1a1cf0a2e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/5b8eba00fd84_face.pt /content/drive/MyDrive/miga_features_cache_agcn/5dd01777bad9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/5dec9937a35a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/5e6ad9aeee6c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/5f60788646aa_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6107dcd2b8db_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6225dffcf8c9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/633afcff2cac_face.pt /content/drive/MyDrive/miga_features_cache_agcn/634c417ee7a6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/64e8ed0acfa7_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6789660f21c3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/68a650f0bb38_face.pt /content/drive/MyDrive/miga_features_cache_agcn/69e068b4a055_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6a619c1e55b7_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6a7be86ff5a1_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6ad2587edec6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6afbeeeeb9db_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6b39551b10ed_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6bfeb4eefb06_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6ce872d5e39b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6d2f7cd0c56c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6d40cdb467e2_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6e97a12d04e5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7074194cbadf_face.pt /content/drive/MyDrive/miga_features_cache_agcn/71c78f751e78_face.pt /content/drive/MyDrive/miga_features_cache_agcn/71d43e439939_face.pt /content/drive/MyDrive/miga_features_cache_agcn/721bee2d4bf2_face.pt /content/drive/MyDrive/miga_features_cache_agcn/72679ca2a7c1_face.pt /content/drive/MyDrive/miga_features_cache_agcn/72ce819af3f5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/73cc360c5976_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7410f44a80a0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/747dbc308fef_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7570191191d8_face.pt /content/drive/MyDrive/miga_features_cache_agcn/75c656b4afc2_face.pt /content/drive/MyDrive/miga_features_cache_agcn/76d64d1731fa_face.pt /content/drive/MyDrive/miga_features_cache_agcn/77f5e5625e93_face.pt /content/drive/MyDrive/miga_features_cache_agcn/782ff1188c9a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/78c469b55ea4_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7961205cec28_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7a4d3f7dddf0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7b4f62aeeda8_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7c20862a49a3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7c96a830913f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7de93a7e893f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7e985501bd16_face.pt /content/drive/MyDrive/miga_features_cache_agcn/80b0cd5eec88_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8264c10dfaaf_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8330f28b0e36_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8341d4e5de0b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/84166a7963c0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/84844a54aef0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/84fa203c5d4c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/85915c3ddab5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/85e46c0ac09e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/869c78216f36_face.pt /content/drive/MyDrive/miga_features_cache_agcn/87031007b9c0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/870ffff332ff_face.pt /content/drive/MyDrive/miga_features_cache_agcn/873a07d8ed3b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8826bb56b47c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8ae7069778aa_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8d87517df5d4_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8dd5161305d9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8ebd6371c670_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8f19d2139c7a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8ff0ddc359fd_face.pt /content/drive/MyDrive/miga_features_cache_agcn/90066b62470f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/90ffc2922e23_face.pt /content/drive/MyDrive/miga_features_cache_agcn/918e88d8abc1_face.pt /content/drive/MyDrive/miga_features_cache_agcn/943d3a758d2b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/95b05994091e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/96619b01229e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/9788e20aadfe_face.pt /content/drive/MyDrive/miga_features_cache_agcn/98f7fece2e41_face.pt /content/drive/MyDrive/miga_features_cache_agcn/993b0087a04a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/995a81c6fe26_face.pt /content/drive/MyDrive/miga_features_cache_agcn/996a670be739_face.pt /content/drive/MyDrive/miga_features_cache_agcn/9ca6fcf22282_face.pt /content/drive/MyDrive/miga_features_cache_agcn/9d56dfadd7d0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/9ef217cb48a9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/9f63e9fa3887_face.pt /content/drive/MyDrive/miga_features_cache_agcn/a07c31a5a305_face.pt /content/drive/MyDrive/miga_features_cache_agcn/a1dfee690987_face.pt /content/drive/MyDrive/miga_features_cache_agcn/a2e7f4b7d7a6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/a3a59a12efe6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/a826a158ebe0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/a8772324bb06_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ab04355a15a9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/abf023461e31_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ad8a195c26e0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/aecc066581e3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/af27e31fd2ff_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b1251a1fd26e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b27373f02956_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b2f54b00dda2_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b36a91a30103_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b3b0fdb1426a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b4a21e3b1d42_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b50e15067a77_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b7180660d049_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b7c0c5adddd6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b803c73db2f5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b8366f151998_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b87e5c420569_face.pt /content/drive/MyDrive/miga_features_cache_agcn/bc604e11cd28_face.pt /content/drive/MyDrive/miga_features_cache_agcn/be6f549156a8_face.pt /content/drive/MyDrive/miga_features_cache_agcn/befa9fe7ec10_face.pt /content/drive/MyDrive/miga_features_cache_agcn/c1a60588a819_face.pt /content/drive/MyDrive/miga_features_cache_agcn/c2dfdd55bb77_face.pt /content/drive/MyDrive/miga_features_cache_agcn/c38ff05f1cb9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/c40273ffad59_face.pt /content/drive/MyDrive/miga_features_cache_agcn/c538ff5af2fc_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ca250e19a593_face.pt /content/drive/MyDrive/miga_features_cache_agcn/cac3c88764f6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ce6aad694dcc_face.pt /content/drive/MyDrive/miga_features_cache_agcn/cfe1d32f286d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/cffef16acdb3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/d04f3fe7aae0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/d25ad6b652f9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/d43a5a46819c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/d5226a19cc4d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/d76fec6d157b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/d8b71e097390_face.pt /content/drive/MyDrive/miga_features_cache_agcn/dac73e3f6772_face.pt /content/drive/MyDrive/miga_features_cache_agcn/db57a768e402_face.pt /content/drive/MyDrive/miga_features_cache_agcn/dbc7add1be13_face.pt /content/drive/MyDrive/miga_features_cache_agcn/dca1f75d184d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/dd0e23932d2d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ddc36aafbe05_face.pt /content/drive/MyDrive/miga_features_cache_agcn/de935844c489_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ded8ad49fb4c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/dff90c7db1a5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e06a6125b4e0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e19f7ae86079_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e1adc4e5fdfb_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e3804ad76f56_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e3a17c0701de_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e53fbeb7872c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e56facbbec94_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e704f197f883_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e86c65a2ad2a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ea96b83905a8_face.pt /content/drive/MyDrive/miga_features_cache_agcn/eaf780e7913f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/eb6131cde7d8_face.pt /content/drive/MyDrive/miga_features_cache_agcn/eb623bd6229b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ebaaadd6489e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ec2a894eb09e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ec2e6984eb7a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ecaad627cf65_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ecc0d5a08ec9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ed5e79afe62a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ee71bbfa1f73_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f06014a5588d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f094214631d9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f1bca4fd3891_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f2fb190167f0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f3127395d63c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f32bb17682fd_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f3625dd8126d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f49286e2ca84_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f59b28bb72fe_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f68588ab68bb_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f6da49ba7687_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f8fa67c44485_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f8fc3aa00f3f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f99c8748866d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/fa6c7f5ece5d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/faade2189271_face.pt /content/drive/MyDrive/miga_features_cache_agcn/fbf0e0e763d9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/fc4764de32f3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/fe2cce3f720b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ff7690117ecc_face.pt /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3/
+ true

**CTX Variant 2: exp_ctx_r2plus1d**

In [ ]:
%%bash
set -euxo pipefail
CSV=/content/phase1_all_with_split.csv
BASE_DIR=/content/drive/MyDrive/miga_features_cache_agcn
EXP_DIR=/content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d

mkdir -p "$EXP_DIR"
ln -sfn "$BASE_DIR"/*_face.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_facemask.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_skel.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_skelmask.pt "$EXP_DIR"/ 2>/dev/null || true

DEVICE=cuda
CHUNK=32
SHARD=10
export PYTHONUNBUFFERED=1

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase1_all_with_split.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD)); if [ $END -gt $TOTAL ]; then END=$TOTAL; fi
  echo "=== CTX r2plus1d_18 shard $START:$END ==="
  time env CTX_BACKBONE=r2plus1d_18 PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 \
    python -u /content/src/cache_features_cli.py \
      --csv "$CSV" --phase 1 --feat_dir "$EXP_DIR" \
      --chunk "$CHUNK" --start "$START" --end "$END" --device "$DEVICE" \
      --do_ctx
  START=$END
done

=== CTX r2plus1d_18 shard 0:10 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False
Downloading: "https://download.pytorch.org/models/r2plus1d_18-91a641e6.pth" to /root/.cache/torch/hub/checkpoints/r2plus1d_18-91a641e6.pth

DONE shard [0:10) ok=10 bad=0
=== CTX r2plus1d_18 shard 10:20 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [10:20) ok=10 bad=0
=== CTX r2plus1d_18 shard 20:30 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [20:30) ok=10 bad=0
=== CTX r2plus1d_18 shard 30:40 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [30:40) ok=10 bad=0
=== CTX r2plus1d_18 shard 40:50 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [40:50) ok=10 bad=0
=== CTX r2plus1d_18 shard 50:60 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [50:60) ok=10 bad=0
=== CTX r2plus1d_18 shard 60:70 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [60:70) ok=10 bad=0
=== CTX r2plus1d_18 shard 70:80 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [70:80) ok=10 bad=0
=== CTX r2plus1d_18 shard 80:90 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [80:90) ok=10 bad=0
=== CTX r2plus1d_18 shard 90:100 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [90:100) ok=10 bad=0
=== CTX r2plus1d_18 shard 100:110 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [100:110) ok=10 bad=0
=== CTX r2plus1d_18 shard 110:120 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [110:120) ok=10 bad=0
=== CTX r2plus1d_18 shard 120:130 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [120:130) ok=10 bad=0
=== CTX r2plus1d_18 shard 130:140 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [130:140) ok=10 bad=0
=== CTX r2plus1d_18 shard 140:150 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [140:150) ok=10 bad=0
=== CTX r2plus1d_18 shard 150:160 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [150:160) ok=10 bad=0
=== CTX r2plus1d_18 shard 160:170 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [160:170) ok=10 bad=0
=== CTX r2plus1d_18 shard 170:180 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [170:180) ok=10 bad=0
=== CTX r2plus1d_18 shard 180:190 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [180:190) ok=10 bad=0
=== CTX r2plus1d_18 shard 190:200 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [190:200) ok=10 bad=0
=== CTX r2plus1d_18 shard 200:210 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [200:210) ok=10 bad=0
=== CTX r2plus1d_18 shard 210:220 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [210:220) ok=10 bad=0
=== CTX r2plus1d_18 shard 220:230 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [220:230) ok=10 bad=0
=== CTX r2plus1d_18 shard 230:240 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [230:240) ok=10 bad=0
=== CTX r2plus1d_18 shard 240:250 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [240:250) ok=10 bad=0
=== CTX r2plus1d_18 shard 250:255 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [250:255) ok=5 bad=0

+ CSV=/content/phase1_all_with_split.csv
+ BASE_DIR=/content/drive/MyDrive/miga_features_cache_agcn
+ EXP_DIR=/content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
+ mkdir -p /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
+ ln -sfn /content/drive/MyDrive/miga_features_cache_agcn/00a3ed33d38e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/00b40a2e4d97_face.pt /content/drive/MyDrive/miga_features_cache_agcn/01087f1b2489_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0123fc67d163_face.pt /content/drive/MyDrive/miga_features_cache_agcn/017fc7925072_face.pt /content/drive/MyDrive/miga_features_cache_agcn/01b372587e0a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/01dc5000e304_face.pt /content/drive/MyDrive/miga_features_cache_agcn/03ae04661248_face.pt /content/drive/MyDrive/miga_features_cache_agcn/049e754be9f7_face.pt /content/drive/MyDrive/miga_features_cache_agcn/04c0dc00860f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/05b600b0301d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/06a239e6b160_face.pt /content/drive/MyDrive/miga_features_cache_agcn/088f59f97642_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0908fd243ee3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/097537f5b986_face.pt /content/drive/MyDrive/miga_features_cache_agcn/09a4cc150f42_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0a096ee9e4a1_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0cae4d6d7f9c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0db8d3e98501_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0dc25751f019_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0dd6795a6dc0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0f2989c1a220_face.pt /content/drive/MyDrive/miga_features_cache_agcn/0f9b72cc21eb_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1018772cd839_face.pt /content/drive/MyDrive/miga_features_cache_agcn/108de304743f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/11646ef853d5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1262ccdf5117_face.pt /content/drive/MyDrive/miga_features_cache_agcn/13756240ecd1_face.pt /content/drive/MyDrive/miga_features_cache_agcn/13c5f3185145_face.pt /content/drive/MyDrive/miga_features_cache_agcn/15e9668db234_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1620ff2a4e19_face.pt /content/drive/MyDrive/miga_features_cache_agcn/17e047e91727_face.pt /content/drive/MyDrive/miga_features_cache_agcn/181fb208dd25_face.pt /content/drive/MyDrive/miga_features_cache_agcn/186cb628a00e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/19843783231b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1d4ede1331de_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1eae6962a63b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1f8aad2528dc_face.pt /content/drive/MyDrive/miga_features_cache_agcn/1fd4173fb471_face.pt /content/drive/MyDrive/miga_features_cache_agcn/201ede2caf26_face.pt /content/drive/MyDrive/miga_features_cache_agcn/209501eeb4a6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/221dfd7cebef_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2268ae4188f5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/22df7084383e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/239a3da840af_face.pt /content/drive/MyDrive/miga_features_cache_agcn/246c9b03d6f0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/252d6f4d416a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/255f7de773f8_face.pt /content/drive/MyDrive/miga_features_cache_agcn/27384aedf70d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2a7eecbafa56_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2ae8451ecf7c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2b10042d06ec_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2bacf5eaa39f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2e8718371d09_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2ea484cff01b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/2ed626e5ffd3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/30ac0539b4a4_face.pt /content/drive/MyDrive/miga_features_cache_agcn/31e7c5a602ca_face.pt /content/drive/MyDrive/miga_features_cache_agcn/322324881360_face.pt /content/drive/MyDrive/miga_features_cache_agcn/338be23bfe9a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/34c172f4f548_face.pt /content/drive/MyDrive/miga_features_cache_agcn/355330b3a745_face.pt /content/drive/MyDrive/miga_features_cache_agcn/36066a55360f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/39060ead04db_face.pt /content/drive/MyDrive/miga_features_cache_agcn/39fe9da25570_face.pt /content/drive/MyDrive/miga_features_cache_agcn/3c8a19f1a77f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/3dd68fd73380_face.pt /content/drive/MyDrive/miga_features_cache_agcn/3e960c17e92e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/3f362975f317_face.pt /content/drive/MyDrive/miga_features_cache_agcn/3f8c022aaee6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/41af1a5aaffe_face.pt /content/drive/MyDrive/miga_features_cache_agcn/41f09daf4463_face.pt /content/drive/MyDrive/miga_features_cache_agcn/420233bb0153_face.pt /content/drive/MyDrive/miga_features_cache_agcn/43c5f5d4c08f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/440c24c623d1_face.pt /content/drive/MyDrive/miga_features_cache_agcn/45f2cba4384d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/47f64f106476_face.pt /content/drive/MyDrive/miga_features_cache_agcn/48b10dbd49ea_face.pt /content/drive/MyDrive/miga_features_cache_agcn/4a4778763d48_face.pt /content/drive/MyDrive/miga_features_cache_agcn/4b30c36d5a25_face.pt /content/drive/MyDrive/miga_features_cache_agcn/4bcde5a82194_face.pt /content/drive/MyDrive/miga_features_cache_agcn/4ca8e56af321_face.pt /content/drive/MyDrive/miga_features_cache_agcn/513d88fe11db_face.pt /content/drive/MyDrive/miga_features_cache_agcn/530ab6cff714_face.pt /content/drive/MyDrive/miga_features_cache_agcn/532f2f26a7b3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/53a70417fdb7_face.pt /content/drive/MyDrive/miga_features_cache_agcn/578e25e98810_face.pt /content/drive/MyDrive/miga_features_cache_agcn/59c71581045f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/59f1a1cf0a2e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/5b8eba00fd84_face.pt /content/drive/MyDrive/miga_features_cache_agcn/5dd01777bad9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/5dec9937a35a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/5e6ad9aeee6c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/5f60788646aa_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6107dcd2b8db_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6225dffcf8c9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/633afcff2cac_face.pt /content/drive/MyDrive/miga_features_cache_agcn/634c417ee7a6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/64e8ed0acfa7_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6789660f21c3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/68a650f0bb38_face.pt /content/drive/MyDrive/miga_features_cache_agcn/69e068b4a055_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6a619c1e55b7_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6a7be86ff5a1_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6ad2587edec6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6afbeeeeb9db_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6b39551b10ed_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6bfeb4eefb06_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6ce872d5e39b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6d2f7cd0c56c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6d40cdb467e2_face.pt /content/drive/MyDrive/miga_features_cache_agcn/6e97a12d04e5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7074194cbadf_face.pt /content/drive/MyDrive/miga_features_cache_agcn/71c78f751e78_face.pt /content/drive/MyDrive/miga_features_cache_agcn/71d43e439939_face.pt /content/drive/MyDrive/miga_features_cache_agcn/721bee2d4bf2_face.pt /content/drive/MyDrive/miga_features_cache_agcn/72679ca2a7c1_face.pt /content/drive/MyDrive/miga_features_cache_agcn/72ce819af3f5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/73cc360c5976_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7410f44a80a0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/747dbc308fef_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7570191191d8_face.pt /content/drive/MyDrive/miga_features_cache_agcn/75c656b4afc2_face.pt /content/drive/MyDrive/miga_features_cache_agcn/76d64d1731fa_face.pt /content/drive/MyDrive/miga_features_cache_agcn/77f5e5625e93_face.pt /content/drive/MyDrive/miga_features_cache_agcn/782ff1188c9a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/78c469b55ea4_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7961205cec28_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7a4d3f7dddf0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7b4f62aeeda8_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7c20862a49a3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7c96a830913f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7de93a7e893f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/7e985501bd16_face.pt /content/drive/MyDrive/miga_features_cache_agcn/80b0cd5eec88_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8264c10dfaaf_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8330f28b0e36_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8341d4e5de0b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/84166a7963c0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/84844a54aef0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/84fa203c5d4c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/85915c3ddab5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/85e46c0ac09e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/869c78216f36_face.pt /content/drive/MyDrive/miga_features_cache_agcn/87031007b9c0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/870ffff332ff_face.pt /content/drive/MyDrive/miga_features_cache_agcn/873a07d8ed3b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8826bb56b47c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8ae7069778aa_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8d87517df5d4_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8dd5161305d9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8ebd6371c670_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8f19d2139c7a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/8ff0ddc359fd_face.pt /content/drive/MyDrive/miga_features_cache_agcn/90066b62470f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/90ffc2922e23_face.pt /content/drive/MyDrive/miga_features_cache_agcn/918e88d8abc1_face.pt /content/drive/MyDrive/miga_features_cache_agcn/943d3a758d2b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/95b05994091e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/96619b01229e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/9788e20aadfe_face.pt /content/drive/MyDrive/miga_features_cache_agcn/98f7fece2e41_face.pt /content/drive/MyDrive/miga_features_cache_agcn/993b0087a04a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/995a81c6fe26_face.pt /content/drive/MyDrive/miga_features_cache_agcn/996a670be739_face.pt /content/drive/MyDrive/miga_features_cache_agcn/9ca6fcf22282_face.pt /content/drive/MyDrive/miga_features_cache_agcn/9d56dfadd7d0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/9ef217cb48a9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/9f63e9fa3887_face.pt /content/drive/MyDrive/miga_features_cache_agcn/a07c31a5a305_face.pt /content/drive/MyDrive/miga_features_cache_agcn/a1dfee690987_face.pt /content/drive/MyDrive/miga_features_cache_agcn/a2e7f4b7d7a6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/a3a59a12efe6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/a826a158ebe0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/a8772324bb06_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ab04355a15a9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/abf023461e31_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ad8a195c26e0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/aecc066581e3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/af27e31fd2ff_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b1251a1fd26e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b27373f02956_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b2f54b00dda2_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b36a91a30103_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b3b0fdb1426a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b4a21e3b1d42_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b50e15067a77_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b7180660d049_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b7c0c5adddd6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b803c73db2f5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b8366f151998_face.pt /content/drive/MyDrive/miga_features_cache_agcn/b87e5c420569_face.pt /content/drive/MyDrive/miga_features_cache_agcn/bc604e11cd28_face.pt /content/drive/MyDrive/miga_features_cache_agcn/be6f549156a8_face.pt /content/drive/MyDrive/miga_features_cache_agcn/befa9fe7ec10_face.pt /content/drive/MyDrive/miga_features_cache_agcn/c1a60588a819_face.pt /content/drive/MyDrive/miga_features_cache_agcn/c2dfdd55bb77_face.pt /content/drive/MyDrive/miga_features_cache_agcn/c38ff05f1cb9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/c40273ffad59_face.pt /content/drive/MyDrive/miga_features_cache_agcn/c538ff5af2fc_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ca250e19a593_face.pt /content/drive/MyDrive/miga_features_cache_agcn/cac3c88764f6_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ce6aad694dcc_face.pt /content/drive/MyDrive/miga_features_cache_agcn/cfe1d32f286d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/cffef16acdb3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/d04f3fe7aae0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/d25ad6b652f9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/d43a5a46819c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/d5226a19cc4d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/d76fec6d157b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/d8b71e097390_face.pt /content/drive/MyDrive/miga_features_cache_agcn/dac73e3f6772_face.pt /content/drive/MyDrive/miga_features_cache_agcn/db57a768e402_face.pt /content/drive/MyDrive/miga_features_cache_agcn/dbc7add1be13_face.pt /content/drive/MyDrive/miga_features_cache_agcn/dca1f75d184d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/dd0e23932d2d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ddc36aafbe05_face.pt /content/drive/MyDrive/miga_features_cache_agcn/de935844c489_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ded8ad49fb4c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/dff90c7db1a5_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e06a6125b4e0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e19f7ae86079_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e1adc4e5fdfb_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e3804ad76f56_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e3a17c0701de_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e53fbeb7872c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e56facbbec94_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e704f197f883_face.pt /content/drive/MyDrive/miga_features_cache_agcn/e86c65a2ad2a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ea96b83905a8_face.pt /content/drive/MyDrive/miga_features_cache_agcn/eaf780e7913f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/eb6131cde7d8_face.pt /content/drive/MyDrive/miga_features_cache_agcn/eb623bd6229b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ebaaadd6489e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ec2a894eb09e_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ec2e6984eb7a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ecaad627cf65_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ecc0d5a08ec9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ed5e79afe62a_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ee71bbfa1f73_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f06014a5588d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f094214631d9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f1bca4fd3891_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f2fb190167f0_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f3127395d63c_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f32bb17682fd_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f3625dd8126d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f49286e2ca84_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f59b28bb72fe_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f68588ab68bb_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f6da49ba7687_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f8fa67c44485_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f8fc3aa00f3f_face.pt /content/drive/MyDrive/miga_features_cache_agcn/f99c8748866d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/fa6c7f5ece5d_face.pt /content/drive/MyDrive/miga_features_cache_agcn/faade2189271_face.pt /content/drive/MyDrive/miga_features_cache_agcn/fbf0e0e763d9_face.pt /content/drive/MyDrive/miga_features_cache_agcn/fc4764de32f3_face.pt /content/drive/MyDrive/miga_features_cache_agcn/fe2cce3f720b_face.pt /content/drive/MyDrive/miga_features_cache_agcn/ff7690117ecc_face.pt /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d/
+ true

**FACE Variant 0: yolo+mid**

In [14]:
%%bash
export FACE_SAMPLING=mid
export FACE_DETECT=yolo

CHUNK=32
SHARD=5
DEVICE=cuda
CSV=/content/phase1_all_with_split.csv
BASE_FEAT_DIR=/content/drive/MyDrive/miga_features_cache_agcn
EXP_NAME=baseline_face
FEAT_DIR=${BASE_FEAT_DIR}/${EXP_NAME}

mkdir -p "$FEAT_DIR"

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase1_all_with_split.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD))
  if [ $END -gt $TOTAL ]; then END=$TOTAL; fi

  echo "=== FACE baseline (mid + yolo) shard $START:$END ==="
  PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 python -u /content/src/cache_features_cli.py \
    --csv $CSV --phase 1 --feat_dir "$FEAT_DIR" \
    --chunk $CHUNK --start $START --end $END --device $DEVICE \
    --do_face

  START=$END
done

=== FACE baseline (mid + yolo) shard 0:5 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n.pt to 'yolov8n.pt'...
Downloading enet_b0_8_best_vgaf.pt from https://github.com/sb-ai-lab/EmotiEffLib/blob/main/models/affectnet_emotions/enet_b0_8_best_vgaf.pt?raw=true

DONE shard [0:5) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 5:10 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [5:10) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 10:15 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [10:15) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 15:20 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [15:20) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 20:25 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [20:25) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 25:30 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [25:30) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 30:35 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [30:35) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 35:40 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [35:40) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 40:45 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [40:45) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 45:50 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [45:50) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 50:55 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [50:55) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 55:60 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [55:60) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 60:65 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [60:65) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 65:70 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [65:70) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 70:75 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [70:75) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 75:80 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [75:80) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 80:85 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [80:85) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 85:90 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [85:90) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 90:95 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [90:95) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 95:100 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [95:100) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 100:105 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [100:105) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 105:110 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [105:110) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 110:115 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [110:115) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 115:120 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [115:120) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 120:125 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [120:125) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 125:130 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [125:130) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 130:135 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [130:135) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 135:140 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [135:140) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 140:145 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [140:145) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 145:150 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [145:150) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 150:155 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [150:155) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 155:160 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [155:160) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 160:165 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [160:165) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 165:170 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [165:170) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 170:175 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [170:175) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 175:180 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [175:180) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 180:185 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [180:185) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 185:190 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [185:190) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 190:195 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [190:195) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 195:200 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [195:200) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 200:205 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [200:205) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 205:210 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [205:210) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 210:215 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [210:215) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 215:220 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [215:220) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 220:225 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [220:225) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 225:230 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [225:230) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 230:235 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [230:235) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 235:240 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [235:240) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 240:245 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [240:245) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 245:250 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [245:250) ok=5 bad=0
=== FACE baseline (mid + yolo) shard 250:255 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [250:255) ok=5 bad=0

  0%|          | 0/5 [00:00<?, ?it/s]
100%|██████████| 6.25M/6.25M [00:00<00:00, 229MB/s]
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771250346.958308   15763 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771250346.966526   15763 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771250346.989259   15763 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250346.989294   15763 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250346.989297   15763 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250346.989299   15763 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:15<00:00, 15.10s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771250426.703696   16891 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771250426.711440   16891 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771250426.732772   16891 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250426.732800   16891 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250426.732803   16891 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250426.732805   16891 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 20%|██        | 1/5 [00:26<01:45, 26.35s/it][h264 @ 0x2971f980] mmco: unref short failure
[h264 @ 0x2971f980] mmco: unref short failure
100%|██████████| 5/5 [00:58<00:00, 11.63s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771250489.446678   17771 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771250489.454822   17771 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771250489.480454   17771 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250489.480496   17771 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250489.480501   17771 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250489.480504   17771 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:05<00:00, 13.11s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771250559.381986   18762 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771250559.389934   18762 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771250559.411794   18762 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250559.411831   18762 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250559.411833   18762 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250559.411835   18762 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 20%|██        | 1/5 [00:21<01:25, 21.39s/it][h264 @ 0x3aa03980] mmco: unref short failure
 80%|████████  | 4/5 [00:56<00:11, 11.62s/it][h264 @ 0x3a8cd440] mmco: unref short failure
100%|██████████| 5/5 [01:05<00:00, 13.11s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771250629.510974   19785 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771250629.518573   19785 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771250629.539524   19785 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250629.539560   19785 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250629.539563   19785 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250629.539566   19785 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[h264 @ 0x3705da80] mmco: unref short failure
[h264 @ 0x3705da80] mmco: unref short failure
 80%|████████  | 4/5 [00:58<00:11, 11.04s/it][h264 @ 0x371be480] mmco: unref short failure
100%|██████████| 5/5 [01:04<00:00, 12.91s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771250698.560204   20800 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771250698.568158   20800 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771250698.589180   20800 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250698.589215   20800 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250698.589217   20800 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250698.589219   20800 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 80%|████████  | 4/5 [01:04<00:14, 14.40s/it][h264 @ 0x1480e7c0] mmco: unref short failure
100%|██████████| 5/5 [01:14<00:00, 14.83s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771250777.291827   21935 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771250777.299655   21935 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771250777.320949   21935 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250777.320978   21935 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250777.320980   21935 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250777.320982   21935 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:00<00:00, 12.05s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771250841.874169   22866 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771250841.881661   22866 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771250841.901737   22866 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250841.901763   22866 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250841.901765   22866 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250841.901767   22866 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 40%|████      | 2/5 [00:32<00:48, 16.03s/it][h264 @ 0x32ef10c0] mmco: unref short failure
100%|██████████| 5/5 [00:50<00:00, 10.20s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771250897.060305   23651 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771250897.067866   23651 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771250897.087791   23651 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250897.087816   23651 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250897.087820   23651 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250897.087822   23651 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 20%|██        | 1/5 [00:18<01:13, 18.39s/it][h264 @ 0x34466100] mmco: unref short failure
100%|██████████| 5/5 [01:07<00:00, 13.50s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771250969.394331   24697 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771250969.402316   24697 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771250969.426423   24697 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250969.426467   24697 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250969.426469   24697 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771250969.426471   24697 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:53<00:00, 22.80s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771251087.470353   26675 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771251087.477988   26675 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771251087.499129   26675 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251087.499164   26675 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251087.499167   26675 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251087.499168   26675 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[h264 @ 0x34d62f80] mmco: unref short failure
[h264 @ 0x34d62f80] mmco: unref short failure
100%|██████████| 5/5 [01:30<00:00, 18.08s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771251182.509024   28094 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771251182.517847   28094 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771251182.539115   28094 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251182.539155   28094 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251182.539158   28094 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251182.539160   28094 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:30<00:00, 18.01s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771251277.276326   29519 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771251277.284101   29519 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771251277.306450   29519 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251277.306485   29519 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251277.306488   29519 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251277.306489   29519 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 20%|██        | 1/5 [00:23<01:33, 23.32s/it][h264 @ 0x10799fc0] mmco: unref short failure
100%|██████████| 5/5 [00:53<00:00, 10.63s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771251335.094408   30315 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771251335.102122   30315 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771251335.123467   30315 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251335.123499   30315 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251335.123502   30315 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251335.123504   30315 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:23<00:00, 16.71s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771251423.103538   31620 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771251423.111182   31620 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771251423.131840   31620 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251423.131872   31620 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251423.131874   31620 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771251423.131876   31620 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:56<00:00, 23.35s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771251544.544724   33467 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771251544.552336   33467 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

**FACE Variant 1: exp_face_3frames_avg**

In [ ]:
%%bash
set -euxo pipefail
CSV=/content/phase1_all_with_split.csv
BASE_DIR=/content/drive/MyDrive/miga_features_cache_agcn
EXP_DIR=/content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg

mkdir -p "$EXP_DIR"
ln -sfn "$BASE_DIR"/*_ctx.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_skel.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_skelmask.pt "$EXP_DIR"/ 2>/dev/null || true

DEVICE=cuda
CHUNK=32
SHARD=5
export PYTHONUNBUFFERED=1

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase1_all_with_split.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD)); if [ $END -gt $TOTAL ]; then END=$TOTAL; fi
  echo "=== FACE 3frames_avg shard $START:$END ==="
  time env FACE_SAMPLING=3frames_avg PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 \
    python -u /content/src/cache_features_cli.py \
      --csv "$CSV" --phase 1 --feat_dir "$EXP_DIR" \
      --chunk "$CHUNK" --start "$START" --end "$END" --device "$DEVICE" \
      --do_face
  START=$END
done

=== FACE 3frames_avg shard 0:5 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n.pt to 'yolov8n.pt'...
Downloading enet_b0_8_best_vgaf.pt from https://github.com/sb-ai-lab/EmotiEffLib/blob/main/models/affectnet_emotions/enet_b0_8_best_vgaf.pt?raw=true

DONE shard [0:5) ok=5 bad=0
=== FACE 3frames_avg shard 5:10 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [5:10) ok=5 bad=0
=== FACE 3frames_avg shard 10:15 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [10:15) ok=5 bad=0
=== FACE 3frames_avg shard 15:20 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [15:20) ok=5 bad=0
=== FACE 3frames_avg shard 20:25 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [20:25) ok=5 bad=0
=== FACE 3frames_avg shard 25:30 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [25:30) ok=5 bad=0
=== FACE 3frames_avg shard 30:35 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [30:35) ok=5 bad=0
=== FACE 3frames_avg shard 35:40 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [35:40) ok=5 bad=0
=== FACE 3frames_avg shard 40:45 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [40:45) ok=5 bad=0
=== FACE 3frames_avg shard 45:50 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [45:50) ok=5 bad=0
=== FACE 3frames_avg shard 50:55 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [50:55) ok=5 bad=0
=== FACE 3frames_avg shard 55:60 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [55:60) ok=5 bad=0
=== FACE 3frames_avg shard 60:65 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [60:65) ok=5 bad=0
=== FACE 3frames_avg shard 65:70 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [65:70) ok=5 bad=0
=== FACE 3frames_avg shard 70:75 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [70:75) ok=5 bad=0
=== FACE 3frames_avg shard 75:80 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [75:80) ok=5 bad=0
=== FACE 3frames_avg shard 80:85 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [80:85) ok=5 bad=0
=== FACE 3frames_avg shard 85:90 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [85:90) ok=5 bad=0
=== FACE 3frames_avg shard 90:95 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [90:95) ok=5 bad=0
=== FACE 3frames_avg shard 95:100 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [95:100) ok=5 bad=0
=== FACE 3frames_avg shard 100:105 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [100:105) ok=5 bad=0
=== FACE 3frames_avg shard 105:110 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [105:110) ok=5 bad=0
=== FACE 3frames_avg shard 110:115 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [110:115) ok=5 bad=0
=== FACE 3frames_avg shard 115:120 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [115:120) ok=5 bad=0
=== FACE 3frames_avg shard 120:125 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [120:125) ok=5 bad=0
=== FACE 3frames_avg shard 125:130 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [125:130) ok=5 bad=0
=== FACE 3frames_avg shard 130:135 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [130:135) ok=5 bad=0
=== FACE 3frames_avg shard 135:140 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [135:140) ok=5 bad=0
=== FACE 3frames_avg shard 140:145 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [140:145) ok=5 bad=0
=== FACE 3frames_avg shard 145:150 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [145:150) ok=5 bad=0
=== FACE 3frames_avg shard 150:155 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [150:155) ok=5 bad=0
=== FACE 3frames_avg shard 155:160 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [155:160) ok=5 bad=0
=== FACE 3frames_avg shard 160:165 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [160:165) ok=5 bad=0
=== FACE 3frames_avg shard 165:170 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [165:170) ok=5 bad=0
=== FACE 3frames_avg shard 170:175 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [170:175) ok=5 bad=0
=== FACE 3frames_avg shard 175:180 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [175:180) ok=5 bad=0
=== FACE 3frames_avg shard 180:185 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [180:185) ok=5 bad=0
=== FACE 3frames_avg shard 185:190 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [185:190) ok=5 bad=0
=== FACE 3frames_avg shard 190:195 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [190:195) ok=5 bad=0
=== FACE 3frames_avg shard 195:200 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [195:200) ok=5 bad=0
=== FACE 3frames_avg shard 200:205 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [200:205) ok=5 bad=0
=== FACE 3frames_avg shard 205:210 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [205:210) ok=5 bad=0
=== FACE 3frames_avg shard 210:215 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [210:215) ok=5 bad=0
=== FACE 3frames_avg shard 215:220 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [215:220) ok=5 bad=0
=== FACE 3frames_avg shard 220:225 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [220:225) ok=5 bad=0
=== FACE 3frames_avg shard 225:230 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [225:230) ok=5 bad=0
=== FACE 3frames_avg shard 230:235 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [230:235) ok=5 bad=0
=== FACE 3frames_avg shard 235:240 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [235:240) ok=5 bad=0
=== FACE 3frames_avg shard 240:245 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [240:245) ok=5 bad=0
=== FACE 3frames_avg shard 245:250 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [245:250) ok=5 bad=0
=== FACE 3frames_avg shard 250:255 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
MODES: ctx= False face= True skel= False

DONE shard [250:255) ok=5 bad=0

+ CSV=/content/phase1_all_with_split.csv
+ BASE_DIR=/content/drive/MyDrive/miga_features_cache_agcn
+ EXP_DIR=/content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
+ mkdir -p /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
+ ln -sfn /content/drive/MyDrive/miga_features_cache_agcn/00a3ed33d38e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/00b40a2e4d97_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/01087f1b2489_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0123fc67d163_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/017fc7925072_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/01b372587e0a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/01dc5000e304_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/03ae04661248_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/049e754be9f7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/04c0dc00860f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/05b600b0301d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/06a239e6b160_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/088f59f97642_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0908fd243ee3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/097537f5b986_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/09a4cc150f42_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0a096ee9e4a1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0cae4d6d7f9c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0db8d3e98501_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0dc25751f019_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0dd6795a6dc0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0f2989c1a220_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0f9b72cc21eb_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1018772cd839_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/108de304743f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/11646ef853d5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1262ccdf5117_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/13756240ecd1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/13c5f3185145_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/15e9668db234_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1620ff2a4e19_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/17e047e91727_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/181fb208dd25_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/186cb628a00e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/19843783231b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1d4ede1331de_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1eae6962a63b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1f8aad2528dc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1fd4173fb471_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/201ede2caf26_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/209501eeb4a6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/221dfd7cebef_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2268ae4188f5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/22df7084383e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/239a3da840af_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/246c9b03d6f0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/252d6f4d416a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/255f7de773f8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/27384aedf70d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2a7eecbafa56_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2ae8451ecf7c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2b10042d06ec_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2bacf5eaa39f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2e8718371d09_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2ea484cff01b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2ed626e5ffd3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/30ac0539b4a4_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/31e7c5a602ca_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/322324881360_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/338be23bfe9a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/34c172f4f548_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/355330b3a745_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/36066a55360f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/39060ead04db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/39fe9da25570_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3c8a19f1a77f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3dd68fd73380_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3e960c17e92e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3f362975f317_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3f8c022aaee6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/41af1a5aaffe_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/41f09daf4463_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/420233bb0153_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/43c5f5d4c08f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/440c24c623d1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/45f2cba4384d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/47f64f106476_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/48b10dbd49ea_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4a4778763d48_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4b30c36d5a25_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4bcde5a82194_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4ca8e56af321_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/513d88fe11db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/530ab6cff714_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/532f2f26a7b3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/53a70417fdb7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/578e25e98810_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/59c71581045f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/59f1a1cf0a2e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5b8eba00fd84_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5dd01777bad9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5dec9937a35a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5e6ad9aeee6c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5f60788646aa_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6107dcd2b8db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6225dffcf8c9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/633afcff2cac_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/634c417ee7a6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/64e8ed0acfa7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6789660f21c3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/68a650f0bb38_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/69e068b4a055_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6a619c1e55b7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6a7be86ff5a1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6ad2587edec6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6afbeeeeb9db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6b39551b10ed_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6bfeb4eefb06_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6ce872d5e39b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6d2f7cd0c56c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6d40cdb467e2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6e97a12d04e5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7074194cbadf_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/71c78f751e78_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/71d43e439939_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/721bee2d4bf2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/72679ca2a7c1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/72ce819af3f5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/73cc360c5976_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7410f44a80a0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/747dbc308fef_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7570191191d8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/75c656b4afc2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/76d64d1731fa_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/77f5e5625e93_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/782ff1188c9a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/78c469b55ea4_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7961205cec28_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7a4d3f7dddf0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7b4f62aeeda8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7c20862a49a3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7c96a830913f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7de93a7e893f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7e985501bd16_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/80b0cd5eec88_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8264c10dfaaf_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8330f28b0e36_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8341d4e5de0b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/84166a7963c0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/84844a54aef0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/84fa203c5d4c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/85915c3ddab5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/85e46c0ac09e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/869c78216f36_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/87031007b9c0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/870ffff332ff_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/873a07d8ed3b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8826bb56b47c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8ae7069778aa_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8d87517df5d4_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8dd5161305d9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8ebd6371c670_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8f19d2139c7a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8ff0ddc359fd_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/90066b62470f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/90ffc2922e23_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/918e88d8abc1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/943d3a758d2b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/95b05994091e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/96619b01229e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9788e20aadfe_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/98f7fece2e41_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/993b0087a04a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/995a81c6fe26_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/996a670be739_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9ca6fcf22282_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9d56dfadd7d0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9ef217cb48a9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9f63e9fa3887_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a07c31a5a305_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a1dfee690987_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a2e7f4b7d7a6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a3a59a12efe6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a826a158ebe0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a8772324bb06_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ab04355a15a9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/abf023461e31_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ad8a195c26e0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/aecc066581e3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/af27e31fd2ff_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b1251a1fd26e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b27373f02956_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b2f54b00dda2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b36a91a30103_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b3b0fdb1426a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b4a21e3b1d42_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b50e15067a77_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b7180660d049_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b7c0c5adddd6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b803c73db2f5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b8366f151998_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b87e5c420569_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/bc604e11cd28_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/be6f549156a8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/befa9fe7ec10_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c1a60588a819_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c2dfdd55bb77_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c38ff05f1cb9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c40273ffad59_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c538ff5af2fc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ca250e19a593_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/cac3c88764f6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ce6aad694dcc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/cfe1d32f286d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/cffef16acdb3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d04f3fe7aae0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d25ad6b652f9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d43a5a46819c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d5226a19cc4d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d76fec6d157b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d8b71e097390_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dac73e3f6772_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/db57a768e402_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dbc7add1be13_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dca1f75d184d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dd0e23932d2d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ddc36aafbe05_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/de935844c489_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ded8ad49fb4c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dff90c7db1a5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e06a6125b4e0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e19f7ae86079_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e1adc4e5fdfb_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e3804ad76f56_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e3a17c0701de_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e53fbeb7872c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e56facbbec94_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e704f197f883_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e86c65a2ad2a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ea96b83905a8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/eaf780e7913f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/eb6131cde7d8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/eb623bd6229b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ebaaadd6489e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ec2a894eb09e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ec2e6984eb7a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ecaad627cf65_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ecc0d5a08ec9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ed5e79afe62a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ee71bbfa1f73_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f06014a5588d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f094214631d9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f1bca4fd3891_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f2fb190167f0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f3127395d63c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f32bb17682fd_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f3625dd8126d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f49286e2ca84_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f59b28bb72fe_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f68588ab68bb_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f6da49ba7687_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f8fa67c44485_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f8fc3aa00f3f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f99c8748866d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fa6c7f5ece5d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/faade2189271_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fbf0e0e763d9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fc4764de32f3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fe2cce3f720b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ff7690117ecc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg/
+ true

**FACE Variant 2: exp_face_centercrop_fast**

In [ ]:
%%bash
set -euxo pipefail
CSV=/content/phase1_all_with_split.csv
BASE_DIR=/content/drive/MyDrive/miga_features_cache_agcn
EXP_DIR=/content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast

mkdir -p "$EXP_DIR"
ln -sfn "$BASE_DIR"/*_ctx.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_skel.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_skelmask.pt "$EXP_DIR"/ 2>/dev/null || true

DEVICE=cuda
CHUNK=32
SHARD=10
export PYTHONUNBUFFERED=1

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase1_all_with_split.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD)); if [ $END -gt $TOTAL ]; then END=$TOTAL; fi
  echo "=== FACE center-crop shard $START:$END ==="
  time env FACE_DETECT=center PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 \
    python -u /content/src/cache_features_cli.py \
      --csv "$CSV" --phase 1 --feat_dir "$EXP_DIR" \
      --chunk "$CHUNK" --start "$START" --end "$END" --device "$DEVICE" \
      --do_face
  START=$END
done

=== FACE center-crop shard 0:10 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [0:10) ok=10 bad=0
=== FACE center-crop shard 10:20 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [10:20) ok=10 bad=0
=== FACE center-crop shard 20:30 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [20:30) ok=10 bad=0
=== FACE center-crop shard 30:40 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [30:40) ok=10 bad=0
=== FACE center-crop shard 40:50 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [40:50) ok=10 bad=0
=== FACE center-crop shard 50:60 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [50:60) ok=10 bad=0
=== FACE center-crop shard 60:70 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [60:70) ok=10 bad=0
=== FACE center-crop shard 70:80 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [70:80) ok=10 bad=0
=== FACE center-crop shard 80:90 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [80:90) ok=10 bad=0
=== FACE center-crop shard 90:100 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [90:100) ok=10 bad=0
=== FACE center-crop shard 100:110 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [100:110) ok=10 bad=0
=== FACE center-crop shard 110:120 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [110:120) ok=10 bad=0
=== FACE center-crop shard 120:130 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [120:130) ok=10 bad=0
=== FACE center-crop shard 130:140 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [130:140) ok=10 bad=0
=== FACE center-crop shard 140:150 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [140:150) ok=10 bad=0
=== FACE center-crop shard 150:160 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [150:160) ok=10 bad=0
=== FACE center-crop shard 160:170 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [160:170) ok=10 bad=0
=== FACE center-crop shard 170:180 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [170:180) ok=10 bad=0
=== FACE center-crop shard 180:190 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [180:190) ok=10 bad=0
=== FACE center-crop shard 190:200 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [190:200) ok=10 bad=0
=== FACE center-crop shard 200:210 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [200:210) ok=10 bad=0
=== FACE center-crop shard 210:220 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [210:220) ok=10 bad=0
=== FACE center-crop shard 220:230 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [220:230) ok=10 bad=0
=== FACE center-crop shard 230:240 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [230:240) ok=10 bad=0
=== FACE center-crop shard 240:250 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [240:250) ok=10 bad=0
=== FACE center-crop shard 250:255 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
MODES: ctx= False face= True skel= False

DONE shard [250:255) ok=5 bad=0

+ CSV=/content/phase1_all_with_split.csv
+ BASE_DIR=/content/drive/MyDrive/miga_features_cache_agcn
+ EXP_DIR=/content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
+ mkdir -p /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
+ ln -sfn /content/drive/MyDrive/miga_features_cache_agcn/00a3ed33d38e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/00b40a2e4d97_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/01087f1b2489_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0123fc67d163_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/017fc7925072_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/01b372587e0a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/01dc5000e304_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/03ae04661248_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/049e754be9f7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/04c0dc00860f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/05b600b0301d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/06a239e6b160_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/088f59f97642_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0908fd243ee3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/097537f5b986_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/09a4cc150f42_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0a096ee9e4a1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0cae4d6d7f9c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0db8d3e98501_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0dc25751f019_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0dd6795a6dc0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0f2989c1a220_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0f9b72cc21eb_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1018772cd839_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/108de304743f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/11646ef853d5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1262ccdf5117_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/13756240ecd1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/13c5f3185145_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/15e9668db234_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1620ff2a4e19_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/17e047e91727_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/181fb208dd25_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/186cb628a00e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/19843783231b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1d4ede1331de_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1eae6962a63b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1f8aad2528dc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1fd4173fb471_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/201ede2caf26_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/209501eeb4a6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/221dfd7cebef_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2268ae4188f5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/22df7084383e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/239a3da840af_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/246c9b03d6f0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/252d6f4d416a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/255f7de773f8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/27384aedf70d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2a7eecbafa56_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2ae8451ecf7c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2b10042d06ec_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2bacf5eaa39f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2e8718371d09_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2ea484cff01b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2ed626e5ffd3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/30ac0539b4a4_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/31e7c5a602ca_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/322324881360_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/338be23bfe9a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/34c172f4f548_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/355330b3a745_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/36066a55360f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/39060ead04db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/39fe9da25570_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3c8a19f1a77f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3dd68fd73380_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3e960c17e92e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3f362975f317_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3f8c022aaee6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/41af1a5aaffe_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/41f09daf4463_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/420233bb0153_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/43c5f5d4c08f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/440c24c623d1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/45f2cba4384d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/47f64f106476_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/48b10dbd49ea_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4a4778763d48_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4b30c36d5a25_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4bcde5a82194_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4ca8e56af321_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/513d88fe11db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/530ab6cff714_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/532f2f26a7b3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/53a70417fdb7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/578e25e98810_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/59c71581045f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/59f1a1cf0a2e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5b8eba00fd84_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5dd01777bad9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5dec9937a35a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5e6ad9aeee6c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5f60788646aa_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6107dcd2b8db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6225dffcf8c9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/633afcff2cac_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/634c417ee7a6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/64e8ed0acfa7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6789660f21c3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/68a650f0bb38_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/69e068b4a055_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6a619c1e55b7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6a7be86ff5a1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6ad2587edec6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6afbeeeeb9db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6b39551b10ed_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6bfeb4eefb06_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6ce872d5e39b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6d2f7cd0c56c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6d40cdb467e2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6e97a12d04e5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7074194cbadf_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/71c78f751e78_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/71d43e439939_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/721bee2d4bf2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/72679ca2a7c1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/72ce819af3f5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/73cc360c5976_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7410f44a80a0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/747dbc308fef_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7570191191d8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/75c656b4afc2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/76d64d1731fa_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/77f5e5625e93_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/782ff1188c9a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/78c469b55ea4_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7961205cec28_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7a4d3f7dddf0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7b4f62aeeda8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7c20862a49a3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7c96a830913f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7de93a7e893f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7e985501bd16_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/80b0cd5eec88_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8264c10dfaaf_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8330f28b0e36_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8341d4e5de0b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/84166a7963c0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/84844a54aef0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/84fa203c5d4c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/85915c3ddab5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/85e46c0ac09e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/869c78216f36_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/87031007b9c0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/870ffff332ff_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/873a07d8ed3b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8826bb56b47c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8ae7069778aa_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8d87517df5d4_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8dd5161305d9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8ebd6371c670_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8f19d2139c7a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8ff0ddc359fd_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/90066b62470f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/90ffc2922e23_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/918e88d8abc1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/943d3a758d2b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/95b05994091e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/96619b01229e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9788e20aadfe_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/98f7fece2e41_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/993b0087a04a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/995a81c6fe26_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/996a670be739_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9ca6fcf22282_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9d56dfadd7d0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9ef217cb48a9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9f63e9fa3887_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a07c31a5a305_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a1dfee690987_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a2e7f4b7d7a6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a3a59a12efe6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a826a158ebe0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a8772324bb06_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ab04355a15a9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/abf023461e31_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ad8a195c26e0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/aecc066581e3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/af27e31fd2ff_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b1251a1fd26e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b27373f02956_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b2f54b00dda2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b36a91a30103_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b3b0fdb1426a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b4a21e3b1d42_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b50e15067a77_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b7180660d049_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b7c0c5adddd6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b803c73db2f5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b8366f151998_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b87e5c420569_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/bc604e11cd28_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/be6f549156a8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/befa9fe7ec10_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c1a60588a819_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c2dfdd55bb77_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c38ff05f1cb9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c40273ffad59_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c538ff5af2fc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ca250e19a593_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/cac3c88764f6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ce6aad694dcc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/cfe1d32f286d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/cffef16acdb3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d04f3fe7aae0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d25ad6b652f9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d43a5a46819c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d5226a19cc4d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d76fec6d157b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d8b71e097390_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dac73e3f6772_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/db57a768e402_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dbc7add1be13_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dca1f75d184d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dd0e23932d2d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ddc36aafbe05_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/de935844c489_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ded8ad49fb4c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dff90c7db1a5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e06a6125b4e0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e19f7ae86079_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e1adc4e5fdfb_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e3804ad76f56_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e3a17c0701de_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e53fbeb7872c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e56facbbec94_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e704f197f883_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e86c65a2ad2a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ea96b83905a8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/eaf780e7913f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/eb6131cde7d8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/eb623bd6229b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ebaaadd6489e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ec2a894eb09e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ec2e6984eb7a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ecaad627cf65_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ecc0d5a08ec9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ed5e79afe62a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ee71bbfa1f73_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f06014a5588d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f094214631d9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f1bca4fd3891_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f2fb190167f0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f3127395d63c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f32bb17682fd_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f3625dd8126d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f49286e2ca84_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f59b28bb72fe_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f68588ab68bb_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f6da49ba7687_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f8fa67c44485_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f8fc3aa00f3f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f99c8748866d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fa6c7f5ece5d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/faade2189271_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fbf0e0e763d9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fc4764de32f3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fe2cce3f720b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ff7690117ecc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast/
+ true

**SKEL Variant 0: mean**

In [15]:
%%bash
export SKEL_AGG=mean

CHUNK=32
SHARD=10
DEVICE=cpu
CSV=/content/phase1_all_with_split.csv
BASE_FEAT_DIR=/content/drive/MyDrive/miga_features_cache_agcn
EXP_NAME=baseline_skel
FEAT_DIR=${BASE_FEAT_DIR}/${EXP_NAME}

mkdir -p "$FEAT_DIR"

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase1_all_with_split.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD))
  if [ $END -gt $TOTAL ]; then END=$TOTAL; fi

  echo "=== SKEL baseline (mean) shard $START:$END ==="
  PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 python -u /content/src/cache_features_cli.py \
    --csv $CSV --phase 1 --feat_dir "$FEAT_DIR" \
    --chunk $CHUNK --start $START --end $END --device $DEVICE \
    --do_skel

  START=$END
done

=== SKEL baseline (mean) shard 0:10 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [0:10) ok=10 bad=0
=== SKEL baseline (mean) shard 10:20 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [10:20) ok=10 bad=0
=== SKEL baseline (mean) shard 20:30 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [20:30) ok=10 bad=0
=== SKEL baseline (mean) shard 30:40 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [30:40) ok=10 bad=0
=== SKEL baseline (mean) shard 40:50 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [40:50) ok=10 bad=0
=== SKEL baseline (mean) shard 50:60 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [50:60) ok=10 bad=0
=== SKEL baseline (mean) shard 60:70 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [60:70) ok=10 bad=0
=== SKEL baseline (mean) shard 70:80 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [70:80) ok=10 bad=0
=== SKEL baseline (mean) shard 80:90 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [80:90) ok=10 bad=0
=== SKEL baseline (mean) shard 90:100 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True
 ERROR
row: 6 video_id: 319 split: train
skeleton_path: nan

DONE shard [90:100) ok=9 bad=1
=== SKEL baseline (mean) shard 100:110 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True
 ERROR
row: 2 video_id: 348 split: train
skeleton_path: nan

DONE shard [100:110) ok=9 bad=1
=== SKEL baseline (mean) shard 110:120 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [110:120) ok=10 bad=0
=== SKEL baseline (mean) shard 120:130 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [120:130) ok=10 bad=0
=== SKEL baseline (mean) shard 130:140 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [130:140) ok=10 bad=0
=== SKEL baseline (mean) shard 140:150 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [140:150) ok=10 bad=0
=== SKEL baseline (mean) shard 150:160 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True
 ERROR
row: 2 video_id: 347 split: train
skeleton_path: nan

DONE shard [150:160) ok=9 bad=1
=== SKEL baseline (mean) shard 160:170 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True
 ERROR
row: 7 video_id: 218 split: train
skeleton_path: nan

DONE shard [160:170) ok=9 bad=1
=== SKEL baseline (mean) shard 170:180 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [170:180) ok=10 bad=0
=== SKEL baseline (mean) shard 180:190 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [180:190) ok=10 bad=0
=== SKEL baseline (mean) shard 190:200 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [190:200) ok=10 bad=0
=== SKEL baseline (mean) shard 200:210 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [200:210) ok=10 bad=0
=== SKEL baseline (mean) shard 210:220 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [210:220) ok=10 bad=0
=== SKEL baseline (mean) shard 220:230 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [220:230) ok=10 bad=0
=== SKEL baseline (mean) shard 230:240 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [230:240) ok=10 bad=0
=== SKEL baseline (mean) shard 240:250 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [240:250) ok=10 bad=0
=== SKEL baseline (mean) shard 250:255 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
MODES: ctx= False face= False skel= True

DONE shard [250:255) ok=5 bad=0

100%|██████████| 10/10 [00:01<00:00,  5.74it/s]
100%|██████████| 10/10 [00:01<00:00,  5.99it/s]
100%|██████████| 10/10 [00:01<00:00,  5.53it/s]
100%|██████████| 10/10 [00:01<00:00,  7.60it/s]
100%|██████████| 10/10 [00:02<00:00,  3.76it/s]
100%|██████████| 10/10 [00:02<00:00,  4.14it/s]
100%|██████████| 10/10 [00:01<00:00,  5.97it/s]
100%|██████████| 10/10 [00:02<00:00,  3.79it/s]
100%|██████████| 10/10 [00:01<00:00,  5.60it/s]
 60%|██████    | 6/10 [00:00<00:00,  7.83it/s]Traceback (most recent call last):
  File "/content/src/cache_features_cli.py", line 46, in main
    build_and_cache_one(
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/content/src/feature_extract.py", line 431, in build_and_cache_one
    if spath is None or (not os.path.exists(spath)):
                             ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not float
100%|██████████| 10/10 [00:01<00:00,  9.11it/s]
 20%|██        | 2/10 [00:00<00:02,  4.00it/s]Traceback (most recent call last):
  File "/content/src/cache_features_cli.py", line 46, in main
    build_and_cache_one(
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/content/src/feature_extract.py", line 431, in build_and_cache_one
    if spath is None or (not os.path.exists(spath)):
                             ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not float
100%|██████████| 10/10 [00:01<00:00,  6.44it/s]
100%|██████████| 10/10 [00:02<00:00,  4.47it/s]
100%|██████████| 10/10 [00:02<00:00,  4.35it/s]
100%|██████████| 10/10 [00:02<00:00,  4.00it/s]
100%|██████████| 10/10 [00:01<00:00,  5.90it/s]
 20%|██        | 2/10 [00:00<00:03,  2.59it/s]Traceback (most recent call last):
  File "/content/src/cache_features_cli.py", line 46, in main
    build_and_cache_one(
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/content/src/feature_extract.py", line 431, in build_and_cache_one
    if spath is None or (not os.path.exists(spath)):
                             ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not float
100%|██████████| 10/10 [00:02<00:00,  4.60it/s]
 60%|██████    | 6/10 [00:01<00:00,  5.25it/s]Traceback (most recent call last):
  File "/content/src/cache_features_cli.py", line 46, in main
    build_and_cache_one(
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/content/src/feature_extract.py", line 431, in build_and_cache_one
    if spath is None or (not os.path.exists(spath)):
                             ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not float
100%|██████████| 10/10 [00:01<00:00,  5.73it/s]
100%|██████████| 10/10 [00:02<00:00,  4.59it/s]
100%|██████████| 10/10 [00:01<00:00,  6.37it/s]
100%|██████████| 10/10 [00:01<00:00,  5.38it/s]
100%|██████████| 10/10 [00:02<00:00,  3.98it/s]
100%|██████████| 10/10 [00:01<00:00,  5.79it/s]
100%|██████████| 10/10 [00:01<00:00,  7.69it/s]
100%|██████████| 10/10 [00:01<00:00,  5.36it/s]
100%|██████████| 10/10 [00:02<00:00,  4.01it/s]
100%|██████████| 5/5 [00:00<00:00,  5.96it/s]

**SKEL Variant 1: exp_skel_mean_std**

In [ ]:
%%bash
set -euxo pipefail
CSV=/content/phase1_all_with_split.csv
BASE_DIR=/content/drive/MyDrive/miga_features_cache_agcn
EXP_DIR=/content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std

mkdir -p "$EXP_DIR"
ln -sfn "$BASE_DIR"/*_ctx.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_face.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_facemask.pt "$EXP_DIR"/ 2>/dev/null || true

DEVICE=cpu
CHUNK=32
SHARD=10
export PYTHONUNBUFFERED=1

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase1_all_with_split.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD)); if [ $END -gt $TOTAL ]; then END=$TOTAL; fi
  echo "=== SKEL mean_std shard $START:$END ==="
  time env SKEL_AGG=mean_std PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 \
    python -u /content/src/cache_features_cli.py \
      --csv "$CSV" --phase 1 --feat_dir "$EXP_DIR" \
      --chunk "$CHUNK" --start "$START" --end "$END" --device "$DEVICE" \
      --do_skel
  START=$END
done

=== SKEL mean_std shard 0:10 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [0:10) ok=10 bad=0
=== SKEL mean_std shard 10:20 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [10:20) ok=10 bad=0
=== SKEL mean_std shard 20:30 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [20:30) ok=10 bad=0
=== SKEL mean_std shard 30:40 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [30:40) ok=10 bad=0
=== SKEL mean_std shard 40:50 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [40:50) ok=10 bad=0
=== SKEL mean_std shard 50:60 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [50:60) ok=10 bad=0
=== SKEL mean_std shard 60:70 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [60:70) ok=10 bad=0
=== SKEL mean_std shard 70:80 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [70:80) ok=10 bad=0
=== SKEL mean_std shard 80:90 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [80:90) ok=10 bad=0
=== SKEL mean_std shard 90:100 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True
 ERROR
row: 6 video_id: 319 split: train
skeleton_path: nan

DONE shard [90:100) ok=9 bad=1
=== SKEL mean_std shard 100:110 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True
 ERROR
row: 2 video_id: 348 split: train
skeleton_path: nan

DONE shard [100:110) ok=9 bad=1
=== SKEL mean_std shard 110:120 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [110:120) ok=10 bad=0
=== SKEL mean_std shard 120:130 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [120:130) ok=10 bad=0
=== SKEL mean_std shard 130:140 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [130:140) ok=10 bad=0
=== SKEL mean_std shard 140:150 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [140:150) ok=10 bad=0
=== SKEL mean_std shard 150:160 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True
 ERROR
row: 2 video_id: 347 split: train
skeleton_path: nan

DONE shard [150:160) ok=9 bad=1
=== SKEL mean_std shard 160:170 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True
 ERROR
row: 7 video_id: 218 split: train
skeleton_path: nan

DONE shard [160:170) ok=9 bad=1
=== SKEL mean_std shard 170:180 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [170:180) ok=10 bad=0
=== SKEL mean_std shard 180:190 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [180:190) ok=10 bad=0
=== SKEL mean_std shard 190:200 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [190:200) ok=10 bad=0
=== SKEL mean_std shard 200:210 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [200:210) ok=10 bad=0
=== SKEL mean_std shard 210:220 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [210:220) ok=10 bad=0
=== SKEL mean_std shard 220:230 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [220:230) ok=10 bad=0
=== SKEL mean_std shard 230:240 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [230:240) ok=10 bad=0
=== SKEL mean_std shard 240:250 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [240:250) ok=10 bad=0
=== SKEL mean_std shard 250:255 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [250:255) ok=5 bad=0

+ CSV=/content/phase1_all_with_split.csv
+ BASE_DIR=/content/drive/MyDrive/miga_features_cache_agcn
+ EXP_DIR=/content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
+ mkdir -p /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std
+ ln -sfn /content/drive/MyDrive/miga_features_cache_agcn/00a3ed33d38e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/00b40a2e4d97_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/01087f1b2489_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0123fc67d163_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/017fc7925072_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/01b372587e0a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/01dc5000e304_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/03ae04661248_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/049e754be9f7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/04c0dc00860f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/05b600b0301d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/06a239e6b160_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/088f59f97642_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0908fd243ee3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/097537f5b986_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/09a4cc150f42_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0a096ee9e4a1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0cae4d6d7f9c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0db8d3e98501_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0dc25751f019_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0dd6795a6dc0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0f2989c1a220_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0f9b72cc21eb_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1018772cd839_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/108de304743f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/11646ef853d5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1262ccdf5117_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/13756240ecd1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/13c5f3185145_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/15e9668db234_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1620ff2a4e19_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/17e047e91727_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/181fb208dd25_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/186cb628a00e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/19843783231b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1d4ede1331de_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1eae6962a63b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1f8aad2528dc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1fd4173fb471_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/201ede2caf26_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/209501eeb4a6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/221dfd7cebef_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2268ae4188f5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/22df7084383e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/239a3da840af_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/246c9b03d6f0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/252d6f4d416a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/255f7de773f8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/27384aedf70d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2a7eecbafa56_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2ae8451ecf7c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2b10042d06ec_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2bacf5eaa39f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2e8718371d09_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2ea484cff01b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2ed626e5ffd3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/30ac0539b4a4_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/31e7c5a602ca_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/322324881360_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/338be23bfe9a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/34c172f4f548_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/355330b3a745_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/36066a55360f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/39060ead04db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/39fe9da25570_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3c8a19f1a77f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3dd68fd73380_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3e960c17e92e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3f362975f317_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3f8c022aaee6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/41af1a5aaffe_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/41f09daf4463_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/420233bb0153_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/43c5f5d4c08f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/440c24c623d1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/45f2cba4384d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/47f64f106476_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/48b10dbd49ea_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4a4778763d48_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4b30c36d5a25_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4bcde5a82194_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4ca8e56af321_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/513d88fe11db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/530ab6cff714_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/532f2f26a7b3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/53a70417fdb7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/578e25e98810_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/59c71581045f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/59f1a1cf0a2e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5b8eba00fd84_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5dd01777bad9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5dec9937a35a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5e6ad9aeee6c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5f60788646aa_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6107dcd2b8db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6225dffcf8c9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/633afcff2cac_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/634c417ee7a6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/64e8ed0acfa7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6789660f21c3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/68a650f0bb38_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/69e068b4a055_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6a619c1e55b7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6a7be86ff5a1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6ad2587edec6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6afbeeeeb9db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6b39551b10ed_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6bfeb4eefb06_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6ce872d5e39b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6d2f7cd0c56c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6d40cdb467e2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6e97a12d04e5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7074194cbadf_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/71c78f751e78_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/71d43e439939_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/721bee2d4bf2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/72679ca2a7c1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/72ce819af3f5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/73cc360c5976_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7410f44a80a0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/747dbc308fef_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7570191191d8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/75c656b4afc2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/76d64d1731fa_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/77f5e5625e93_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/782ff1188c9a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/78c469b55ea4_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7961205cec28_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7a4d3f7dddf0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7b4f62aeeda8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7c20862a49a3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7c96a830913f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7de93a7e893f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7e985501bd16_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/80b0cd5eec88_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8264c10dfaaf_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8330f28b0e36_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8341d4e5de0b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/84166a7963c0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/84844a54aef0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/84fa203c5d4c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/85915c3ddab5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/85e46c0ac09e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/869c78216f36_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/87031007b9c0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/870ffff332ff_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/873a07d8ed3b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8826bb56b47c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8ae7069778aa_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8d87517df5d4_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8dd5161305d9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8ebd6371c670_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8f19d2139c7a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8ff0ddc359fd_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/90066b62470f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/90ffc2922e23_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/918e88d8abc1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/943d3a758d2b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/95b05994091e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/96619b01229e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9788e20aadfe_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/98f7fece2e41_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/993b0087a04a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/995a81c6fe26_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/996a670be739_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9ca6fcf22282_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9d56dfadd7d0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9ef217cb48a9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9f63e9fa3887_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a07c31a5a305_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a1dfee690987_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a2e7f4b7d7a6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a3a59a12efe6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a826a158ebe0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a8772324bb06_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ab04355a15a9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/abf023461e31_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ad8a195c26e0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/aecc066581e3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/af27e31fd2ff_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b1251a1fd26e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b27373f02956_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b2f54b00dda2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b36a91a30103_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b3b0fdb1426a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b4a21e3b1d42_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b50e15067a77_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b7180660d049_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b7c0c5adddd6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b803c73db2f5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b8366f151998_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b87e5c420569_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/bc604e11cd28_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/be6f549156a8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/befa9fe7ec10_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c1a60588a819_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c2dfdd55bb77_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c38ff05f1cb9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c40273ffad59_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c538ff5af2fc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ca250e19a593_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/cac3c88764f6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ce6aad694dcc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/cfe1d32f286d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/cffef16acdb3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d04f3fe7aae0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d25ad6b652f9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d43a5a46819c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d5226a19cc4d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d76fec6d157b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d8b71e097390_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dac73e3f6772_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/db57a768e402_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dbc7add1be13_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dca1f75d184d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dd0e23932d2d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ddc36aafbe05_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/de935844c489_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ded8ad49fb4c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dff90c7db1a5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e06a6125b4e0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e19f7ae86079_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e1adc4e5fdfb_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e3804ad76f56_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e3a17c0701de_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e53fbeb7872c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e56facbbec94_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e704f197f883_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e86c65a2ad2a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ea96b83905a8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/eaf780e7913f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/eb6131cde7d8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/eb623bd6229b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ebaaadd6489e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ec2a894eb09e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ec2e6984eb7a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ecaad627cf65_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ecc0d5a08ec9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ed5e79afe62a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ee71bbfa1f73_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f06014a5588d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f094214631d9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f1bca4fd3891_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f2fb190167f0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f3127395d63c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f32bb17682fd_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f3625dd8126d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f49286e2ca84_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f59b28bb72fe_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f68588ab68bb_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f6da49ba7687_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f8fa67c44485_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f8fc3aa00f3f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f99c8748866d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fa6c7f5ece5d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/faade2189271_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fbf0e0e763d9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fc4764de32f3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fe2cce3f720b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ff7690117ecc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std/
+ true

**SKEL Variant 2: exp_skel_max**

In [ ]:
%%bash
set -euxo pipefail
CSV=/content/phase1_all_with_split.csv
BASE_DIR=/content/drive/MyDrive/miga_features_cache_agcn
EXP_DIR=/content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max

mkdir -p "$EXP_DIR"
ln -sfn "$BASE_DIR"/*_ctx.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_face.pt "$EXP_DIR"/ 2>/dev/null || true
ln -sfn "$BASE_DIR"/*_facemask.pt "$EXP_DIR"/ 2>/dev/null || true

DEVICE=cpu
CHUNK=32
SHARD=10
export PYTHONUNBUFFERED=1

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase1_all_with_split.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD)); if [ $END -gt $TOTAL ]; then END=$TOTAL; fi
  echo "=== SKEL max shard $START:$END ==="
  time env SKEL_AGG=max PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 \
    python -u /content/src/cache_features_cli.py \
      --csv "$CSV" --phase 1 --feat_dir "$EXP_DIR" \
      --chunk "$CHUNK" --start "$START" --end "$END" --device "$DEVICE" \
      --do_skel
  START=$END
done

=== SKEL max shard 0:10 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [0:10) ok=10 bad=0
=== SKEL max shard 10:20 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [10:20) ok=10 bad=0
=== SKEL max shard 20:30 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [20:30) ok=10 bad=0
=== SKEL max shard 30:40 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [30:40) ok=10 bad=0
=== SKEL max shard 40:50 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [40:50) ok=10 bad=0
=== SKEL max shard 50:60 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [50:60) ok=10 bad=0
=== SKEL max shard 60:70 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [60:70) ok=10 bad=0
=== SKEL max shard 70:80 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [70:80) ok=10 bad=0
=== SKEL max shard 80:90 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [80:90) ok=10 bad=0
=== SKEL max shard 90:100 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True
 ERROR
row: 6 video_id: 319 split: train
skeleton_path: nan

DONE shard [90:100) ok=9 bad=1
=== SKEL max shard 100:110 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True
 ERROR
row: 2 video_id: 348 split: train
skeleton_path: nan

DONE shard [100:110) ok=9 bad=1
=== SKEL max shard 110:120 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [110:120) ok=10 bad=0
=== SKEL max shard 120:130 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [120:130) ok=10 bad=0
=== SKEL max shard 130:140 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [130:140) ok=10 bad=0
=== SKEL max shard 140:150 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [140:150) ok=10 bad=0
=== SKEL max shard 150:160 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True
 ERROR
row: 2 video_id: 347 split: train
skeleton_path: nan

DONE shard [150:160) ok=9 bad=1
=== SKEL max shard 160:170 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True
 ERROR
row: 7 video_id: 218 split: train
skeleton_path: nan

DONE shard [160:170) ok=9 bad=1
=== SKEL max shard 170:180 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [170:180) ok=10 bad=0
=== SKEL max shard 180:190 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [180:190) ok=10 bad=0
=== SKEL max shard 190:200 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [190:200) ok=10 bad=0
=== SKEL max shard 200:210 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [200:210) ok=10 bad=0
=== SKEL max shard 210:220 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [210:220) ok=10 bad=0
=== SKEL max shard 220:230 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [220:230) ok=10 bad=0
=== SKEL max shard 230:240 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [230:240) ok=10 bad=0
=== SKEL max shard 240:250 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [240:250) ok=10 bad=0
=== SKEL max shard 250:255 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
MODES: ctx= False face= False skel= True

DONE shard [250:255) ok=5 bad=0

+ CSV=/content/phase1_all_with_split.csv
+ BASE_DIR=/content/drive/MyDrive/miga_features_cache_agcn
+ EXP_DIR=/content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
+ mkdir -p /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max
+ ln -sfn /content/drive/MyDrive/miga_features_cache_agcn/00a3ed33d38e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/00b40a2e4d97_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/01087f1b2489_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0123fc67d163_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/017fc7925072_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/01b372587e0a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/01dc5000e304_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/03ae04661248_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/049e754be9f7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/04c0dc00860f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/05b600b0301d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/06a239e6b160_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/088f59f97642_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0908fd243ee3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/097537f5b986_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/09a4cc150f42_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0a096ee9e4a1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0cae4d6d7f9c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0db8d3e98501_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0dc25751f019_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0dd6795a6dc0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0f2989c1a220_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/0f9b72cc21eb_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1018772cd839_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/108de304743f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/11646ef853d5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1262ccdf5117_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/13756240ecd1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/13c5f3185145_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/15e9668db234_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1620ff2a4e19_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/17e047e91727_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/181fb208dd25_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/186cb628a00e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/19843783231b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1d4ede1331de_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1eae6962a63b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1f8aad2528dc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/1fd4173fb471_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/201ede2caf26_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/209501eeb4a6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/221dfd7cebef_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2268ae4188f5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/22df7084383e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/239a3da840af_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/246c9b03d6f0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/252d6f4d416a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/255f7de773f8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/27384aedf70d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2a7eecbafa56_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2ae8451ecf7c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2b10042d06ec_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2bacf5eaa39f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2e8718371d09_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2ea484cff01b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/2ed626e5ffd3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/30ac0539b4a4_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/31e7c5a602ca_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/322324881360_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/338be23bfe9a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/34c172f4f548_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/355330b3a745_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/36066a55360f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/39060ead04db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/39fe9da25570_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3c8a19f1a77f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3dd68fd73380_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3e960c17e92e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3f362975f317_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/3f8c022aaee6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/41af1a5aaffe_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/41f09daf4463_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/420233bb0153_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/43c5f5d4c08f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/440c24c623d1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/45f2cba4384d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/47f64f106476_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/48b10dbd49ea_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4a4778763d48_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4b30c36d5a25_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4bcde5a82194_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/4ca8e56af321_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/513d88fe11db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/530ab6cff714_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/532f2f26a7b3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/53a70417fdb7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/578e25e98810_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/59c71581045f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/59f1a1cf0a2e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5b8eba00fd84_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5dd01777bad9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5dec9937a35a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5e6ad9aeee6c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/5f60788646aa_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6107dcd2b8db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6225dffcf8c9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/633afcff2cac_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/634c417ee7a6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/64e8ed0acfa7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6789660f21c3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/68a650f0bb38_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/69e068b4a055_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6a619c1e55b7_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6a7be86ff5a1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6ad2587edec6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6afbeeeeb9db_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6b39551b10ed_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6bfeb4eefb06_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6ce872d5e39b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6d2f7cd0c56c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6d40cdb467e2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/6e97a12d04e5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7074194cbadf_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/71c78f751e78_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/71d43e439939_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/721bee2d4bf2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/72679ca2a7c1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/72ce819af3f5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/73cc360c5976_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7410f44a80a0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/747dbc308fef_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7570191191d8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/75c656b4afc2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/76d64d1731fa_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/77f5e5625e93_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/782ff1188c9a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/78c469b55ea4_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7961205cec28_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7a4d3f7dddf0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7b4f62aeeda8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7c20862a49a3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7c96a830913f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7de93a7e893f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/7e985501bd16_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/80b0cd5eec88_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8264c10dfaaf_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8330f28b0e36_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8341d4e5de0b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/84166a7963c0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/84844a54aef0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/84fa203c5d4c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/85915c3ddab5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/85e46c0ac09e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/869c78216f36_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/87031007b9c0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/870ffff332ff_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/873a07d8ed3b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8826bb56b47c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8ae7069778aa_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8d87517df5d4_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8dd5161305d9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8ebd6371c670_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8f19d2139c7a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/8ff0ddc359fd_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/90066b62470f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/90ffc2922e23_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/918e88d8abc1_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/943d3a758d2b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/95b05994091e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/96619b01229e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9788e20aadfe_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/98f7fece2e41_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/993b0087a04a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/995a81c6fe26_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/996a670be739_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9ca6fcf22282_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9d56dfadd7d0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9ef217cb48a9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/9f63e9fa3887_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a07c31a5a305_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a1dfee690987_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a2e7f4b7d7a6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a3a59a12efe6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a826a158ebe0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/a8772324bb06_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ab04355a15a9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/abf023461e31_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ad8a195c26e0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/aecc066581e3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/af27e31fd2ff_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b1251a1fd26e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b27373f02956_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b2f54b00dda2_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b36a91a30103_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b3b0fdb1426a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b4a21e3b1d42_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b50e15067a77_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b7180660d049_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b7c0c5adddd6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b803c73db2f5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b8366f151998_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/b87e5c420569_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/bc604e11cd28_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/be6f549156a8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/befa9fe7ec10_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c1a60588a819_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c2dfdd55bb77_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c38ff05f1cb9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c40273ffad59_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/c538ff5af2fc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ca250e19a593_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/cac3c88764f6_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ce6aad694dcc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/cfe1d32f286d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/cffef16acdb3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d04f3fe7aae0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d25ad6b652f9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d43a5a46819c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d5226a19cc4d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d76fec6d157b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/d8b71e097390_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dac73e3f6772_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/db57a768e402_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dbc7add1be13_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dca1f75d184d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dd0e23932d2d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ddc36aafbe05_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/de935844c489_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ded8ad49fb4c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/dff90c7db1a5_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e06a6125b4e0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e19f7ae86079_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e1adc4e5fdfb_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e3804ad76f56_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e3a17c0701de_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e53fbeb7872c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e56facbbec94_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e704f197f883_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/e86c65a2ad2a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ea96b83905a8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/eaf780e7913f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/eb6131cde7d8_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/eb623bd6229b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ebaaadd6489e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ec2a894eb09e_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ec2e6984eb7a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ecaad627cf65_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ecc0d5a08ec9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ed5e79afe62a_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ee71bbfa1f73_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f06014a5588d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f094214631d9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f1bca4fd3891_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f2fb190167f0_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f3127395d63c_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f32bb17682fd_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f3625dd8126d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f49286e2ca84_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f59b28bb72fe_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f68588ab68bb_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f6da49ba7687_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f8fa67c44485_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f8fc3aa00f3f_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/f99c8748866d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fa6c7f5ece5d_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/faade2189271_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fbf0e0e763d9_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fc4764de32f3_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/fe2cce3f720b_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/ff7690117ecc_ctx.pt /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_max/
+ true

In [27]:
%%writefile /content/src/model.py
import torch
import torch.nn as nn
import torch.nn.functional as F

class AttnPool(nn.Module):
    def __init__(self, d):
        super().__init__()
        self.scorer = nn.Sequential(
            nn.Linear(d, d // 2),
            nn.GELU(),
            nn.Linear(d // 2, 1)
        )

    def forward(self, x, mask):
        # x: (B, T, d)
        # mask: (B, T) – True для реальных данных
        if mask.numel() == 0 or mask.sum() == 0:
            # Нет валидных элементов – возвращаем нулевой вектор
            return torch.zeros(x.size(0), x.size(2), device=x.device, dtype=x.dtype)
        score = self.scorer(x).squeeze(-1)  # (B, T)
        score = score.float()
        score = score.masked_fill(~mask, -1e4)
        w = torch.softmax(score, dim=1).unsqueeze(-1)  # (B, T, 1)
        w = w.to(dtype=x.dtype)
        return (x * w).sum(dim=1)

class TriStreamModel(nn.Module):
    def __init__(
        self,
        d_ctx_in=512,
        d_face_in=1280,
        d_skel_in=512,
        d=512,
        n_layers=4,
        n_heads=4,
        dropout=0.3,
    ):
        super().__init__()

        self.ctx_in  = nn.Sequential(nn.Linear(d_ctx_in, d), nn.Dropout(dropout))
        self.face_in = nn.Sequential(nn.Linear(d_face_in, d), nn.Dropout(dropout))
        self.skel_in = nn.Sequential(nn.Linear(d_skel_in, d), nn.Dropout(dropout))

        enc = nn.TransformerEncoderLayer(
            d_model=d,
            nhead=n_heads,
            dim_feedforward=4 * d,
            dropout=dropout,
            batch_first=True,
            activation="gelu"
        )

        self.ctx_enc  = nn.TransformerEncoder(enc, num_layers=n_layers)
        self.face_enc = nn.TransformerEncoder(enc, num_layers=n_layers)
        self.skel_enc = nn.TransformerEncoder(enc, num_layers=n_layers)

        self.ctx_pool  = AttnPool(d)
        self.face_pool = AttnPool(d)
        self.skel_pool = AttnPool(d)

        self.head = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(3 * d, d),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(d, 1)
        )

    def forward(self, ctx, face, skel, time_mask, face_mask, skel_mask):
        # Проецируем
        x_ctx = self.ctx_in(ctx)
        x_face = self.face_in(face)
        x_skel = self.skel_in(skel)

        # Кодируем контекст (всегда есть)
        if x_ctx.size(1) > 0:
            pad_ignore = ~time_mask  # (B, T)
            # Если в каком-то образце все элементы pad_ignore True, исправляем
            if pad_ignore.ndim == 2 and pad_ignore.shape[1] > 0:
                all_pad = pad_ignore.all(dim=1)
                if all_pad.any():
                    pad_ignore = pad_ignore.clone()
                    pad_ignore[all_pad, 0] = False
            x_ctx = self.ctx_enc(x_ctx, src_key_padding_mask=pad_ignore)

        # Кодируем лицо, только если есть хотя бы один ненулевой элемент маски
        if x_face.size(1) > 0 and face_mask.sum() > 0:
            x_face = self.face_enc(x_face, src_key_padding_mask=~face_mask)
        # иначе оставляем x_face как есть (уже спроецирован, но не обработан энкодером)

        # Кодируем скелет аналогично
        if x_skel.size(1) > 0 and skel_mask.sum() > 0:
            x_skel = self.skel_enc(x_skel, src_key_padding_mask=~skel_mask)

        # Пулинг с учётом масок
        ctx_vec  = self.ctx_pool(x_ctx, time_mask)
        face_vec = self.face_pool(x_face, face_mask)
        skel_vec = self.skel_pool(x_skel, skel_mask)

        # Конкатенация и классификация
        z = torch.cat([ctx_vec, face_vec, skel_vec], dim=-1)
        return self.head(z).squeeze(-1)

Overwriting /content/src/model.py

In [15]:
%%writefile /content/src/ds.py
import os
import torch
import numpy as np
from torch.utils.data import Dataset

def cache_key(video_id, split, phase):
    s = f"{int(video_id)}|{split}|{phase}"
    import hashlib
    return hashlib.md5(s.encode("utf-8")).hexdigest()[:12]

class Track3CachedDataset(Dataset):
    def __init__(
        self,
        df,
        ctx_dir=None,
        face_dir=None,
        skel_dir=None,
        feat_dir=None,
        phase=1,
        has_label=True,
        use_ctx=True,
        use_face=True,
        use_skel=True
    ):
        self.df = df.reset_index(drop=True)
        self.phase = phase
        self.has_label = has_label
        self.use_ctx = use_ctx
        self.use_face = use_face
        self.use_skel = use_skel

        if feat_dir is not None:
            self.ctx_dir = feat_dir
            self.face_dir = feat_dir
            self.skel_dir = feat_dir
        else:
            self.ctx_dir = ctx_dir
            self.face_dir = face_dir
            self.skel_dir = skel_dir

        self.keys = []
        self.ids = []
        self.splits = []
        for _, row in self.df.iterrows():
            video_id = int(row["video_id"])
            split = row.get("split", "train")
            key = cache_key(video_id, split, self.phase)
            self.keys.append(key)
            self.ids.append(video_id)
            self.splits.append(split)

        if has_label and "label" in self.df.columns:
            self.labels = self.df["label"].values.astype(np.float32)
        else:
            self.labels = None

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        key = self.keys[idx]
        out = {"id": self.ids[idx], "split": self.splits[idx]}

        # Контекст
        if self.use_ctx and self.ctx_dir:
            ctx_path = os.path.join(self.ctx_dir, f"{key}_ctx.pt")
            if os.path.exists(ctx_path):
                ctx = torch.load(ctx_path)
                out["ctx"] = ctx.float()
                out["time_mask"] = torch.ones(len(ctx), dtype=torch.bool)
            else:
                out["ctx"] = torch.zeros((0, 512), dtype=torch.float32)
                out["time_mask"] = torch.zeros(0, dtype=torch.bool)
        else:
            out["ctx"] = torch.zeros((0, 512), dtype=torch.float32)
            out["time_mask"] = torch.zeros(0, dtype=torch.bool)

        # Лицо
        if self.use_face and self.face_dir:
            face_path = os.path.join(self.face_dir, f"{key}_face.pt")
            fmask_path = os.path.join(self.face_dir, f"{key}_facemask.pt")
            if os.path.exists(face_path) and os.path.exists(fmask_path):
                face = torch.load(face_path)
                fmask = torch.load(fmask_path)
                out["face"] = face.float()
                out["face_mask"] = fmask.bool()
            else:
                out["face"] = torch.zeros((0, 1280), dtype=torch.float32)
                out["face_mask"] = torch.zeros(0, dtype=torch.bool)
        else:
            out["face"] = torch.zeros((0, 1280), dtype=torch.float32)
            out["face_mask"] = torch.zeros(0, dtype=torch.bool)

        # Скелет
        if self.use_skel and self.skel_dir:
            skel_path = os.path.join(self.skel_dir, f"{key}_skel.pt")
            smask_path = os.path.join(self.skel_dir, f"{key}_skelmask.pt")
            if os.path.exists(skel_path) and os.path.exists(smask_path):
                skel = torch.load(skel_path)
                smask = torch.load(smask_path)
                out["skel"] = skel.float()
                out["skel_mask"] = smask.bool()
            else:
                out["skel"] = torch.zeros((0, 512), dtype=torch.float32)
                out["skel_mask"] = torch.zeros(0, dtype=torch.bool)
        else:
            out["skel"] = torch.zeros((0, 512), dtype=torch.float32)
            out["skel_mask"] = torch.zeros(0, dtype=torch.bool)

        if self.labels is not None:
            out["y"] = torch.tensor(self.labels[idx], dtype=torch.float32)

        return out

def pad_seq(list_TD, pad_value=0.0):
    if len(list_TD) == 0:
        return torch.empty(0, 0, 0), torch.empty(0, 0, dtype=torch.bool)
    T = max(x.shape[0] for x in list_TD)
    D = list_TD[0].shape[1] if len(list_TD[0].shape) > 1 else 0
    out = torch.full((len(list_TD), T, D), pad_value, dtype=torch.float32)
    mask = torch.zeros((len(list_TD), T), dtype=torch.bool)
    for i, x in enumerate(list_TD):
        if x.shape[0] > 0:
            out[i, :x.shape[0]] = x.float()
            mask[i, :x.shape[0]] = True
    return out, mask

def collate_fn(batch):
    # Контекст – всегда есть (может быть пустым, но для тренировки не пуст)
    ctx_list = [b["ctx"] for b in batch]
    ctx_pad, time_mask = pad_seq(ctx_list)  # (B, T_ctx, 512)
    B, T_ctx, _ = ctx_pad.shape

    # Лицо: если хотя бы один образец имеет ненулевую длину, паддим до T_ctx,
    # иначе возвращаем пустой тензор и пустую маску.
    face_lens = [b["face"].size(0) for b in batch]
    if any(l > 0 for l in face_lens):
        face_pad = torch.zeros(B, T_ctx, 1280, dtype=torch.float32)
        face_mask = torch.zeros(B, T_ctx, dtype=torch.bool)
        for i, b in enumerate(batch):
            f = b["face"]
            if f.size(0) > 0:
                copy_len = min(T_ctx, f.size(0))
                face_pad[i, :copy_len] = f[:copy_len]
                fm = b.get("face_mask", torch.ones(copy_len, dtype=torch.bool))
                face_mask[i, :copy_len] = fm[:copy_len]
    else:
        # Все образцы не имеют лица -> возвращаем пустые тензоры
        face_pad = torch.zeros(B, 0, 1280, dtype=torch.float32)
        face_mask = torch.zeros(B, 0, dtype=torch.bool)

    # Скелет аналогично
    skel_lens = [b["skel"].size(0) for b in batch]
    if any(l > 0 for l in skel_lens):
        skel_pad = torch.zeros(B, T_ctx, 512, dtype=torch.float32)
        skel_mask = torch.zeros(B, T_ctx, dtype=torch.bool)
        for i, b in enumerate(batch):
            s = b["skel"]
            if s.size(0) > 0:
                copy_len = min(T_ctx, s.size(0))
                skel_pad[i, :copy_len] = s[:copy_len]
                sm = b.get("skel_mask", torch.ones(copy_len, dtype=torch.bool))
                skel_mask[i, :copy_len] = sm[:copy_len]
    else:
        skel_pad = torch.zeros(B, 0, 512, dtype=torch.float32)
        skel_mask = torch.zeros(B, 0, dtype=torch.bool)

    out = {
        "id": [b["id"] for b in batch],
        "ctx": ctx_pad,
        "face": face_pad,
        "skel": skel_pad,
        "time_mask": time_mask,
        "face_mask": face_mask,
        "skel_mask": skel_mask,
    }

    if "y" in batch[0]:
        out["y"] = torch.stack([b["y"] for b in batch])

    return out

Writing /content/src/ds.py

**PHASE 1**

**Абляция по модальностям**

In [16]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import os

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, WeightedRandomSampler
from sklearn.model_selection import StratifiedKFold

from src.ds import Track3CachedDataset, collate_fn
from src.model import TriStreamModel

# ---- базовые пути ----
BASE_FEAT_DIR = "/content/drive/MyDrive/miga_features_cache_agcn"
device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

# ---- загружаем данные ----
if 'train_ok' not in dir() or train_ok is None or len(train_ok) == 0:
    train_ok = pd.read_csv('/content/phase1_all_with_split.csv')
    print(f"Загружено {len(train_ok)} строк")

df_ok = train_ok.reset_index(drop=True).copy()
print(f"Размер df_ok: {len(df_ok)}")

# ---- определяем размерности признаков на примере baseline-папок ----
tmp_ds = Track3CachedDataset(
    df_ok.iloc[:1],
    ctx_dir=os.path.join(BASE_FEAT_DIR, "baseline_ctx"),
    face_dir=os.path.join(BASE_FEAT_DIR, "baseline_face"),
    skel_dir=os.path.join(BASE_FEAT_DIR, "baseline_skel"),
    phase=1,
    has_label=True
)
sample = tmp_ds[0]

D_FACE  = int(sample["face"].shape[1])
d_ctx_in  = int(sample["ctx"].shape[1])
d_skel_in = int(sample["skel"].shape[1])

print("sample id:", sample["id"])
print("dims: ctx", d_ctx_in, "face", D_FACE, "skel", d_skel_in)

# =========================
# Metrics helpers
# =========================
@torch.no_grad()
def probs_from_logits(logits: torch.Tensor) -> np.ndarray:
    return torch.sigmoid(logits).detach().cpu().numpy().astype(np.float64)

def top1_at_thr(p: np.ndarray, y: np.ndarray, thr: float = 0.5) -> float:
    pred = (p >= thr).astype(np.int64)
    return float((pred == y.astype(np.int64)).mean())

def balanced_top1_at_thr(p: np.ndarray, y: np.ndarray, thr: float = 0.5):
    y = y.astype(np.int64)
    pred = (p >= thr).astype(np.int64)
    pos = (y == 1)
    neg = (y == 0)
    tpr = float((pred[pos] == 1).mean()) if pos.any() else float("nan")
    tnr = float((pred[neg] == 0).mean()) if neg.any() else float("nan")
    bacc = float(np.nanmean([tpr, tnr]))
    return bacc, tpr, tnr

# =========================
# Ablation helpers
# =========================
def apply_ablation_to_batch(b, cfg):
    if not cfg["use_ctx"]:
        b["ctx"] = torch.zeros_like(b["ctx"])
    if not cfg["use_face"]:
        b["face"] = torch.zeros_like(b["face"])
        b["face_mask"] = torch.zeros_like(b["face_mask"]).bool()
    if not cfg["use_skel"]:
        b["skel"] = torch.zeros_like(b["skel"])
        b["skel_mask"] = torch.zeros_like(b["skel_mask"]).bool()
    return b

@torch.no_grad()
def infer(model, loader, ab_cfg):
    model.eval()
    all_p, all_y, all_ids = [], [], []
    for b in loader:
        b = apply_ablation_to_batch(b, ab_cfg)
        logit = model(
            b["ctx"].to(device, non_blocking=True),
            b["face"].to(device, non_blocking=True),
            b["skel"].to(device, non_blocking=True),
            b["time_mask"].to(device, non_blocking=True),
            b["face_mask"].to(device, non_blocking=True),
            b["skel_mask"].to(device, non_blocking=True),
        )
        p = probs_from_logits(logit)
        y = b["y"].detach().cpu().numpy().astype(np.int64)
        ids = np.array(b["id"], dtype=np.int64)
        all_p.append(p)
        all_y.append(y)
        all_ids.append(ids)
    return np.concatenate(all_p), np.concatenate(all_y), np.concatenate(all_ids)

# =========================
# Train one fold
# =========================
def train_one_fold(
    tr_df, va_df, ab_cfg,
    ctx_dir, face_dir, skel_dir,
    epochs=12, lr=2e-4, wd=1e-4, bs=16, patience=4
):
    tr_ds = Track3CachedDataset(
        tr_df,
        ctx_dir=ctx_dir, face_dir=face_dir, skel_dir=skel_dir,
        phase=1, has_label=True,
        use_ctx=ab_cfg["use_ctx"], use_face=ab_cfg["use_face"], use_skel=ab_cfg["use_skel"]
    )
    va_ds = Track3CachedDataset(
        va_df,
        ctx_dir=ctx_dir, face_dir=face_dir, skel_dir=skel_dir,
        phase=1, has_label=True,
        use_ctx=ab_cfg["use_ctx"], use_face=ab_cfg["use_face"], use_skel=ab_cfg["use_skel"]
    )

    y_tr = tr_df["label"].values.astype(np.int64)
    cnt = np.bincount(y_tr, minlength=2)
    cls_w = 1.0 / np.maximum(cnt, 1)
    samp_w = cls_w[y_tr]
    sampler = WeightedRandomSampler(samp_w, num_samples=len(samp_w), replacement=True)

    tr_loader = DataLoader(tr_ds, batch_size=bs, sampler=sampler, num_workers=0,
                           collate_fn=collate_fn, pin_memory=True)
    va_loader = DataLoader(va_ds, batch_size=bs, shuffle=False, num_workers=0,
                           collate_fn=collate_fn, pin_memory=True)

    model = TriStreamModel(
        d_ctx_in=d_ctx_in,
        d_face_in=D_FACE,
        d_skel_in=d_skel_in,
        d=512,
        n_layers=4,
        n_heads=4,
        dropout=0.3,
    ).to(device)

    crit = nn.BCEWithLogitsLoss()
    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=wd)
    scaler = torch.amp.GradScaler("cuda", enabled=(device == "cuda"))

    best_acc = -1.0
    best_state = None
    bad = 0

    for epoch in range(1, epochs + 1):
        model.train()
        losses = []
        for b in tr_loader:
            opt.zero_grad(set_to_none=True)
            with torch.amp.autocast("cuda", enabled=(device == "cuda")):
                logit = model(
                    b["ctx"].to(device, non_blocking=True),
                    b["face"].to(device, non_blocking=True),
                    b["skel"].to(device, non_blocking=True),
                    b["time_mask"].to(device, non_blocking=True),
                    b["face_mask"].to(device, non_blocking=True),
                    b["skel_mask"].to(device, non_blocking=True),
                )
                yb = b["y"].to(device, non_blocking=True)
                loss = crit(logit, yb)
            scaler.scale(loss).backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(opt)
            scaler.update()
            losses.append(float(loss.item()))

        p, y, _ = infer(model, va_loader, ab_cfg)
        acc05 = top1_at_thr(p, y, 0.5)
        bacc05, tpr, tnr = balanced_top1_at_thr(p, y, 0.5)

        print(f"epoch {epoch}: loss={np.mean(losses):.4f} "
              f"val_top1@0.5={acc05:.4f} | bal_top1={bacc05:.4f} (tpr={tpr:.3f}, tnr={tnr:.3f})")

        if acc05 > best_acc + 1e-6:
            best_acc = acc05
            best_state = {k: v.detach().cpu() for k, v in model.state_dict().items()}
            bad = 0
        else:
            bad += 1
            if bad >= patience:
                break

    return best_acc, best_state

# =========================
# Run CV for one setting
# =========================
def run_cv_setting(df, name, ab_cfg, ctx_dir, face_dir, skel_dir,
                   n_splits=5, seed=42, epochs=12, lr=2e-4, wd=1e-4, bs=16):
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    y_all = df["label"].values.astype(np.int64)

    oof_p = np.zeros(len(df), dtype=np.float64)
    fold_scores = []
    best_fold_state = None
    best_fold_score = -1.0

    for fold, (tr_idx, va_idx) in enumerate(skf.split(df, y_all), 1):
        print(f"\n--- fold {fold}/{n_splits} ---")
        tr_df = df.iloc[tr_idx].reset_index(drop=True)
        va_df = df.iloc[va_idx].reset_index(drop=True)

        fold_acc, fold_state = train_one_fold(
            tr_df, va_df, ab_cfg,
            ctx_dir=ctx_dir, face_dir=face_dir, skel_dir=skel_dir,
            epochs=epochs, lr=lr, wd=wd, bs=bs, patience=4
        )

        model = TriStreamModel(
            d_ctx_in=d_ctx_in,
            d_face_in=D_FACE,
            d_skel_in=d_skel_in,
            d=512,
            n_layers=4,
            n_heads=4,
            dropout=0.3,
        ).to(device)
        model.load_state_dict(fold_state)
        model.eval()

        va_ds = Track3CachedDataset(va_df, ctx_dir=ctx_dir, face_dir=face_dir, skel_dir=skel_dir,
                                     phase=1, has_label=True,
                                     use_ctx=ab_cfg["use_ctx"], use_face=ab_cfg["use_face"], use_skel=ab_cfg["use_skel"])
        va_loader = DataLoader(va_ds, batch_size=bs, shuffle=False, num_workers=0,
                               collate_fn=collate_fn, pin_memory=True)

        p, y, _ = infer(model, va_loader, ab_cfg)
        oof_p[va_idx] = p

        fold_scores.append(fold_acc)
        print(f"fold {fold} best top1@0.5={fold_acc:.4f}")

        if fold_acc > best_fold_score:
            best_fold_score = fold_acc
            best_fold_state = fold_state

    oof_acc05 = top1_at_thr(oof_p, y_all, 0.5)
    oof_bacc05, oof_tpr, oof_tnr = balanced_top1_at_thr(oof_p, y_all, 0.5)

    print(f"\n[{name}] CV mean top1@0.5={np.mean(fold_scores):.4f} ± {np.std(fold_scores):.4f}")
    print(f"[{name}] OOF  top1@0.5={oof_acc05:.4f} | bal_top1={oof_bacc05:.4f} (tpr={oof_tpr:.3f}, tnr={oof_tnr:.3f})")

    return {
        "name": name,
        "ab_cfg": ab_cfg,
        "fold_scores": fold_scores,
        "oof_p": oof_p,
        "oof_y": y_all.copy(),
        "best_state": best_fold_state,
        "oof_acc05": oof_acc05,
        "oof_bacc05": oof_bacc05,
    }

# =========================
# ABLATIONS – только унимодальные эксперименты
# =========================
BASE = "/content/drive/MyDrive/miga_features_cache_agcn"

# Конфигурации для каждой модальности
unimodal_cfgs = {
    "ctx":  {"use_ctx": True,  "use_face": False, "use_skel": False},
    "face": {"use_ctx": False, "use_face": True,  "use_skel": False},
    "skel": {"use_ctx": False, "use_face": False, "use_skel": True},
}

# Список экспериментов с указанием модальности и путей
experiments = [
    # Контекст
    {"name": "ctx_baseline", "modality": "ctx", "ctx_dir": f"{BASE}/baseline_ctx", "face_dir": f"{BASE}/baseline_face", "skel_dir": f"{BASE}/baseline_skel"},
    {"name": "ctx_mc3",      "modality": "ctx", "ctx_dir": f"{BASE}/exp_ctx_mc3", "face_dir": f"{BASE}/baseline_face", "skel_dir": f"{BASE}/baseline_skel"},
    {"name": "ctx_r2plus1d", "modality": "ctx", "ctx_dir": f"{BASE}/exp_ctx_r2plus1d", "face_dir": f"{BASE}/baseline_face", "skel_dir": f"{BASE}/baseline_skel"},
    # Лицо
    {"name": "face_baseline", "modality": "face", "ctx_dir": f"{BASE}/baseline_ctx", "face_dir": f"{BASE}/baseline_face", "skel_dir": f"{BASE}/baseline_skel"},
    {"name": "face_3avg",     "modality": "face", "ctx_dir": f"{BASE}/baseline_ctx", "face_dir": f"{BASE}/exp_face_3frames_avg", "skel_dir": f"{BASE}/baseline_skel"},
    {"name": "face_center",   "modality": "face", "ctx_dir": f"{BASE}/baseline_ctx", "face_dir": f"{BASE}/exp_face_centercrop_fast", "skel_dir": f"{BASE}/baseline_skel"},
    # Скелет
    {"name": "skel_baseline", "modality": "skel", "ctx_dir": f"{BASE}/baseline_ctx", "face_dir": f"{BASE}/baseline_face", "skel_dir": f"{BASE}/baseline_skel"},
    {"name": "skel_meanstd",  "modality": "skel", "ctx_dir": f"{BASE}/baseline_ctx", "face_dir": f"{BASE}/baseline_face", "skel_dir": f"{BASE}/exp_skel_mean_std"},
    {"name": "skel_max",      "modality": "skel", "ctx_dir": f"{BASE}/baseline_ctx", "face_dir": f"{BASE}/baseline_face", "skel_dir": f"{BASE}/exp_skel_max"},
]

summary_rows = []

for exp in experiments:
    modality = exp["modality"]
    ab_cfg = unimodal_cfgs[modality]
    print("\n" + "="*80)
    print(f"Эксперимент: {exp['name']} | Модальность: {modality}")
    print(f"ctx_dir: {exp['ctx_dir']}")
    print(f"face_dir: {exp['face_dir']}")
    print(f"skel_dir: {exp['skel_dir']}")
    print("="*80)

    res = run_cv_setting(
        df_ok,
        name=exp['name'],
        ab_cfg=ab_cfg,
        ctx_dir=exp['ctx_dir'],
        face_dir=exp['face_dir'],
        skel_dir=exp['skel_dir'],
        n_splits=5,
        epochs=12
    )

    variant = exp['name'].split('_', 1)[1] if '_' in exp['name'] else exp['name']

    summary_rows.append({
        "Experiment": exp['name'],
        "Modality": modality,
        "Variant": variant,
        "Top-1 Accuracy (%)": 100.0 * res["oof_acc05"],
        "CV mean (%)": 100.0 * np.mean(res["fold_scores"]),
        "CV std (%)": 100.0 * np.std(res["fold_scores"]),
    })

summary = pd.DataFrame(summary_rows)
summary = summary.sort_values(["Modality", "Top-1 Accuracy (%)"], ascending=[True, False])
display(summary)

device: cuda
Загружено 255 строк
Размер df_ok: 255
sample id: 68
dims: ctx 512 face 1280 skel 512

================================================================================
Эксперимент: ctx_baseline | Модальность: ctx
ctx_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
face_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
skel_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
================================================================================

--- fold 1/5 ---

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/transformer.py:515: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. We recommend specifying layout=torch.jagged when constructing a nested tensor, as this layout receives active development, has better operator coverage, and works with torch.compile. (Triggered internally at /pytorch/aten/src/ATen/NestedTensorImpl.cpp:178.)
  output = torch._nested_tensor_from_mask(

epoch 1: loss=0.7282 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 2: loss=0.7322 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6747 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 4: loss=0.7035 val_top1@0.5=0.3922 | bal_top1=0.5463 (tpr=0.293, tnr=0.800)
epoch 5: loss=0.6824 val_top1@0.5=0.7843 | bal_top1=0.4878 (tpr=0.976, tnr=0.000)
fold 1 best top1@0.5=0.8039

--- fold 2/5 ---
epoch 1: loss=0.6926 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6999 val_top1@0.5=0.3922 | bal_top1=0.3573 (tpr=0.415, tnr=0.300)
epoch 3: loss=0.6695 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.7065 val_top1@0.5=0.6863 | bal_top1=0.4646 (tpr=0.829, tnr=0.100)
epoch 5: loss=0.6562 val_top1@0.5=0.7255 | bal_top1=0.4890 (tpr=0.878, tnr=0.100)
epoch 6: loss=0.5836 val_top1@0.5=0.6275 | bal_top1=0.4659 (tpr=0.732, tnr=0.200)
epoch 7: loss=0.5846 val_top1@0.5=0.7451 | bal_top1=0.4634 (tpr=0.927, tnr=0.000)
epoch 8: loss=0.6623 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 9: loss=0.4721 val_top1@0.5=0.6471 | bal_top1=0.4780 (tpr=0.756, tnr=0.200)
epoch 10: loss=0.4987 val_top1@0.5=0.4314 | bal_top1=0.4573 (tpr=0.415, tnr=0.500)
epoch 11: loss=0.4752 val_top1@0.5=0.4902 | bal_top1=0.4939 (tpr=0.488, tnr=0.500)
epoch 12: loss=0.5270 val_top1@0.5=0.3137 | bal_top1=0.4976 (tpr=0.195, tnr=0.800)
fold 2 best top1@0.5=0.8039

--- fold 3/5 ---
epoch 1: loss=0.6999 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 2: loss=0.6980 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 3: loss=0.6865 val_top1@0.5=0.2941 | bal_top1=0.4511 (tpr=0.175, tnr=0.727)
epoch 4: loss=0.6791 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 5: loss=0.6675 val_top1@0.5=0.7451 | bal_top1=0.5080 (tpr=0.925, tnr=0.091)
fold 3 best top1@0.5=0.7843

--- fold 4/5 ---
epoch 1: loss=0.6864 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6967 val_top1@0.5=0.2941 | bal_top1=0.4841 (tpr=0.150, tnr=0.818)
epoch 3: loss=0.7011 val_top1@0.5=0.7255 | bal_top1=0.6273 (tpr=0.800, tnr=0.455)
epoch 4: loss=0.6662 val_top1@0.5=0.6667 | bal_top1=0.6557 (tpr=0.675, tnr=0.636)
epoch 5: loss=0.6295 val_top1@0.5=0.7843 | bal_top1=0.6318 (tpr=0.900, tnr=0.364)
epoch 6: loss=0.5794 val_top1@0.5=0.7451 | bal_top1=0.6398 (tpr=0.825, tnr=0.455)
epoch 7: loss=0.5529 val_top1@0.5=0.7255 | bal_top1=0.6273 (tpr=0.800, tnr=0.455)
epoch 8: loss=0.6246 val_top1@0.5=0.4706 | bal_top1=0.5307 (tpr=0.425, tnr=0.636)
epoch 9: loss=0.5956 val_top1@0.5=0.5490 | bal_top1=0.5807 (tpr=0.525, tnr=0.636)
fold 4 best top1@0.5=0.7843

--- fold 5/5 ---
epoch 1: loss=0.6853 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.7210 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 3: loss=0.6978 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.7014 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 5: loss=0.7070 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 6: loss=0.6753 val_top1@0.5=0.3529 | bal_top1=0.5545 (tpr=0.200, tnr=0.909)
fold 5 best top1@0.5=0.7843

[ctx_baseline] CV mean top1@0.5=0.7922 ± 0.0096
[ctx_baseline] OOF  top1@0.5=0.7922 | bal_top1=0.5278 (tpr=0.980, tnr=0.075)

================================================================================
Эксперимент: ctx_mc3 | Модальность: ctx
ctx_dir: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_mc3
face_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
skel_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
================================================================================

--- fold 1/5 ---
epoch 1: loss=0.6789 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 2: loss=0.6888 val_top1@0.5=0.5882 | bal_top1=0.4415 (tpr=0.683, tnr=0.200)
epoch 3: loss=0.6431 val_top1@0.5=0.7059 | bal_top1=0.4768 (tpr=0.854, tnr=0.100)
epoch 4: loss=0.5840 val_top1@0.5=0.4510 | bal_top1=0.4317 (tpr=0.463, tnr=0.400)
epoch 5: loss=0.6374 val_top1@0.5=0.5686 | bal_top1=0.4293 (tpr=0.659, tnr=0.200)
fold 1 best top1@0.5=0.8039

--- fold 2/5 ---
epoch 1: loss=0.7140 val_top1@0.5=0.6863 | bal_top1=0.5024 (tpr=0.805, tnr=0.200)
epoch 2: loss=0.6751 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 3: loss=0.6925 val_top1@0.5=0.5490 | bal_top1=0.4549 (tpr=0.610, tnr=0.300)
epoch 4: loss=0.6184 val_top1@0.5=0.4902 | bal_top1=0.4939 (tpr=0.488, tnr=0.500)
epoch 5: loss=0.5383 val_top1@0.5=0.6471 | bal_top1=0.5537 (tpr=0.707, tnr=0.400)
epoch 6: loss=0.4746 val_top1@0.5=0.6667 | bal_top1=0.5280 (tpr=0.756, tnr=0.300)
fold 2 best top1@0.5=0.8039

--- fold 3/5 ---
epoch 1: loss=0.6755 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6981 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6373 val_top1@0.5=0.6667 | bal_top1=0.4250 (tpr=0.850, tnr=0.000)
epoch 4: loss=0.5827 val_top1@0.5=0.5098 | bal_top1=0.6216 (tpr=0.425, tnr=0.818)
epoch 5: loss=0.6740 val_top1@0.5=0.3333 | bal_top1=0.5420 (tpr=0.175, tnr=0.909)
epoch 6: loss=0.5406 val_top1@0.5=0.4706 | bal_top1=0.5636 (tpr=0.400, tnr=0.727)
epoch 7: loss=0.4460 val_top1@0.5=0.6667 | bal_top1=0.6557 (tpr=0.675, tnr=0.636)
fold 3 best top1@0.5=0.6667

--- fold 4/5 ---
epoch 1: loss=0.6905 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6637 val_top1@0.5=0.8039 | bal_top1=0.6114 (tpr=0.950, tnr=0.273)
epoch 3: loss=0.6426 val_top1@0.5=0.2353 | bal_top1=0.5125 (tpr=0.025, tnr=1.000)
epoch 4: loss=0.7153 val_top1@0.5=0.2941 | bal_top1=0.4841 (tpr=0.150, tnr=0.818)
epoch 5: loss=0.6804 val_top1@0.5=0.5882 | bal_top1=0.6386 (tpr=0.550, tnr=0.727)
epoch 6: loss=0.6829 val_top1@0.5=0.8235 | bal_top1=0.5909 (tpr=1.000, tnr=0.182)
epoch 7: loss=0.6344 val_top1@0.5=0.3137 | bal_top1=0.5295 (tpr=0.150, tnr=0.909)
epoch 8: loss=0.5820 val_top1@0.5=0.4902 | bal_top1=0.5432 (tpr=0.450, tnr=0.636)
epoch 9: loss=0.5204 val_top1@0.5=0.6078 | bal_top1=0.5523 (tpr=0.650, tnr=0.455)
epoch 10: loss=0.5359 val_top1@0.5=0.6275 | bal_top1=0.5648 (tpr=0.675, tnr=0.455)
fold 4 best top1@0.5=0.8235

--- fold 5/5 ---
epoch 1: loss=0.7154 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.7099 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 3: loss=0.7186 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.6733 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 5: loss=0.6673 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 6: loss=0.6540 val_top1@0.5=0.5882 | bal_top1=0.6716 (tpr=0.525, tnr=0.818)
fold 5 best top1@0.5=0.7843

[ctx_mc3] CV mean top1@0.5=0.7765 ± 0.0563
[ctx_mc3] OOF  top1@0.5=0.7765 | bal_top1=0.5040 (tpr=0.970, tnr=0.038)

================================================================================
Эксперимент: ctx_r2plus1d | Модальность: ctx
ctx_dir: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
face_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
skel_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
================================================================================

--- fold 1/5 ---
epoch 1: loss=0.6889 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 2: loss=0.6873 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 3: loss=0.6903 val_top1@0.5=0.7255 | bal_top1=0.5646 (tpr=0.829, tnr=0.300)
epoch 4: loss=0.6148 val_top1@0.5=0.6471 | bal_top1=0.4780 (tpr=0.756, tnr=0.200)
epoch 5: loss=0.6256 val_top1@0.5=0.7451 | bal_top1=0.5768 (tpr=0.854, tnr=0.300)
fold 1 best top1@0.5=0.8039

--- fold 2/5 ---
epoch 1: loss=0.6894 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 2: loss=0.7001 val_top1@0.5=0.2745 | bal_top1=0.5488 (tpr=0.098, tnr=1.000)
epoch 3: loss=0.6478 val_top1@0.5=0.7059 | bal_top1=0.5524 (tpr=0.805, tnr=0.300)
epoch 4: loss=0.5710 val_top1@0.5=0.6275 | bal_top1=0.4659 (tpr=0.732, tnr=0.200)
epoch 5: loss=0.5599 val_top1@0.5=0.5490 | bal_top1=0.5683 (tpr=0.537, tnr=0.600)
fold 2 best top1@0.5=0.8039

--- fold 3/5 ---
epoch 1: loss=0.6972 val_top1@0.5=0.6863 | bal_top1=0.6023 (tpr=0.750, tnr=0.455)
epoch 2: loss=0.6911 val_top1@0.5=0.5686 | bal_top1=0.6261 (tpr=0.525, tnr=0.727)
epoch 3: loss=0.6803 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 4: loss=0.7194 val_top1@0.5=0.2353 | bal_top1=0.5125 (tpr=0.025, tnr=1.000)
epoch 5: loss=0.6216 val_top1@0.5=0.3333 | bal_top1=0.5420 (tpr=0.175, tnr=0.909)
epoch 6: loss=0.6275 val_top1@0.5=0.6471 | bal_top1=0.5773 (tpr=0.700, tnr=0.455)
epoch 7: loss=0.5332 val_top1@0.5=0.7451 | bal_top1=0.4750 (tpr=0.950, tnr=0.000)
fold 3 best top1@0.5=0.7843

--- fold 4/5 ---
epoch 1: loss=0.6894 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.7094 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6858 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.6918 val_top1@0.5=0.3529 | bal_top1=0.4886 (tpr=0.250, tnr=0.727)
epoch 5: loss=0.6739 val_top1@0.5=0.8039 | bal_top1=0.6114 (tpr=0.950, tnr=0.273)
epoch 6: loss=0.6049 val_top1@0.5=0.7843 | bal_top1=0.5989 (tpr=0.925, tnr=0.273)
epoch 7: loss=0.5584 val_top1@0.5=0.4510 | bal_top1=0.5182 (tpr=0.400, tnr=0.636)
epoch 8: loss=0.5777 val_top1@0.5=0.6275 | bal_top1=0.6307 (tpr=0.625, tnr=0.636)
epoch 9: loss=0.5358 val_top1@0.5=0.4706 | bal_top1=0.5966 (tpr=0.375, tnr=0.818)
fold 4 best top1@0.5=0.8039

--- fold 5/5 ---
epoch 1: loss=0.7049 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6918 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 3: loss=0.6724 val_top1@0.5=0.7059 | bal_top1=0.4830 (tpr=0.875, tnr=0.091)
epoch 4: loss=0.6652 val_top1@0.5=0.2353 | bal_top1=0.5125 (tpr=0.025, tnr=1.000)
epoch 5: loss=0.6584 val_top1@0.5=0.4118 | bal_top1=0.5591 (tpr=0.300, tnr=0.818)
epoch 6: loss=0.6429 val_top1@0.5=0.6863 | bal_top1=0.5693 (tpr=0.775, tnr=0.364)
fold 5 best top1@0.5=0.7843

[ctx_r2plus1d] CV mean top1@0.5=0.7961 ± 0.0096
[ctx_r2plus1d] OOF  top1@0.5=0.7961 | bal_top1=0.5234 (tpr=0.990, tnr=0.057)

================================================================================
Эксперимент: face_baseline | Модальность: face
ctx_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
face_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
skel_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
================================================================================

--- fold 1/5 ---
epoch 1: loss=0.6932 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 2: loss=0.6933 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6930 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.6928 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 5: loss=0.6937 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
fold 1 best top1@0.5=0.8039

--- fold 2/5 ---
epoch 1: loss=0.6932 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6933 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6930 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.6932 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 5: loss=0.6931 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
fold 2 best top1@0.5=0.1961

--- fold 3/5 ---
epoch 1: loss=0.6940 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6930 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6930 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.6938 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 5: loss=0.6912 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
fold 3 best top1@0.5=0.2157

--- fold 4/5 ---
epoch 1: loss=0.6906 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6930 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6910 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.6935 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 5: loss=0.6941 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
fold 4 best top1@0.5=0.2157

--- fold 5/5 ---
epoch 1: loss=0.6932 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6933 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6931 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 4: loss=0.6931 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 5: loss=0.6932 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 6: loss=0.6932 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 7: loss=0.6929 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
fold 5 best top1@0.5=0.7843

[face_baseline] CV mean top1@0.5=0.4431 ± 0.2867
[face_baseline] OOF  top1@0.5=0.4431 | bal_top1=0.5024 (tpr=0.401, tnr=0.604)

================================================================================
Эксперимент: face_3avg | Модальность: face
ctx_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
face_dir: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_3frames_avg
skel_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
================================================================================

--- fold 1/5 ---
epoch 1: loss=0.6923 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6929 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6932 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.6931 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 5: loss=0.6924 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
fold 1 best top1@0.5=0.1961

--- fold 2/5 ---
epoch 1: loss=0.6937 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6939 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6935 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.6931 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 5: loss=0.6932 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
fold 2 best top1@0.5=0.1961

--- fold 3/5 ---
epoch 1: loss=0.6930 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 2: loss=0.6930 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 3: loss=0.6943 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 4: loss=0.6916 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 5: loss=0.6941 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
fold 3 best top1@0.5=0.7843

--- fold 4/5 ---
epoch 1: loss=0.6936 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6920 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6940 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.6959 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 5: loss=0.6920 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
fold 4 best top1@0.5=0.2157

--- fold 5/5 ---
epoch 1: loss=0.6934 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 2: loss=0.6932 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 3: loss=0.6924 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 4: loss=0.6916 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 5: loss=0.6946 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
fold 5 best top1@0.5=0.7843

[face_3avg] CV mean top1@0.5=0.4353 ± 0.2851
[face_3avg] OOF  top1@0.5=0.4353 | bal_top1=0.4905 (tpr=0.396, tnr=0.585)

================================================================================
Эксперимент: face_center | Модальность: face
ctx_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
face_dir: /content/drive/MyDrive/miga_features_cache_agcn/exp_face_centercrop_fast
skel_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
================================================================================

--- fold 1/5 ---
epoch 1: loss=0.6920 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 2: loss=0.6935 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 3: loss=0.6925 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 4: loss=0.6931 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 5: loss=0.6957 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
fold 1 best top1@0.5=0.8039

--- fold 2/5 ---
epoch 1: loss=0.6918 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6911 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6939 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.6941 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 5: loss=0.6934 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
fold 2 best top1@0.5=0.1961

--- fold 3/5 ---
epoch 1: loss=0.6935 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 2: loss=0.6933 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 3: loss=0.6932 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 4: loss=0.6932 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 5: loss=0.6932 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
fold 3 best top1@0.5=0.7843

--- fold 4/5 ---
epoch 1: loss=0.6931 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6934 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6932 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.6933 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 5: loss=0.6931 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
fold 4 best top1@0.5=0.2157

--- fold 5/5 ---
epoch 1: loss=0.6959 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 2: loss=0.6929 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 3: loss=0.6930 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.6926 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 5: loss=0.6931 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
fold 5 best top1@0.5=0.2157

[face_center] CV mean top1@0.5=0.4431 ± 0.2867
[face_center] OOF  top1@0.5=0.4431 | bal_top1=0.5024 (tpr=0.401, tnr=0.604)

================================================================================
Эксперимент: skel_baseline | Модальность: skel
ctx_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_ctx
face_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
skel_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_skel
================================================================================

--- fold 1/5 ---
epoch 1: loss=0.6931 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 2: loss=0.6934 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 3: loss=0.6931 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 4: loss=0.6932 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 5: loss=0.6932 val_top1@0.5=0.8039 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
fold 1 best top1@0.5=0.8039

--- fold 2/5 ---
epoch 1: loss=0.6923 val_top1@0.5=0.1961 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)

,Experiment,Modality,Variant,Top-1 Accuracy (%),CV mean (%),CV std (%)
2,ctx_r2plus1d,ctx,r2plus1d,79.607843,79.607843,0.960584
0,ctx_baseline,ctx,baseline,79.215686,79.215686,0.960584
1,ctx_mc3,ctx,mc3,77.647059,77.647059,5.628510
3,face_baseline,face,baseline,44.313725,44.313725,28.673077
5,face_center,face,center,44.313725,44.313725,28.673077
4,face_3avg,face,3avg,43.529412,43.529412,28.506324
7,skel_meanstd,skel,meanstd,56.470588,56.470588,28.506324
6,skel_baseline,skel,baseline,55.686275,55.686275,28.673077
8,skel_max,skel,max,44.313725,44.313725,28.673077

**Для полной модели выбираем:**

ctx: exp_ctx_r2plus1d

face: baseline_face

skel: exp_skel_mean_std

In [53]:
import numpy as np
import pandas as pd
import os
import torch
from sklearn.model_selection import StratifiedKFold

BASE = "/content/drive/MyDrive/miga_features_cache_agcn"

best_ctx_dir = f"{BASE}/exp_ctx_r2plus1d"
best_face_dir = f"{BASE}/baseline_face"
best_skel_dir = f"{BASE}/exp_skel_mean_std"

# Настройка для полной модели (все модальности включены)
ab_cfg_all = {"use_ctx": True, "use_face": True, "use_skel": True}

print("Запуск полной трёхмодальной модели")
print(f"ctx_dir: {best_ctx_dir}")
print(f"face_dir: {best_face_dir}")
print(f"skel_dir: {best_skel_dir}")


# Запуск CV
result = run_cv_setting(
    df=df_ok,
    name="full_model_best",
    ab_cfg=ab_cfg_all,
    ctx_dir=best_ctx_dir,
    face_dir=best_face_dir,
    skel_dir=best_skel_dir,
    n_splits=5,
    epochs=12,
    lr=2e-4,
    wd=1e-4,
    bs=16
)

# Вывод итоговых метрик
print("\n" + "="*60)
print("РЕЗУЛЬТАТЫ ПОЛНОЙ МОДЕЛИ")
print("="*60)
print(f"OOF Top-1 Accuracy: {result['oof_acc05']*100:.2f}%")
print(f"OOF Balanced Accuracy: {result['oof_bacc05']*100:.2f}%")
print(f"CV mean accuracy: {np.mean(result['fold_scores'])*100:.2f}% ± {np.std(result['fold_scores'])*100:.2f}%")
print("="*60)

# Сохраняем результаты для дальнейшего использования
import pickle

# Сохраняем OOF-предсказания и метки
oof_data = {
    'y_true': result['oof_y'],
    'y_pred_proba': result['oof_p'],
    'fold_scores': result['fold_scores'],
    'best_state': result['best_state']
}

with open('/content/full_model_results.pkl', 'wb') as f:
    pickle.dump(oof_data, f)

print("\n Результаты сохранены в файл 'full_model_results.pkl'")

Запуск полной трёхмодальной модели
ctx_dir: /content/drive/MyDrive/miga_features_cache_agcn/exp_ctx_r2plus1d
face_dir: /content/drive/MyDrive/miga_features_cache_agcn/baseline_face
skel_dir: /content/drive/MyDrive/miga_features_cache_agcn/exp_skel_mean_std

--- fold 1/5 ---
epoch 1: loss=0.6920 val_top1@0.5=0.4706 | bal_top1=0.5573 (tpr=0.415, tnr=0.700)
epoch 2: loss=0.6675 val_top1@0.5=0.3333 | bal_top1=0.5854 (tpr=0.171, tnr=1.000)
epoch 3: loss=0.6648 val_top1@0.5=0.4706 | bal_top1=0.5951 (tpr=0.390, tnr=0.800)
epoch 4: loss=0.6320 val_top1@0.5=0.7059 | bal_top1=0.5524 (tpr=0.805, tnr=0.300)
epoch 5: loss=0.7480 val_top1@0.5=0.5686 | bal_top1=0.5805 (tpr=0.561, tnr=0.600)
epoch 6: loss=0.6443 val_top1@0.5=0.6863 | bal_top1=0.5780 (tpr=0.756, tnr=0.400)
epoch 7: loss=0.6762 val_top1@0.5=0.8039 | bal_top1=0.5378 (tpr=0.976, tnr=0.100)
epoch 8: loss=0.5066 val_top1@0.5=0.7255 | bal_top1=0.5268 (tpr=0.854, tnr=0.200)
epoch 9: loss=0.6580 val_top1@0.5=0.3922 | bal_top1=0.5841 (tpr=0.268, tnr=0.900)
epoch 10: loss=0.5470 val_top1@0.5=0.4118 | bal_top1=0.5963 (tpr=0.293, tnr=0.900)
epoch 11: loss=0.6032 val_top1@0.5=0.3137 | bal_top1=0.5354 (tpr=0.171, tnr=0.900)
fold 1 best top1@0.5=0.8039

--- fold 2/5 ---
epoch 1: loss=0.7342 val_top1@0.5=0.6078 | bal_top1=0.5671 (tpr=0.634, tnr=0.500)
epoch 2: loss=0.6971 val_top1@0.5=0.2941 | bal_top1=0.5610 (tpr=0.122, tnr=1.000)
epoch 3: loss=0.6713 val_top1@0.5=0.2157 | bal_top1=0.4366 (tpr=0.073, tnr=0.800)
epoch 4: loss=0.6733 val_top1@0.5=0.3137 | bal_top1=0.4976 (tpr=0.195, tnr=0.800)
epoch 5: loss=0.6183 val_top1@0.5=0.3529 | bal_top1=0.5220 (tpr=0.244, tnr=0.800)
fold 2 best top1@0.5=0.6078

--- fold 3/5 ---
epoch 1: loss=0.7127 val_top1@0.5=0.2353 | bal_top1=0.5125 (tpr=0.025, tnr=1.000)
epoch 2: loss=0.6774 val_top1@0.5=0.3725 | bal_top1=0.4682 (tpr=0.300, tnr=0.636)
epoch 3: loss=0.6399 val_top1@0.5=0.7059 | bal_top1=0.5159 (tpr=0.850, tnr=0.182)
epoch 4: loss=0.6399 val_top1@0.5=0.5882 | bal_top1=0.5398 (tpr=0.625, tnr=0.455)
epoch 5: loss=0.6786 val_top1@0.5=0.4706 | bal_top1=0.5307 (tpr=0.425, tnr=0.636)
epoch 6: loss=0.4842 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 7: loss=0.7632 val_top1@0.5=0.3333 | bal_top1=0.4432 (tpr=0.250, tnr=0.636)
epoch 8: loss=0.5422 val_top1@0.5=0.2353 | bal_top1=0.4136 (tpr=0.100, tnr=0.727)
epoch 9: loss=0.5126 val_top1@0.5=0.5490 | bal_top1=0.4818 (tpr=0.600, tnr=0.364)
epoch 10: loss=0.4078 val_top1@0.5=0.7059 | bal_top1=0.5159 (tpr=0.850, tnr=0.182)
fold 3 best top1@0.5=0.7843

--- fold 4/5 ---
epoch 1: loss=0.7147 val_top1@0.5=0.6275 | bal_top1=0.4659 (tpr=0.750, tnr=0.182)
epoch 2: loss=0.7065 val_top1@0.5=0.3922 | bal_top1=0.5466 (tpr=0.275, tnr=0.818)
epoch 3: loss=0.7612 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 4: loss=0.7663 val_top1@0.5=0.2157 | bal_top1=0.5000 (tpr=0.000, tnr=1.000)
epoch 5: loss=0.7293 val_top1@0.5=0.5294 | bal_top1=0.4693 (tpr=0.575, tnr=0.364)
fold 4 best top1@0.5=0.6275

--- fold 5/5 ---
epoch 1: loss=0.7209 val_top1@0.5=0.2745 | bal_top1=0.5045 (tpr=0.100, tnr=0.909)
epoch 2: loss=0.6961 val_top1@0.5=0.7843 | bal_top1=0.5000 (tpr=1.000, tnr=0.000)
epoch 3: loss=0.7066 val_top1@0.5=0.6275 | bal_top1=0.6636 (tpr=0.600, tnr=0.727)
epoch 4: loss=0.6642 val_top1@0.5=0.6275 | bal_top1=0.6966 (tpr=0.575, tnr=0.818)
epoch 5: loss=0.5755 val_top1@0.5=0.6078 | bal_top1=0.6841 (tpr=0.550, tnr=0.818)
epoch 6: loss=0.5062 val_top1@0.5=0.6275 | bal_top1=0.4659 (tpr=0.750, tnr=0.182)
fold 5 best top1@0.5=0.7843

[full_model_best] CV mean top1@0.5=0.7216 ± 0.0854
[full_model_best] OOF  top1@0.5=0.7216 | bal_top1=0.5111 (tpr=0.871, tnr=0.151)

============================================================
РЕЗУЛЬТАТЫ ПОЛНОЙ МОДЕЛИ
============================================================
OOF Top-1 Accuracy: 72.16%
OOF Balanced Accuracy: 51.11%
CV mean accuracy: 72.16% ± 8.54%
============================================================

 Результаты сохранены в файл 'full_model_results.pkl'

**PHASE 2**

In [20]:
ROOT = "/content/miga_data"
FEAT_DIR_P1 = "/content/drive/MyDrive/miga_features_cache_agcn"
FEAT_DIR_P2 = "/content/drive/MyDrive/miga_features_cache_agcn_p2"

In [21]:
import os, glob
import pandas as pd

RGB_PHASE2 = f"{ROOT}/imigue_rgb_phase2"
SK_P2_TEST = f"{ROOT}/imigue_data_phase2/imigue_skeleton_test"

def vid4(x):
    return f"{int(x):04d}"

def resolve_video_path_phase2(video_id):
    v = vid4(video_id)
    p = os.path.join(RGB_PHASE2, v, f"{v}.mp4")
    if os.path.exists(p):
        return p
    hits = glob.glob(os.path.join(RGB_PHASE2, "**", f"{v}.mp4"), recursive=True)
    return hits[0] if hits else None

def resolve_skeleton_path_phase2(video_id, prefer_hand=True):
    v = vid4(video_id)
    p_hand  = os.path.join(SK_P2_TEST, v, f"{v}_light_hand.csv")
    p_light = os.path.join(SK_P2_TEST, v, f"{v}_light.csv")
    if prefer_hand and os.path.exists(p_hand):
        return p_hand
    if os.path.exists(p_light):
        return p_light
    if os.path.exists(p_hand):
        return p_hand
    return None

ids = sorted([int(os.path.basename(p)) for p in glob.glob(os.path.join(SK_P2_TEST, "[0-9][0-9][0-9][0-9]"))])

rows = []
miss_v, miss_s = 0, 0
for vid in ids:
    vpath = resolve_video_path_phase2(vid)
    spath = resolve_skeleton_path_phase2(vid)
    if vpath is None:
        miss_v += 1
    if spath is None:
        miss_s += 1
    rows.append({
        "video_id": vid,
        "split": "test",
        "video_path": vpath,
        "skeleton_path": spath
    })

phase2_df = pd.DataFrame(rows).sort_values("video_id").reset_index(drop=True)
print("Phase2 rows:", len(phase2_df), "missing video:", miss_v, "missing skeleton:", miss_s)

PHASE2_CSV = "/content/phase2_all_with_paths.csv"
phase2_df.to_csv(PHASE2_CSV, index=False)
print("Saved:", PHASE2_CSV)
phase2_df.head()

Phase2 rows: 104 missing video: 0 missing skeleton: 0
Saved: /content/phase2_all_with_paths.csv

,video_id,split,video_path,skeleton_path
0,54,test,/content/miga_data/imigue_rgb_phase2/0054/0054...,/content/miga_data/imigue_data_phase2/imigue_s...
1,67,test,/content/miga_data/imigue_rgb_phase2/0067/0067...,/content/miga_data/imigue_data_phase2/imigue_s...
2,69,test,/content/miga_data/imigue_rgb_phase2/0069/0069...,/content/miga_data/imigue_data_phase2/imigue_s...
3,70,test,/content/miga_data/imigue_rgb_phase2/0070/0070...,/content/miga_data/imigue_data_phase2/imigue_s...
4,71,test,/content/miga_data/imigue_rgb_phase2/0071/0071...,/content/miga_data/imigue_data_phase2/imigue_s...

**Контекст (r2plus1d_18)**

In [22]:
%%bash
export CTX_BACKBONE=r2plus1d_18

CHUNK=64
SHARD=10
DEVICE=cuda
CSV=/content/phase2_all_with_paths.csv
BASE_FEAT_DIR_P2=/content/drive/MyDrive/miga_features_cache_agcn_p2
EXP_NAME=exp_ctx_r2plus1d
FEAT_DIR=${BASE_FEAT_DIR_P2}/${EXP_NAME}

mkdir -p "$FEAT_DIR"

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase2_all_with_paths.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD))
  if [ $END -gt $TOTAL ]; then END=$TOTAL; fi

  echo "=== CTX phase2 (r2plus1d) shard $START:$END (chunk=$CHUNK) ==="
  PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 python -u /content/src/cache_features_cli.py \
    --csv $CSV --phase 2 --feat_dir "$FEAT_DIR" \
    --chunk $CHUNK --start $START --end $END --device $DEVICE \
    --do_ctx

  START=$END
done

=== CTX phase2 (r2plus1d) shard 0:10 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False
Downloading: "https://download.pytorch.org/models/r2plus1d_18-91a641e6.pth" to /root/.cache/torch/hub/checkpoints/r2plus1d_18-91a641e6.pth

DONE shard [0:10) ok=10 bad=0
=== CTX phase2 (r2plus1d) shard 10:20 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [10:20) ok=10 bad=0
=== CTX phase2 (r2plus1d) shard 20:30 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [20:30) ok=10 bad=0
=== CTX phase2 (r2plus1d) shard 30:40 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [30:40) ok=10 bad=0
=== CTX phase2 (r2plus1d) shard 40:50 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [40:50) ok=10 bad=0
=== CTX phase2 (r2plus1d) shard 50:60 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [50:60) ok=10 bad=0
=== CTX phase2 (r2plus1d) shard 60:70 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [60:70) ok=10 bad=0
=== CTX phase2 (r2plus1d) shard 70:80 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [70:80) ok=10 bad=0
=== CTX phase2 (r2plus1d) shard 80:90 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [80:90) ok=10 bad=0
=== CTX phase2 (r2plus1d) shard 90:100 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [90:100) ok=10 bad=0
=== CTX phase2 (r2plus1d) shard 100:104 (chunk=64) ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_ctx_r2plus1d
MODES: ctx= True face= False skel= False

DONE shard [100:104) ok=4 bad=0

  0%|          | 0/10 [00:00<?, ?it/s]
  0%|          | 0.00/120M [00:00<?, ?B/s]
 16%|█▋        | 19.6M/120M [00:00<00:00, 205MB/s]
 34%|███▍      | 40.9M/120M [00:00<00:00, 215MB/s]
 51%|█████▏    | 61.9M/120M [00:00<00:00, 217MB/s]
 69%|██████▉   | 83.1M/120M [00:00<00:00, 219MB/s]
100%|██████████| 120M/120M [00:00<00:00, 219MB/s]
100%|██████████| 10/10 [05:11<00:00, 31.14s/it]
100%|██████████| 10/10 [06:25<00:00, 38.51s/it]
100%|██████████| 10/10 [07:48<00:00, 46.88s/it]
100%|██████████| 10/10 [06:59<00:00, 41.97s/it]
100%|██████████| 10/10 [06:38<00:00, 39.87s/it]
100%|██████████| 10/10 [09:47<00:00, 58.72s/it]
100%|██████████| 10/10 [13:05<00:00, 78.58s/it]
100%|██████████| 10/10 [11:08<00:00, 66.88s/it]
100%|██████████| 10/10 [12:17<00:00, 73.80s/it]
100%|██████████| 10/10 [06:44<00:00, 40.42s/it]
100%|██████████| 4/4 [03:23<00:00, 50.76s/it]

**Лицо (baseline: mid + yolo)**

In [23]:
%%bash
export FACE_SAMPLING=mid
export FACE_DETECT=yolo

CHUNK=32
SHARD=5
DEVICE=cuda
CSV=/content/phase2_all_with_paths.csv
BASE_FEAT_DIR_P2=/content/drive/MyDrive/miga_features_cache_agcn_p2
EXP_NAME=baseline_face
FEAT_DIR=${BASE_FEAT_DIR_P2}/${EXP_NAME}

mkdir -p "$FEAT_DIR"

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase2_all_with_paths.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD))
  if [ $END -gt $TOTAL ]; then END=$TOTAL; fi

  echo "=== FACE phase2 (baseline) shard $START:$END ==="
  PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 python -u /content/src/cache_features_cli.py \
    --csv $CSV --phase 2 --feat_dir "$FEAT_DIR" \
    --chunk $CHUNK --start $START --end $END --device $DEVICE \
    --do_face

  START=$END
done

=== FACE phase2 (baseline) shard 0:5 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n.pt to 'yolov8n.pt'...
Downloading enet_b0_8_best_vgaf.pt from https://github.com/sb-ai-lab/EmotiEffLib/blob/main/models/affectnet_emotions/enet_b0_8_best_vgaf.pt?raw=true

DONE shard [0:5) ok=5 bad=0
=== FACE phase2 (baseline) shard 5:10 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [5:10) ok=5 bad=0
=== FACE phase2 (baseline) shard 10:15 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [10:15) ok=5 bad=0
=== FACE phase2 (baseline) shard 15:20 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [15:20) ok=5 bad=0
=== FACE phase2 (baseline) shard 20:25 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [20:25) ok=5 bad=0
=== FACE phase2 (baseline) shard 25:30 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [25:30) ok=5 bad=0
=== FACE phase2 (baseline) shard 30:35 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [30:35) ok=5 bad=0
=== FACE phase2 (baseline) shard 35:40 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [35:40) ok=5 bad=0
=== FACE phase2 (baseline) shard 40:45 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [40:45) ok=5 bad=0
=== FACE phase2 (baseline) shard 45:50 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [45:50) ok=5 bad=0
=== FACE phase2 (baseline) shard 50:55 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [50:55) ok=5 bad=0
=== FACE phase2 (baseline) shard 55:60 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [55:60) ok=5 bad=0
=== FACE phase2 (baseline) shard 60:65 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [60:65) ok=5 bad=0
=== FACE phase2 (baseline) shard 65:70 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [65:70) ok=5 bad=0
=== FACE phase2 (baseline) shard 70:75 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [70:75) ok=5 bad=0
=== FACE phase2 (baseline) shard 75:80 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [75:80) ok=5 bad=0
=== FACE phase2 (baseline) shard 80:85 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [80:85) ok=5 bad=0
=== FACE phase2 (baseline) shard 85:90 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [85:90) ok=5 bad=0
=== FACE phase2 (baseline) shard 90:95 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [90:95) ok=5 bad=0
=== FACE phase2 (baseline) shard 95:100 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [95:100) ok=5 bad=0
=== FACE phase2 (baseline) shard 100:104 ===
DEVICE: cuda
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/baseline_face
MODES: ctx= False face= True skel= False

DONE shard [100:104) ok=4 bad=0

  0%|          | 0/5 [00:00<?, ?it/s]
100%|██████████| 6.25M/6.25M [00:00<00:00, 146MB/s]
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323246.758227   63198 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323246.766003   63198 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323246.787413   63198 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323246.787447   63198 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323246.787449   63198 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323246.787451   63198 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [00:45<00:00,  9.05s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323295.475577   63866 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323295.484266   63866 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323295.507877   63866 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323295.507916   63866 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323295.507919   63866 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323295.507922   63866 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [00:40<00:00,  8.11s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323340.485980   64486 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323340.493727   64486 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323340.516890   64486 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323340.516923   64486 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323340.516925   64486 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323340.516927   64486 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[h264 @ 0x1b182200] mmco: unref short failure
[h264 @ 0x1b182200] mmco: unref short failure
100%|██████████| 5/5 [00:42<00:00,  8.50s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323387.061257   65140 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323387.068778   65140 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323387.088994   65140 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323387.089029   65140 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323387.089031   65140 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323387.089033   65140 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [00:54<00:00, 10.95s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323446.750941   66198 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323446.758672   66198 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323446.782078   66198 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323446.782124   66198 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323446.782127   66198 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323446.782129   66198 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[h264 @ 0x37ab26c0] mmco: unref short failure
[h264 @ 0x37ab26c0] mmco: unref short failure
 20%|██        | 1/5 [00:19<01:17, 19.34s/it][h264 @ 0x37c25fc0] mmco: unref short failure
100%|██████████| 5/5 [00:55<00:00, 11.12s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323506.618012   67102 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323506.625644   67102 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323506.646521   67102 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323506.646558   67102 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323506.646561   67102 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323506.646563   67102 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 20%|██        | 1/5 [00:20<01:20, 20.10s/it][h264 @ 0x45782540] mmco: unref short failure
[h264 @ 0x45782540] mmco: unref short failure
100%|██████████| 5/5 [00:52<00:00, 10.47s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323563.541736   67958 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323563.549629   67958 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323563.574539   67958 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323563.574585   67958 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323563.574588   67958 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323563.574590   67958 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [00:51<00:00, 10.33s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323619.986108   68794 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323619.993803   68794 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323620.015040   68794 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323620.015082   68794 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323620.015085   68794 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323620.015087   68794 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[h264 @ 0x2074a800] mmco: unref short failure
 40%|████      | 2/5 [00:28<00:39, 13.14s/it][h264 @ 0x21849880] mmco: unref short failure
100%|██████████| 5/5 [00:46<00:00,  9.35s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323671.718768   69556 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323671.728298   69556 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323671.750591   69556 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323671.750629   69556 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323671.750632   69556 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323671.750635   69556 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 20%|██        | 1/5 [00:21<01:27, 21.90s/it][h264 @ 0xd690f40] mmco: unref short failure
[h264 @ 0xd690f40] mmco: unref short failure
100%|██████████| 5/5 [00:50<00:00, 10.03s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323726.069039   70360 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323726.078646   70360 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323726.100109   70360 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323726.100146   70360 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323726.100149   70360 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323726.100150   70360 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 40%|████      | 2/5 [00:27<00:38, 12.88s/it][h264 @ 0xe2f1000] mmco: unref short failure
 60%|██████    | 3/5 [00:34<00:20, 10.31s/it][h264 @ 0x34f46a40] mmco: unref short failure
100%|██████████| 5/5 [00:46<00:00,  9.36s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323777.506384   71125 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323777.514232   71125 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323777.535965   71125 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323777.536001   71125 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323777.536003   71125 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323777.536005   71125 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [00:58<00:00, 11.79s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323841.251958   72083 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323841.259592   72083 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323841.282604   72083 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323841.282641   72083 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323841.282644   72083 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323841.282646   72083 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
 40%|████      | 2/5 [00:44<01:01, 20.65s/it][h264 @ 0x29e49a00] mmco: unref short failure
[h264 @ 0x29e49a00] mmco: unref short failure
100%|██████████| 5/5 [01:11<00:00, 14.27s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771323916.815813   73206 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771323916.823656   73206 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771323916.846298   73206 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323916.846334   73206 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323916.846337   73206 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771323916.846339   73206 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:27<00:00, 17.46s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771324008.550971   74632 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771324008.558827   74632 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771324008.580240   74632 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771324008.580272   74632 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771324008.580274   74632 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771324008.580276   74632 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[h264 @ 0x148a7a00] mmco: unref short failure
[h264 @ 0x148a7a00] mmco: unref short failure
100%|██████████| 5/5 [01:13<00:00, 14.68s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771324086.436767   75851 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771324086.446333   75851 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771324086.468054   75851 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771324086.468100   75851 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771324086.468103   75851 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771324086.468105   75851 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
100%|██████████| 5/5 [01:11<00:00, 14.35s/it]
  0%|          | 0/5 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1771324162.778821   77029 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771324162.786553   77029 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

**Скелет (mean_std)**

In [24]:
%%bash
export SKEL_AGG=mean_std

CHUNK=32
SHARD=10
DEVICE=cpu
CSV=/content/phase2_all_with_paths.csv
BASE_FEAT_DIR_P2=/content/drive/MyDrive/miga_features_cache_agcn_p2
EXP_NAME=exp_skel_mean_std
FEAT_DIR=${BASE_FEAT_DIR_P2}/${EXP_NAME}

mkdir -p "$FEAT_DIR"

TOTAL=$(python - <<'PY'
import pandas as pd
print(len(pd.read_csv("/content/phase2_all_with_paths.csv")))
PY
)

START=0
while [ $START -lt $TOTAL ]; do
  END=$((START+SHARD))
  if [ $END -gt $TOTAL ]; then END=$TOTAL; fi

  echo "=== SKEL phase2 (mean_std) shard $START:$END ==="
  PYTHONPATH=/content PYTHONDONTWRITEBYTECODE=1 python -u /content/src/cache_features_cli.py \
    --csv $CSV --phase 2 --feat_dir "$FEAT_DIR" \
    --chunk $CHUNK --start $START --end $END --device $DEVICE \
    --do_skel

  START=$END
done

=== SKEL phase2 (mean_std) shard 0:10 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [0:10) ok=10 bad=0
=== SKEL phase2 (mean_std) shard 10:20 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [10:20) ok=10 bad=0
=== SKEL phase2 (mean_std) shard 20:30 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [20:30) ok=10 bad=0
=== SKEL phase2 (mean_std) shard 30:40 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [30:40) ok=10 bad=0
=== SKEL phase2 (mean_std) shard 40:50 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [40:50) ok=10 bad=0
=== SKEL phase2 (mean_std) shard 50:60 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [50:60) ok=10 bad=0
=== SKEL phase2 (mean_std) shard 60:70 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [60:70) ok=10 bad=0
=== SKEL phase2 (mean_std) shard 70:80 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [70:80) ok=10 bad=0
=== SKEL phase2 (mean_std) shard 80:90 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [80:90) ok=10 bad=0
=== SKEL phase2 (mean_std) shard 90:100 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [90:100) ok=10 bad=0
=== SKEL phase2 (mean_std) shard 100:104 ===
DEVICE: cpu
FEAT_DIR: /content/drive/MyDrive/miga_features_cache_agcn_p2/exp_skel_mean_std
MODES: ctx= False face= False skel= True

DONE shard [100:104) ok=4 bad=0

100%|██████████| 10/10 [00:01<00:00,  8.96it/s]
100%|██████████| 10/10 [00:01<00:00,  7.01it/s]
100%|██████████| 10/10 [00:01<00:00,  5.78it/s]
100%|██████████| 10/10 [00:01<00:00,  6.58it/s]
100%|██████████| 10/10 [00:01<00:00,  6.86it/s]
100%|██████████| 10/10 [00:02<00:00,  4.72it/s]
100%|██████████| 10/10 [00:02<00:00,  3.56it/s]
100%|██████████| 10/10 [00:02<00:00,  4.29it/s]
100%|██████████| 10/10 [00:02<00:00,  3.90it/s]
100%|██████████| 10/10 [00:01<00:00,  6.58it/s]
100%|██████████| 4/4 [00:00<00:00,  5.29it/s]

**Inference**

In [56]:
import os
import pickle
import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader
from src.ds import Track3CachedDataset, collate_fn
from src.model import TriStreamModel

device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

BASE_P2 = "/content/drive/MyDrive/miga_features_cache_agcn_p2"
test_ctx_dir = f"{BASE_P2}/exp_ctx_r2plus1d"
test_face_dir = f"{BASE_P2}/baseline_face"
test_skel_dir = f"{BASE_P2}/exp_skel_mean_std"

model_state_path = "/content/full_model_results.pkl"

with open(model_state_path, 'rb') as f:
    model_data = pickle.load(f)
best_state = model_data['best_state']
print("Модель загружена. Ключи:", best_state.keys() if best_state else None)


test_csv = "/content/phase2_all_with_paths.csv"
test_df = pd.read_csv(test_csv)
print(f"Загружено тестовых образцов: {len(test_df)}")


test_ds = Track3CachedDataset(
    test_df,
    ctx_dir=test_ctx_dir,
    face_dir=test_face_dir,
    skel_dir=test_skel_dir,
    phase=2,
    has_label=False,
    use_ctx=True,
    use_face=True,
    use_skel=True
)

test_loader = DataLoader(
    test_ds,
    batch_size=16,
    shuffle=False,
    num_workers=0,
    collate_fn=collate_fn,
    pin_memory=True
)

# ---- создаём модель и загружаем веса ----
model = TriStreamModel(
    d_ctx_in=d_ctx_in,
    d_face_in=D_FACE,
    d_skel_in=d_skel_in,
    d=512,
    n_layers=4,
    n_heads=4,
    dropout=0.3,
).to(device)

model.load_state_dict(best_state)
model.eval()
print("Модель инициализирована и веса загружены.")

# ---- инференс ----
all_ids = []
all_probs = []

with torch.no_grad():
    for batch in test_loader:
        ids = batch["id"]
        logits = model(
            batch["ctx"].to(device, non_blocking=True),
            batch["face"].to(device, non_blocking=True),
            batch["skel"].to(device, non_blocking=True),
            batch["time_mask"].to(device, non_blocking=True),
            batch["face_mask"].to(device, non_blocking=True),
            batch["skel_mask"].to(device, non_blocking=True),
        )
        probs = torch.sigmoid(logits).cpu().numpy()
        all_ids.extend(ids)
        all_probs.extend(probs)

results_df = pd.DataFrame({
    "video_id": all_ids,
    "prediction": all_probs
})


output_path = "/content/phase2_predictions.csv"
results_df.to_csv(output_path, index=False)
print(f"Предсказания сохранены в {output_path}")
print(results_df.head())

device: cuda
Модель загружена. Ключи: dict_keys(['ctx_in.0.weight', 'ctx_in.0.bias', 'face_in.0.weight', 'face_in.0.bias', 'skel_in.0.weight', 'skel_in.0.bias', 'ctx_enc.layers.0.self_attn.in_proj_weight', 'ctx_enc.layers.0.self_attn.in_proj_bias', 'ctx_enc.layers.0.self_attn.out_proj.weight', 'ctx_enc.layers.0.self_attn.out_proj.bias', 'ctx_enc.layers.0.linear1.weight', 'ctx_enc.layers.0.linear1.bias', 'ctx_enc.layers.0.linear2.weight', 'ctx_enc.layers.0.linear2.bias', 'ctx_enc.layers.0.norm1.weight', 'ctx_enc.layers.0.norm1.bias', 'ctx_enc.layers.0.norm2.weight', 'ctx_enc.layers.0.norm2.bias', 'ctx_enc.layers.1.self_attn.in_proj_weight', 'ctx_enc.layers.1.self_attn.in_proj_bias', 'ctx_enc.layers.1.self_attn.out_proj.weight', 'ctx_enc.layers.1.self_attn.out_proj.bias', 'ctx_enc.layers.1.linear1.weight', 'ctx_enc.layers.1.linear1.bias', 'ctx_enc.layers.1.linear2.weight', 'ctx_enc.layers.1.linear2.bias', 'ctx_enc.layers.1.norm1.weight', 'ctx_enc.layers.1.norm1.bias', 'ctx_enc.layers.1.norm2.weight', 'ctx_enc.layers.1.norm2.bias', 'ctx_enc.layers.2.self_attn.in_proj_weight', 'ctx_enc.layers.2.self_attn.in_proj_bias', 'ctx_enc.layers.2.self_attn.out_proj.weight', 'ctx_enc.layers.2.self_attn.out_proj.bias', 'ctx_enc.layers.2.linear1.weight', 'ctx_enc.layers.2.linear1.bias', 'ctx_enc.layers.2.linear2.weight', 'ctx_enc.layers.2.linear2.bias', 'ctx_enc.layers.2.norm1.weight', 'ctx_enc.layers.2.norm1.bias', 'ctx_enc.layers.2.norm2.weight', 'ctx_enc.layers.2.norm2.bias', 'ctx_enc.layers.3.self_attn.in_proj_weight', 'ctx_enc.layers.3.self_attn.in_proj_bias', 'ctx_enc.layers.3.self_attn.out_proj.weight', 'ctx_enc.layers.3.self_attn.out_proj.bias', 'ctx_enc.layers.3.linear1.weight', 'ctx_enc.layers.3.linear1.bias', 'ctx_enc.layers.3.linear2.weight', 'ctx_enc.layers.3.linear2.bias', 'ctx_enc.layers.3.norm1.weight', 'ctx_enc.layers.3.norm1.bias', 'ctx_enc.layers.3.norm2.weight', 'ctx_enc.layers.3.norm2.bias', 'face_enc.layers.0.self_attn.in_proj_weight', 'face_enc.layers.0.self_attn.in_proj_bias', 'face_enc.layers.0.self_attn.out_proj.weight', 'face_enc.layers.0.self_attn.out_proj.bias', 'face_enc.layers.0.linear1.weight', 'face_enc.layers.0.linear1.bias', 'face_enc.layers.0.linear2.weight', 'face_enc.layers.0.linear2.bias', 'face_enc.layers.0.norm1.weight', 'face_enc.layers.0.norm1.bias', 'face_enc.layers.0.norm2.weight', 'face_enc.layers.0.norm2.bias', 'face_enc.layers.1.self_attn.in_proj_weight', 'face_enc.layers.1.self_attn.in_proj_bias', 'face_enc.layers.1.self_attn.out_proj.weight', 'face_enc.layers.1.self_attn.out_proj.bias', 'face_enc.layers.1.linear1.weight', 'face_enc.layers.1.linear1.bias', 'face_enc.layers.1.linear2.weight', 'face_enc.layers.1.linear2.bias', 'face_enc.layers.1.norm1.weight', 'face_enc.layers.1.norm1.bias', 'face_enc.layers.1.norm2.weight', 'face_enc.layers.1.norm2.bias', 'face_enc.layers.2.self_attn.in_proj_weight', 'face_enc.layers.2.self_attn.in_proj_bias', 'face_enc.layers.2.self_attn.out_proj.weight', 'face_enc.layers.2.self_attn.out_proj.bias', 'face_enc.layers.2.linear1.weight', 'face_enc.layers.2.linear1.bias', 'face_enc.layers.2.linear2.weight', 'face_enc.layers.2.linear2.bias', 'face_enc.layers.2.norm1.weight', 'face_enc.layers.2.norm1.bias', 'face_enc.layers.2.norm2.weight', 'face_enc.layers.2.norm2.bias', 'face_enc.layers.3.self_attn.in_proj_weight', 'face_enc.layers.3.self_attn.in_proj_bias', 'face_enc.layers.3.self_attn.out_proj.weight', 'face_enc.layers.3.self_attn.out_proj.bias', 'face_enc.layers.3.linear1.weight', 'face_enc.layers.3.linear1.bias', 'face_enc.layers.3.linear2.weight', 'face_enc.layers.3.linear2.bias', 'face_enc.layers.3.norm1.weight', 'face_enc.layers.3.norm1.bias', 'face_enc.layers.3.norm2.weight', 'face_enc.layers.3.norm2.bias', 'skel_enc.layers.0.self_attn.in_proj_weight', 'skel_enc.layers.0.self_attn.in_proj_bias', 'skel_enc.layers.0.self_attn.out_proj.weight', 'skel_enc.layers.0.self_attn.out_proj.bias', 'skel_enc.layers.0.linear1.weight', 'skel_enc.layers.0.linear1.bias', 'skel_enc.layers.0.linear2.weight', 'skel_enc.layers.0.linear2.bias', 'skel_enc.layers.0.norm1.weight', 'skel_enc.layers.0.norm1.bias', 'skel_enc.layers.0.norm2.weight', 'skel_enc.layers.0.norm2.bias', 'skel_enc.layers.1.self_attn.in_proj_weight', 'skel_enc.layers.1.self_attn.in_proj_bias', 'skel_enc.layers.1.self_attn.out_proj.weight', 'skel_enc.layers.1.self_attn.out_proj.bias', 'skel_enc.layers.1.linear1.weight', 'skel_enc.layers.1.linear1.bias', 'skel_enc.layers.1.linear2.weight', 'skel_enc.layers.1.linear2.bias', 'skel_enc.layers.1.norm1.weight', 'skel_enc.layers.1.norm1.bias', 'skel_enc.layers.1.norm2.weight', 'skel_enc.layers.1.norm2.bias', 'skel_enc.layers.2.self_attn.in_proj_weight', 'skel_enc.layers.2.self_attn.in_proj_bias', 'skel_enc.layers.2.self_attn.out_proj.weight', 'skel_enc.layers.2.self_attn.out_proj.bias', 'skel_enc.layers.2.linear1.weight', 'skel_enc.layers.2.linear1.bias', 'skel_enc.layers.2.linear2.weight', 'skel_enc.layers.2.linear2.bias', 'skel_enc.layers.2.norm1.weight', 'skel_enc.layers.2.norm1.bias', 'skel_enc.layers.2.norm2.weight', 'skel_enc.layers.2.norm2.bias', 'skel_enc.layers.3.self_attn.in_proj_weight', 'skel_enc.layers.3.self_attn.in_proj_bias', 'skel_enc.layers.3.self_attn.out_proj.weight', 'skel_enc.layers.3.self_attn.out_proj.bias', 'skel_enc.layers.3.linear1.weight', 'skel_enc.layers.3.linear1.bias', 'skel_enc.layers.3.linear2.weight', 'skel_enc.layers.3.linear2.bias', 'skel_enc.layers.3.norm1.weight', 'skel_enc.layers.3.norm1.bias', 'skel_enc.layers.3.norm2.weight', 'skel_enc.layers.3.norm2.bias', 'ctx_pool.scorer.0.weight', 'ctx_pool.scorer.0.bias', 'ctx_pool.scorer.2.weight', 'ctx_pool.scorer.2.bias', 'face_pool.scorer.0.weight', 'face_pool.scorer.0.bias', 'face_pool.scorer.2.weight', 'face_pool.scorer.2.bias', 'skel_pool.scorer.0.weight', 'skel_pool.scorer.0.bias', 'skel_pool.scorer.2.weight', 'skel_pool.scorer.2.bias', 'head.1.weight', 'head.1.bias', 'head.4.weight', 'head.4.bias'])
Загружено тестовых образцов: 104
Модель инициализирована и веса загружены.
Предсказания сохранены в /content/phase2_predictions.csv
   video_id  prediction
0        54    0.804344
1        67    0.928574
2        69    0.808915
3        70    0.777509
4        71    0.779696